### ISSUE TITLE
focus-manager: Think about module

### ISSUE THREAD

**Issue by narqo** [bem/bem-components#1026]
We need to think about `focus-manager` module which would "lock" user's focus inside some DOM context.

Yandex login dialog ("domik") is a bright example of a consumer for this module: it's a `modal` (#798) with form inside of it. User must not have any opportunity to go outside of the dialog until it is open.

See links below for inspiration:
- http://msdn.microsoft.com/en-us/library/system.windows.input.focusmanager(v=vs.110).aspx
- http://yuilibrary.com/yui/docs/node-focusmanager/

**Comment by persidskiy** [comment]
:+1:

**Comment by aristov** [comment]
It looks like bem-core module.

**Comment by narqo** [comment]
More articles for inspiration: https://developer.mozilla.org/en-US/docs/Web/Accessibility/Keyboard-navigable_JavaScript_widgets#Managing_focus_inside_groups

**Comment by veged** [comment]
agree with @aristov for move such block to bem-core

**Comment by aristov** [comment]
Each block should manage it's focus behaviour by itself. Close in favour of #1673. Reopen if needed.
