### ISSUE TITLE
popup: _target_position + directions + offsets

### ISSUE THREAD

**Issue by persidskiy** [bem/bem-components#1027]
The API of [setPosition()] says that popup will be placed at passed coordinated, but it's not true: the popup will choose good position for itself using `directions` and consider `mainOffset` ,`secondaryOffset` and `viewportOffset`. Thus, result can be unexpectable.

Maybe we need to leave this params only for `popup_target_anchor` ?

**Comment by narqo** [comment]
We discussed this during work on #968. Current behaviour works correctly, accordion our concept of what "position" means. At the same time, we decided that the "unexpected results" you're talking, could be prevented with specifying exact single value of popup direction.

**Comment by persidskiy** [comment]
Ok
