### ISSUE TITLE
Rename "normal" theme to "islands"

### ISSUE THREAD

**Issue by narqo** [bem/bem-components#1038]
Current `normal` theme has nothing "normal" in it's name, as well as in the way it looks. I propose the name `islands` as it sounds much clearer from the open source POV (at least we have http://islands.yandex.com as "a historical reasons to call it "islands")

**Comment by tadatuta** [comment]
+1

**Comment by blond** [comment]
:+1:

**Comment by sipayRT** [comment]
+1

**Comment by tavriaforever** [comment]
:+1:

**Comment by voischev** [comment]
+1

**Comment by innabelaya** [comment]
+1 
С удовольствием поправлю в документации, как только решите поменять :)

**Comment by veged** [comment]
сколько ещё надо +1 чтобы сделать? ;-)

**Comment by narqo** [comment]
Сделаю на этой неделе

**Comment by mishanga** [comment]
:+1: ;)
