### ISSUE TITLE
Нужен метод для получения всех возможных значений контрола

### ISSUE THREAD

**Issue by aliosv** [bem/bem-components#1043]
(select|checkbox-group||radio-group).getValues() -> [{ checked, text, value }]

**Comment by tadatuta** [comment]
приведи пример использования

**Comment by aliosv** [comment]
дропаю текст, нахожу вхождения из item.text, устанавливаю нужные значения в контроле.

**Comment by tadatuta** [comment]
расскажи подробнее, что мешает использовать для этого текущее api?

**Comment by aliosv** [comment]
Ничего, но хочется получать значения за вызов одного метода. В select сейчас приходится использовать поле _menu, которое в апи не входит(логично по аналогии с checkbox-group.getCheckboxes() создать select.getMenu()).

**Comment by aliosv** [comment]
пример из проекта:

``` js
var control = this.findBlockInside('select') || this.findBlockInside('checkbox-group'),
  items = control._menu ?
    control._menu.getItems().map(function(item) {
      return { text : item.domElem.text().toLowerCase(), val : item.params.val };
    }) :
    control.getCheckboxes().map(function(item) {
      return { text : item.domElem.text().toLowerCase(), val : item.getVal() };
    });
```

**Comment by tadatuta** [comment]
считаю, что хотеть такого вредно ;)

**Comment by veged** [comment]
у `select` есть метод `setVal`, который может принимать массив значений — подразумевается, что это будет использоваться для установки значений

использование `item.domElem.text()` для того, чтобы что-то понимать про значение выглядит не правильным, т.к. в тексте содержится какой-то декоративный текст — функциональная связь должна быть сделана более явно по значениям, без ковыряния в сыром html

я бы предложил такую архитектуру:
- есть блок (или функция в существующем верхнеуровневом блоке), который мапит потенциально дропаемый текст на конкретные значения
- результат мапинга в виде значений используется через `setVal` (который одинаково доступен и для `select` и для `checkbox-group`)

**Comment by aliosv** [comment]
@veged
- от того, что я прокину значения архитектурно верно, они не поменяются, на выходе будет то же, что я возьму из html, а т.к. страница строится через bemtree, то мне придется прокидывать их через js.params, больше трафика, ноль профита. Но в теории я с тобой согласен.

Еще пример: если хочется только вывести где-то checked значения, также прокидывать все items?

**Comment by veged** [comment]
они не поменяются "по счастливому совпадению" ;-) именно этим устойчивая архитектура отличается

если где-то хочется выводить checked значения, то я опять же порекомендовал бы воспользоваться всё тем же специальным блоком, который ставит в соответствие человекочитаемые тексты и внутренние данные

альтернативным решением может быть разве что использование самих тайтлов в качестве значений — это если действительно предметная область такова, что это они и есть

**Comment by aliosv** [comment]
@veged, что скажешь касательно добавления select.getMenu() вместо текущего обращения к select._menu ?

**Comment by veged** [comment]
@aliosv пока я не увидел необходимости открывать наружу эти внутренние детали реализации — а если сильной необходимости нет, то лучше этого не делать (маленькое апи проще и учить, и поддерживать)

**Comment by dfilatov** [comment]
`menu` — это внутренняя реализация этого блока, завтра он может быть сделан по-другому, поэтому открывать к нему доступ нельзя.

**Comment by aliosv** [comment]
@dfilatov, чекбоксы - внутренняя реализация checkbox-group, почему к ним у нас есть доступ через апи?

**Comment by dfilatov** [comment]
@aliosv мне как-то сложно представить, что группа чекбоксов сделана не через чекбоксы.

**Comment by qfox** [comment]
@aliosv Я согласен с @dfilatov, что `_menu` или `getMenu` использовать нельзя, но почему в то же время @veged против `getOptions` — я не до конца понимаю. Правда, тут вопрос, что именно `getOptions` должен возвращать.

Задача связана, на мой взгляд, с #1163, её решили пока вообще не делать.

Может эту тоже закроем?
