### ISSUE TITLE
Upgrade Gemini to 0.8.2

### ISSUE THREAD

**Issue by aristov** [bem/bem-components#1044]

**Comment by aristov** [comment]
@SevInf 
I run `gemini test` and get:

```
Error: Cannot launch browser chrome-v35:
[init({"takesScreenshot":true,"record-screenshots":false,"record-video":false,"screen-resolution":"1024x768","max-duration":7200,"browserName":"chrome","version":35,"platform":"Linux"})] The environment you requested was unavailable.
```

or

```
Error: Cannot launch browser firefox-v30:
[init({"takesScreenshot":true,"record-screenshots":false,"record-video":false,"screen-resolution":"1024x768","max-duration":7200,"browserName":"firefox","version":30,"platform":"Linux"})] The environment you requested was unavailable.
```

independent of Gemini version (I tried with current 0.6.4 and new 0.8.2). WDIDW?

**Comment by SevInf** [comment]
Looks like something wrong with on SauceLabs part.

**Comment by aristov** [comment]
So how can we affect it?

**Comment by SevInf** [comment]
We can try some other chrome or firefox version, but I don't think it has a good chance of helping.
We can also try removing all browsers capabilites except `browserName` and `version` and see if it works that way.

If none of this will give any result we can only ask saucelabs on their support site/twitter, it looks like a problem on their side.

**Comment by arikon** [comment]
@aristov You can see the logs of sessions in your account on saucelabs.

**Comment by qfox** [comment]
Just fyi: I've got the same error when goes out of automated minutes. Probably it should be detected somehow.

**Comment by VladimirCW** [comment]
@SevInf 
I have the same issue, but i just try to run gemini at my computer (without SauceLab) and it gives me error
"Error: Cannot launch browser chrome:
[init({"takesScreenshot":true,"desiredCapabilities":{"browserName":"chrome"}})] The environment you requested was unavailable."
I've tried to delete some fields (like browserName, version and other) - nothing helps.

**Comment by SevInf** [comment]
@VladimirCW I don't work on gemini for almost 2 years already. I'm sure if you ask in [original project repo](https://github.com/gemini-testing/gemini) someone from the current team will be able to help you.
