### ISSUE TITLE
Rename bem-controls to bem-components

### ISSUE THREAD

**Issue by dfilatov** [bem/bem-components#106]

**Comment by dfilatov** [comment]
Variants:
- rename current bem-controls repo to bem-components to keep all issues and pull requests.
- create new bem-controls repo and push some state for backward compatibility

**Comment by tadatuta** [comment]
when we merged islands-controls with islands-popups and islands-dynamic, we made a copy of islands-controls as islands-components, merged all repos with all history and left source repos untached but added notice in readme.

i think it's the safest way.

**Comment by narqo** [comment]
I like @dfilatov's variant. We could make a dummy copy of current repo after renaming process, so all the issues will stay in components' repo.

So +1 from me :)

**Comment by vithar** [comment]
I agree with @dfilatov 
We can rename bem-controls to bem-components, create new repo bem-controls and push bem-controls@v1 to it in order to not affect current users of bem-controls@v1.
