### ISSUE TITLE
Add more browsers to Gemini

### ISSUE THREAD

**Issue by aristov** [bem/bem-components#1060]
// cc @tadatuta 
Which browsers we want to add?

**Comment by hcodes** [comment]
IE 9, 10...

**Comment by tadatuta** [comment]
- нужны тачи, в идеале ios и android

**Comment by tadatuta** [comment]
- we need to test touch blocks

**Comment by hcodes** [comment]
Тачи на Android и iOS тестировать пока не получится, нет поддержки в Gemini.
В IE9, 11 снятие  скриншотов отваливается по таймауту после десятка тестов.

**Comment by tadatuta** [comment]
cc @SevInf

**Comment by SevInf** [comment]
А можно кокретный текст ошибки посмотреть? Если это не трависовский таймаут (50 минут), то скорей всего его можно в настройках или `capabilities` потвикать.

**Comment by hcodes** [comment]
Таймаут. Какой параметр прописать в gemini.yml? В доках про focus saucelabs сходу не нашел...

**Comment by SevInf** [comment]
Мне нужен тест ошибки с которой gemini падает в консоли, чтобы понять какой именно это таймаут.

**Comment by hcodes** [comment]
```
✓ button default-link-enabled hovered [ie9]
 > CALL moveTo({"ELEMENT":"7"}) 
 > POST /session/:sessionID/moveto {"element":"7"}
 > RESPONSE moveTo({"ELEMENT":"7"}) 
 > CALL buttonDown() 
 > POST /session/:sessionID/buttondown {}
 > RESPONSE buttonDown() 
 > CALL eval("__gemini.prepareScreenshot([\".gemini-test-button-default-link-enabled\"], {\"coverage\":false})") 
 > POST /session/:sessionID/execute {"script":"return __gemini.prepareScreenshot([\".gemini-test-button-default-link-enabled\"], {\"coverage\":false});","args":[]}
 ! ETIMEDOUT: Lost http connection retrying in 15 ms.
 ! ETIMEDOUT: Lost http connection retrying in 15 ms.
 ! ETIMEDOUT: Lost http connection retrying in 15 ms.
```

**Comment by hcodes** [comment]
Пока можно добавить только IE9.
В IE10-11 снимаются некорректные скриншоты.
/cc @SevInf

**Comment by veged** [comment]
пока нет возможности добавить IE10-11 и Android, а IE9 с маленькой долей и не сильно нужен

ждём поддержки большего количества браузеров в Gemini
