### ISSUE TITLE
select[size=N, multiple]

### ISSUE THREAD

**Issue by aliosv** [bem/bem-components#1061]
http://jsfiddle.net/d93yqqen/
Планируется повторение данной функциональности нативного селекта в блоке?

**Comment by narqo** [comment]
В селекте — нет. 

Но, кажется, `menu_mode_check` + `menu#getVal() / menu#setVal()` позволяют достаточно просто решить конкретную задачу на уровне проекта

**Comment by qfox** [comment]
Имхо, по смыслу это checkbox-group с ограничением по высоте и со скроллом.

**Comment by veged** [comment]
`size=N` невозможен из-за того, что айтемы могут быть разной высоты — поэтому предполагается использование явного задания высоты + скролл

как и написал @narqo аналогичную `select[size=N, multiply]` функциональность можно получить с помощью https://ru.bem.info/libs/bem-components/v2.0.0/desktop/menu/docs/#Меню-с-множественным-выбором-модификатор-mode-в-значении-check
