### ISSUE TITLE
button: Spin inside button is positioned wrong

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-components#1065]
Please take a look at the guide for reference: icon should have left margin and gap between icon and text should be smaller

**Comment by hcodes** [comment]
Поговорил с @mishanga , кажется задача синтетическая.
Может быть убрать из примеров использование spin внутри button?

**Comment by tadatuta** [comment]
если никому такое использование не нужно, то да, давай убирать

**Comment by hcodes** [comment]
#1075
