### ISSUE TITLE
Demo page

### ISSUE THREAD

**Issue by dfilatov** [bem/bem-components#1066]
I think that we definitely need to have a demo page which contains some examples all of the blocks in a current state. Of course this page should be automatically updated on each commit to the main branch.
What's reason we don't have it yet? It seems that's a simple task via github gh-pages.

@veged @narqo @tadatuta @mishanga 

?

**Comment by tadatuta** [comment]
@sipayRT started working on such page for https://bem.info/ before his vacation. He will get back to it next week.
From bem.info side @tormozz48 is in progress with subscription on gh updates to rebuild documentation automatically.

**Comment by dfilatov** [comment]
@tadatuta Is there any progress?

**Comment by tadatuta** [comment]
@dfilatov yes, here's how it looks now: https://nda.ya.ru/3QTUes

**Comment by narqo** [comment]
@tadatuta nda links are unaccessible from the internet

**Comment by sipayRT** [comment]
here is - https://yadi.sk/i/hh5P30trctfxJ
