### ISSUE TITLE
Make usage of components as library bullet-proof

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-components#1087]
@andrewblond suggested to add special level which will change all possible tags to some custom and introduce local reset for each block where it's impossible to make blocks from `bem-components` used as prebuilt library really bullet-proof in enemy environments.

**Comment by dfilatov** [comment]
What about inputs, links?

**Comment by tadatuta** [comment]
@dfilatov, that's why we also need

> local reset for each block where it's impossible

**Comment by dfilatov** [comment]
@tadatuta Oh, I see. Anyway, the vast majority of our blocks can't be implemented via custom tags, so you can only use local reset. IMHO.

**Comment by veged** [comment]
let's delay this question until 1) we have seriously need in such "bullet-proof" and 2) death of IE8
