### ISSUE TITLE
Избавиться от пробела перед двоеточием в codestyle

### ISSUE THREAD

**Issue by aristov** [bem/bem-components#1101]
Все мучаются

**Comment by sipayRT** [comment]
+1

**Comment by narqo** [comment]
:-1: (я так привык и «мучаюсь», с «другими» код-стайлами)

**Comment by dfilatov** [comment]
:-1: Давайте что-нибудь полезное лучше делать

**Comment by ilyar** [comment]
:-1:  полезнее написать инструкцию|обзор о поддержке в редакторах/нструментов форматирования по код-стайлу

**Comment by aristov** [comment]
Продолжаем мучиться.

**Comment by aristov** [comment]
https://github.com/bem/bem-components/issues/1112
