### ISSUE TITLE
Написать инструкцию/обзор о поддержке в редакторах/инструментов форматирования по код-стайлу

### ISSUE THREAD

**Issue by aristov** [bem/bem-components#1112]
по мотивам https://github.com/bem/bem-components/issues/1101

**Comment by aristov** [comment]
cc @ilyar
Ты знаешь кого-то, кто в этом хорошо разбирается и мог бы помочь?

**Comment by ilyar** [comment]
@arikon к сожалению, нет

**Comment by narqo** [comment]
У меня есть codestyle-профиль для webstorm. А о чем таск?

**Comment by aristov** [comment]
@narqo можешь поделиться профилем?

**Comment by narqo** [comment]
@aristov https://yadi.sk/d/K27zhvWUcuuSH
