### ISSUE TITLE
Do not run gemini tests if diff is just in *.md

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-components#1136]

**Comment by qfox** [comment]
@tadatuta :heart:

**Comment by qfox** [comment]
`git diff $(git merge-base HEAD v2) | grep +++ | grep -v -e 'md$' > /dev/null && echo 'exec tests'` something like that in `.travis.yml`? Or in `package.json`?

**Comment by tadatuta** [comment]
yep. in `.travis.yml` I think is better

**Comment by qfox** [comment]
@tadatuta Didn't find a good place in .travis.yml. Any thoughts?

**Comment by qfox** [comment]
@tadatuta https://travis-ci.org/bem/bem-components/jobs/42204569 before_script is the best one. http://docs.travis-ci.com/user/build-configuration/

Also there is an option to add `[skip ci]` in any place of commit. http://docs.travis-ci.com/user/how-to-skip-a-build/

**Comment by qfox** [comment]
Need to check condition.

**Comment by hcodes** [comment]
The documentation contains inline examples.
Tests are not needed only for Gemini.

**Comment by qfox** [comment]
@hcodes Do you want to finish this? I saw a PR ;-)
