### ISSUE TITLE
Update bundles

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-components#1156]
Right now we have a few bundles in https://github.com/bem/bem-components/tree/v2/desktop.pages
Recently we've got some API changes and new features implemented. So we should update bundles according to these updates.

**Comment by hcodes** [comment]
What do you mean?

**Comment by qfox** [comment]
@tadatuta Please provide some clear description for this issue.

**Comment by tadatuta** [comment]
@hcodes @zxqfox updated description

**Comment by qfox** [comment]
@tadatuta Thanks. Can I ask about recent API changes? ;-)

**Comment by tadatuta** [comment]
@zxqfox can't suggest anything better then to check the final date bundles were updated and look through commits since that time :(

**Comment by qfox** [comment]
@tadatuta So we need to find out what was added to blocks since last bundles edit and fill them up.

Can I ask about logic of filling up these bundles?
Am I right if I say that showcase bundle should contain all possible blocks with islands theme?
What should exists in other bundles?

**Comment by hcodes** [comment]
PR #1204
