### ISSUE TITLE
menu: bottom padding is absent in case of specified height and scroll

### ISSUE THREAD

**Issue by dfilatov** [bem/bem-components#1158]
Height is not specified:
![normal](https://cloud.githubusercontent.com/assets/67957/5260919/4c2d85ee-7a25-11e4-953f-9af78e082783.jpg)

Height is specified:
![broken](https://cloud.githubusercontent.com/assets/67957/5260923/52dd5950-7a25-11e4-9ef0-aa313c901d50.jpg)

**Comment by mishanga** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=748518
