### ISSUE TITLE
Remove any usage of default theme from docs, examples

### ISSUE THREAD

**Issue by narqo** [bem/bem-components#1168]
We have a lot of crap about, so called, "default" theme in our codebase, for example in docs or tests. I propose to clean it out and declare "theme" as a required modifier for every control.

**Comment by aristov** [comment]
:+1: 

We can add a helper for common theme declaration. Something like this:

```
// page_theme.bemhtml

block('page').def()(function() {
    applyNext({ theme: this.mods.theme });
});

mix().match(function()
        return this.block !== 'page' && !this.elem && !this.mods.theme && !!this.theme;
    })(function() {
        return { mods: { theme: this.theme } };
    });
```

So we can simply use `_theme` modifier for `page` block, and any block inside it will inherit specified theme.
What do you think about it?

**Comment by qfox** [comment]
What about `bh`? `tParam('pageTheme')` in `bh.match('page', ...` and hardcode in every block?

It would be easy to make if `bh` would have some pattern matchers. Something like `bh.match('*', ...`.

**Comment by aristov** [comment]
I have no idea how to make the same with `bh`.

**Comment by narqo** [comment]
> [..] What do you think about it?

It won't work for us, sorry! 

1) You need to write proper deps to have all themes for all blocks in bundle to work.
2) You need to write proper deps to guaranty that this predicate would match. And, btw, there is no guaranty that block's `mix` won't rewrite "this general mix".
3) It won't work on the client-side. so it's absolutely unclear, why the same code should be used differently.
4) I have a strong feeling that such predicates dramatically harm template performance.

**Comment by mishanga** [comment]
@aristov это не по БЭМу и не по АНБ. Каждый блок может иметь собственную тему на странице.
@narqo можно выкинуть тему default из документации и примеров, но в тестах нужно оставить.

**Comment by dfilatov** [comment]
@mishanga Тему default мы уже убрали из документации

**Comment by aristov** [comment]
@narqo all right. This solution have a lot of problems, even more than you listed.

**Comment by deeonis** [comment]
we need it only for tests, from examples and docs was already removed
