### ISSUE TITLE
select: Wrong scroll position in Chrome

### ISSUE THREAD

**Issue by narqo** [bem/bem-components#1171]
![screen shot 2014-12-04 at 18 47 35](https://cloud.githubusercontent.com/assets/88045/5301024/3d8bd316-7be6-11e4-8ab2-d85baf2a4f51.png)

Video: https://yadi.sk/i/MTwURj9dd9pye

**Comment by tenorok** [comment]
![select-bug](https://cloud.githubusercontent.com/assets/1322855/5337981/fc81446c-7edf-11e4-945d-2f47b6cb79e3.png)

**Comment by hcodes** [comment]
Reproduced only on MacOSX 10.9.5 with retina.

**Comment by deeonis** [comment]
This bug is too minor and reproduce only in few browsers. Won't fix.
