### ISSUE TITLE
tabindex: make sure that all controls can have it

### ISSUE THREAD

**Issue by qfox** [bem/bem-components#1190]
Just for consistency

Components with tabIndex:
- [x] attach
- [x] button
- [ ] checkbox #1191
- [ ] checkbox_type_button #1191
- [ ] checkbox-group #1191
- [ ] dropdown__switcher #1191
- [x] input
- [x] link
- [ ] radio #1191
- [ ] radio_type_button #1191
- [ ] radio-group #1191
- [x] select__button
- [x] textarea

**Comment by qfox** [comment]
PR #1191

**Comment by aristov** [comment]
Assign an issue to yourself, if you make PR for it, please.

**Comment by veged** [comment]
we need the same in other controls

**Comment by qfox** [comment]
@veged I'm looking at code base, and radio/checkbox and their groups are the last controls without tabIndex. Can you clarify what you mean?

**Comment by aristov** [comment]
Close in favour of #1675.
