### ISSUE TITLE
Support IE8

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-components#1205]
main PR https://github.com/bem/bem-components/pull/1313
- [x] ~~attach~~ #1312
- [x] ~~button~~  #1274
- [x] ~~control-group~~ #1274 (button's styles)
- [x] ~~link~~
- [x] ~~radio~~ #1276
- [x] ~~radio-group~~
- [x] ~~z-index-group~~
- [x] ~~dropdown~~
- [x] ~~checkbox~~ #1300
- [x] ~~checkbox-group~~
- [x] ~~icon~~
- [x] ~~menu #1310~~ 
- [x] ~~menu-item #1310~~
- [x] ~~select #1314~~
- [x] ~~image~~
- [x] ~~modal #1273~~
- [x] ~~spin~~
- [x] ~~control~~
- [x] ~~input #1289~~
- [x] ~~popup #1273~~
- [x] ~~progressbar~~
- [x] ~~textarea #1298~~

**Comment by sipayRT** [comment]
#1263

**Comment by sipayRT** [comment]
#1264

**Comment by sipayRT** [comment]
#1265

**Comment by hcodes** [comment]
popup #1273

**Comment by sipayRT** [comment]
button - https://github.com/bem/bem-components/pull/1274
radio - https://github.com/bem/bem-components/pull/1276

**Comment by hcodes** [comment]
spin #1280

**Comment by hcodes** [comment]
input #1289

**Comment by hcodes** [comment]
textarea #1298

**Comment by hcodes** [comment]
Main PR #1313

**Comment by hcodes** [comment]
/cc @mishanga 
Need review.

**Comment by mishanga** [comment]
Во всех bemjson нужно заменить ie8.css на ie.css (и styl-файлы соответственно) и 'IE 8' на 'lt IE 9'.

**Comment by sipayRT** [comment]
Я думаю, что это можно будет сделать уже в ветке 1205, когда сольем все PR'ы в одну ветку. Там же тогда нужно будет и конфиг подправить

**Comment by sipayRT** [comment]
main PR https://github.com/bem/bem-components/pull/1313
