### ISSUE TITLE
checkbox: do we need passing id to checkbox?

### ISSUE THREAD

**Issue by qfox** [bem/bem-components#1209]
According to #1191 

> Are there any real cases where anyone needs ids in checkboxes?
> 
> Shouldn't we test somehow such enhancements with our testers? For example, how checkbox_type_button would work here? How label[id = 'id1'] + checkbox_type_button[id = 'id1'] would behave?

/cc @narqo @tadatuta @aristov 

https://github.com/bem/bem-components/commits/issues/1209%40v2

**Comment by deeonis** [comment]
cc @hcodes 

@hcodes will find out do we need it for a11y

**Comment by hcodes** [comment]
@deeonis 
JAWS читает текст у label при переходе по TAB на checkbox, расположенный внутри label.

**Comment by aristov** [comment]
@zxqfox are you satisfied with the answer? Anything else to discus here?

**Comment by qfox** [comment]
@aristov Yup, totally. Thanks.

Moreover, AFAIK if somebody need `id`s — he can make a template on his own level and pass there `id` attribute.
