### ISSUE TITLE
The right way to handle css` specificity on project`s level vs lib`s level

### ISSUE THREAD

**Issue by vitkarpov** [bem/bem-components#1227]
I have a question: how to override some css rules on project level considering that lib`s rules have more specificity?

I use `menu-item` and want to set another paddings than its default from `theme_islands`. If I just write css like that:

```
.menu-item
{
  padding: 2px 6px 4px 6px;
}
```

It doesn't work 'cause of 

```
.menu_size_m .menu-item_theme_islands
{
  ...
}
```

I can increase specificity of my rules on project`s level with different ways and I'm interested which of them do you recommend and why? Or it's not a problem at all and it doesn't matter

**Comment by tadatuta** [comment]
@vitkarpov there's quite a few solutions depending on what you really want to achieve:
1. If something looks in another way than `_theme_islands` suggests, why not to create your own theme?
2. If `_theme_islands` is good for most cases and doesn't fit for some particular use case you may consider to mix a new block and apply rules to it.
3. If you just want to override `menu-item_theme_islands` why don't you want to keep support for other `menu` sizes (and if so — keep cascade from `.menu_size_*`)?
4. If you don't want to bother at all and just want to increase specificity, you may use same selector few times (e.g. `.menu-item.menu-item { padding: 2px 6px 4px 6px; }`)

**Comment by vitkarpov** [comment]
@tadatuta Thanks for detailed answer, it's useful. I think a little bit more and chose the first option: I really don't need islands theme for menu-item.

By the way, am I correct in assuming that islands theme is open source and I can use it in my personal project, isn't it?

**Comment by tadatuta** [comment]
@vitkarpov sure, it's open sourced and you are free to use it any way you like

**Comment by vitkarpov** [comment]
Thanks!
