### ISSUE TITLE
Add the ability to expand textarea control attrs

### ISSUE THREAD

**Issue by tavriaforever** [bem/bem-components#1248]
In my case, I need to use `rows` html attr for block textarea. But now, a can`t expand attrs – https://github.com/bem/bem-components/blob/v2/common.blocks/textarea/__control/textarea__control.bemhtml#L6-L14

**Comment by tadatuta** [comment]
you can put needed code on your own level. E.g.:

``` js
block('textarea').elem('control').attrs()(function() {
    var attrs = applyNext();
    attrs.rows = this._textarea.rows;
    return attrs;
});
```
