### ISSUE TITLE
Configure precommit hook for tests

### ISSUE THREAD

**Issue by veged** [bem/bem-components#125]
If we try to commit some BEM-item with tests, we should run it in precommit hook.

**Comment by mishanga** [comment]
Is it still actual?

**Comment by tadatuta** [comment]
I think it is.

**Comment by qfox** [comment]
@veged Should it run tests in dependants? Should it run block tests if element/modifier changed?

It will be much harder if it is and will require some special `js` tools.

**Comment by qfox** [comment]
ping

**Comment by deeonis** [comment]
closed in favour Travis CI
