### ISSUE TITLE
checkbox, radio: blur and focus

### ISSUE THREAD

**Issue by qfox** [bem/bem-components#1261]
Clicking on focused checkbox or radiobutton generates 2 events: blur + focus.

`bemjson.js`:

``` js
{ block : 'checkbox' }
```

`browser.js`:

``` js
modules.define('checkbox',
    ['i-bem__dom'],
    function(provide, BEMDOM, prev) {

provide(prev.decl(this.name, {
  onSetMod : {
    focused : function () {
      console.log(arguments);
    }
  }
}));
```

Expected nothing if control already focused.

Is this a bug? Feels like.

**Comment by deeonis** [comment]
cc @veged @narqo

**Comment by dfilatov** [comment]
It's not a bug. It completely corresponds to the browser behaviour.
