### ISSUE TITLE
checkbox: Send off to server

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-components#1262]
I propose to improve native `checkbox` behaviour and always send values to a server even if a checkbox is off (maybe as a separate modifier).

Can be implemented with the help of hidden input like this:

``` js
block('checkbox').content()(function() {
    var isChecked = this.mods.checked;

    return [
        {
            elem: 'hidden',
            tag: 'input',
            attrs: {
                type: 'hidden',
                name: this.ctx.name,
                disabled: isChecked ? 'disabled' : undefined,
                value: isChecked ? '' : 'off'
            }
        },
        applyNext()
    ];
});
```

and

``` js
modules.define('checkbox', function(provide, Checkbox) {
    provide(Checkbox.decl({
        _onChange: function() {
            this.__base.apply(this, arguments);

            this.elem('hidden').prop(this.elem('control').prop('checked') ?
                { disabled: 'disabled' } : { value: 'off', disabled: false });
        }
    }));
});
```

**Comment by narqo** [comment]
it would be very strange, to send any predefined constant values to the user's backed. Potentially it can break backend logic, as it's not very intuitive.

Any way, I think such things should be on the user-space side. Not in the library side. So :-1: for that, sorry

**Comment by narqo** [comment]
Oops, wrong button

**Comment by tadatuta** [comment]
@narqo we can go with modifier not to break anything

**Comment by dfilatov** [comment]
@tadatuta what's it for?

**Comment by tadatuta** [comment]
@dfilatov when you submit a form with switched off checkbox there's no way on schemaless backend to understand if you want to leave it's value unchanged or want to remove it as nothing is sent at all. also you can't differentiate unknown state from intentionally switched off.

**Comment by dfilatov** [comment]
If you need to differentiate state "no checked" from "unchecked by user" you should do it outside of this component.
