### ISSUE TITLE
Button in IE8

### ISSUE THREAD

**Issue by sipayRT** [bem/bem-components#1263]
In IE8 we have some native behavior in pressed state:
![button-pressed](https://cloud.githubusercontent.com/assets/1658415/5799142/e9ed16a2-9fdf-11e4-9144-ff8f42fcb012.png)

We can fix it by resetting `background` and adding `border` and changing `line-height` css-property. Should we do it?

**Comment by sipayRT** [comment]
@mishanga

**Comment by sipayRT** [comment]
We need more bugs! In ie we can't use `textMaxWidth` because button will collapse to the width of the text as if it was not set to be clipped:
![max-width](https://cloud.githubusercontent.com/assets/1658415/5820496/468fea1e-a0d6-11e4-83be-877466c8e57d.png)
I offer to disable this option in ie8 by `max-width: none !important;` for `__text`

**Comment by dfilatov** [comment]
To my mind we could get rid of this option at all. It was made up when we had no _width_available modifier.

**Comment by sipayRT** [comment]
But we don't have such modifier for button. And `_width_available` and `textMaxWidth` are not the same.  `_width_available` modifier add the ability to fit all available width, but `textMaxWidth` defines maximum width of button (but button can be narrowed)

**Comment by dfilatov** [comment]
Yes, they aren't the same. But `textMaxWidth` was introduced to make work `select` and afterwards we found better solution with `maxWidth` in css and `_width_available` modifier.

**Comment by qfox** [comment]
+1 to drop that.

**Comment by tadatuta** [comment]
+1 to @dfilatov

**Comment by sipayRT** [comment]
https://github.com/bem/bem-components/pull/1269
