### ISSUE TITLE
Radio in IE8

### ISSUE THREAD

**Issue by sipayRT** [bem/bem-components#1264]
Native radios in IE8 are more similar to our design:
native:
![radio-native](https://cloud.githubusercontent.com/assets/1658415/5799232/0c69b022-9fe1-11e4-85af-d71d5872fcd1.png)
islands in ie8:
![radio-custom](https://cloud.githubusercontent.com/assets/1658415/5799236/1c0caae8-9fe1-11e4-84be-3de72372e788.png)
islands in webkit:
![radio-webkit](https://cloud.githubusercontent.com/assets/1658415/5799264/70d994c8-9fe1-11e4-9a21-2abc198d709d.png)

What type of radios should we use?

**Comment by sipayRT** [comment]
@mishanga

**Comment by sipayRT** [comment]
ping! somebody saw this issue?

**Comment by tadatuta** [comment]
my vote is for native implementation

**Comment by blond** [comment]
+1 for native

**Comment by mishanga** [comment]
Нативные — это круто, конечно, но для фолбека придется городить костыли в коде для основных браузеров. А мы договаривались, что фолбек будем делать в отдельных ie8.css файлах.

**Comment by sipayRT** [comment]
А почему мы не можем просто в ie8.css отменить все стили? Что-то типа

```
.radio_theme_islands
{
    .radio__box
    {
        background: 0;

        &:before,
        &:after
        {
            content: none !important;
        }
    }
}
```

должно убить все стили, оставив нативные контролы (но не для `_type_button`)

**Comment by mishanga** [comment]
А в других блоках как быть? Надо придумать консистентное решение.

**Comment by sipayRT** [comment]
Да, что делать с другими блоками пока не понятно. Тогда можно сейчас оставить кастомную реализацию, а когда будут готовы все блоки под ИЕ - открыть в ИЕ общую страницу с контролами и уже толпой подумать как сделать лучше. Тогда пока оставляю нашу реализацию - оторвать всегда успеем

**Comment by qfox** [comment]
Squares is so cute.
