### ISSUE TITLE
es5-shim for IE8

### ISSUE THREAD

**Issue by sipayRT** [bem/bem-components#1265]
What type of adding this library you prefer?
1. CDN with conditional comments on desktop(or test)-level?
2. bower.json + deps?
Or you can offer your own version

my vote for first option

**Comment by narqo** [comment]
> 1. CDN with conditional comments on desktop(or test)-level?
> 2. bower.json + deps?

I don't think that you want to write all this deps for `ecma` elements for each test-bundle. So CDN should be the case

**Comment by sipayRT** [comment]
tnx!
