### ISSUE TITLE
select: Strange examples in block documentation

### ISSUE THREAD

**Issue by narqo** [bem/bem-components#1270]
1) [The example for `optionsMaxHeight`](http://ru.bem.info/libs/bem-components/v2/desktop/select/docs/#Поле-`optionsMaxHeight`) from field's description is really show nothing about what this field is about.

I think we can something like [this one](http://ru.bem.info/__example/bem-components/v2/desktop.examples/select/yWP0yGereV7Fl4LXt6oGfSJuueM/yWP0yGereV7Fl4LXt6oGfSJuueM.html) to illustrate what is this field is for.

2) [The example for `textMaxWidth`](http://ru.bem.info/libs/bem-components/v2/desktop/select/docs/#textmaxwidth), doesn't illustrate anything as well ;)

3) It's really hard to understand, why do we need `_width_available` modifier from [this example](http://ru.bem.info/libs/bem-components/v2/desktop/select/docs/#Модификатор-`width`)

**Comment by innabelaya** [comment]
Done, except the last one https://github.com/bem/bem-components/pull/1295
