### ISSUE TITLE
button: Add documentation about _width_available

### ISSUE THREAD

**Issue by narqo** [bem/bem-components#1271]
It seems, that [current documentation](https://github.com/bem/bem-components/blob/2fcd618f54f58c5e06510eb11bda82859673c20f/common.blocks/button/button.ru.md#%D0%9C%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80%D1%8B-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B0) of the `button`, lacks `_width_available` description.

**Comment by sipayRT** [comment]
but we haven't such modifier in button.

**Comment by narqo** [comment]
My bad, sorry. I've mixed up it with `input`.
