### ISSUE TITLE
Add examples of popup, modal and z-index

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-components#1294]
- [x] modal
- [ ] popup
- [ ] z-index

**Comment by weynemeynen** [comment]
Привет Вова!

Научи пожалуйста (по bem) открывать (по загрузке страницы) и закрывать и модальное окно.
autoclosable не работает :(
видеть можно здесь:
https://8a1ff09ee07f1e2ffa60543a9b82ee60fe9245bd.googledrive.com/host/0BwpgJqxcuprwZEhIRkNXSUZwOE0/index.html

github:
https://github.com/weynemeynen/tests/tree/informika

и ещё:
как вставить пробелы между кнопками в radio-group???
https://ru.bem.info/__example/bem-components/v2.4.0/desktop.examples/radio-group/2OwBAUL8orcMJzEsW8Za1oyJ6kc/2OwBAUL8orcMJzEsW8Za1oyJ6kc.html

Спасибо, с уважением, ДШ

**Comment by tadatuta** [comment]
> как вставить пробелы между кнопками в radio-group?

`radio-group` задуман исключительно для того, чтобы поставить радио-кнопки вплотную. Если между ними нужны отступы, то воспользуйся просто несколькими отдельными [radio](https://ru.bem.info/libs/bem-components/v2.4.0/touch/radio/).

**Comment by tadatuta** [comment]
В репозитории https://github.com/weynemeynen/tests/tree/informika не увидел использования блока `modal`, так что подсказать на счет `autoclosable` без примера не смогу — у меня с ним проблем нет, да и тесты блок проходит.

А на счет показа `modal` на загрузку, можно в `page.js` в обработчике на `js inited` вызвать `this.findBlockInside('modal').setMod('visible');`. Если модальных окон больше одного, то смиксовать их с каким-то конкретным элементом `page` и делать что-то типа:

``` js
this.findBlockOn('special-hello-modal', 'modal').setMod('visible');
```

**Comment by weynemeynen** [comment]
Ура! Получилось!
большое СПАСИБО!
