### ISSUE TITLE
Don't overrides menu and menu-item blocks

### ISSUE THREAD

**Issue by awinogradov** [bem/bem-components#1315]
Если попытаться прокинуть свои параметры в этих блоках ничего не выйдет. Тянуться только из библиотеки.

**Comment by tadatuta** [comment]
@verybigman ты про https://github.com/bem/bem-components/issues/1248 ?

**Comment by awinogradov** [comment]
Похоже только там в def прокидывается тема и дизайблед в _menuMods через applyNext(). А мне надо еще туда свои. Я про https://github.com/bem/bem-components/blob/v2/common.blocks/menu-item/menu-item.bemhtml#L6-L11

**Comment by tadatuta** [comment]
@verybigman 
Напиши, пожалуйста, какие именно поля тебе необходимо пробрасывать.

На данный момент мейнтейнеры bem-core/bem-components сформулировали такой принцип добавления новых параметров: если что-то нужно критическому количеству пользователей — параметр попадает в библиотеку, а до тех пор каждый добавляет свои кастомные штуки на своем уровне переопределения.

Возможность пробрасывать произвольные параметры запрещена сознательно — такое гибкое API невозможно покрыть тестами и гарантировать его работоспособность в любых комбинациях.

**Comment by awinogradov** [comment]
Мне на моем и надо добавить. Но шаблон с моего уровня не добавляет
параметров по каким-то причинам. Я в def добавляю свои модификаторы, но
чето никак. Позже кину код.
Пт, 30 янв. 2015 г. в 18:44, Vladimir Grinenko notifications@github.com:

**Comment by awinogradov** [comment]
Сделал пример блоков тут https://github.com/verybigman/test-case/tree/master/common.blocks
Совершенно точно, что-то я делаю не так:)

**Comment by Guria** [comment]
https://github.com/verybigman/test-case/blob/master/common.blocks/menu/menu.bemhtml#L5
Опечатка

**Comment by awinogradov** [comment]
Это ничего не меняет. Пофиксил. Это последствия переноса:)

**Comment by tadatuta** [comment]
@verybigman потому что [вот здесь](https://github.com/bem/bem-components/blob/v2/common.blocks/menu/menu.bemhtml#L37-L42) твои данные в `_menuMods` перетираются. и подчеркивание в имени поля как раз и придумано, чтобы намекнуть «не используй меня, я приватная штука».
чтобы у тебя все стало хорошо, просто придумай свое собственное поле для проброса модификаторов

**Comment by awinogradov** [comment]
@tadatuta спасибо!
