### ISSUE TITLE
Add bemhtml-template to popup examples 

### ISSUE THREAD

**Issue by gela-d** [bem/bem-components#1316]
Here https://github.com/bem/bem-components/tree/v2/common.blocks/popup/popup.examples/20-popup.blocks/directions we need bemhtml-template too

**Comment by tadatuta** [comment]
@gela-d @andrewblond @tormozz48 guys, let's switch to BH-only — it'll make build process faster. but if it's not easy to implement I agree to add BEMHTML templates as hotfix

**Comment by gela-d** [comment]
@tadatuta Sure, but for our buildings - it's a feature. And now I want to fix building of this example
