### ISSUE TITLE
textarea: default use width_available modifier

### ISSUE THREAD

**Issue by voischev** [bem/bem-components#1318]
Очень хочется использовать этот модификатор без темы `islands`. 
*Кстати в документации не написано что он только для темы `islands` ;) или я  ослеп *

Сейчас в теме вот такой код

``` css
&.textarea_width_available
{
      width: 100%;
}
```

Cтранно. В теме блок сделан inline-block, а контрол с width: 100%;. По этому нам достаточно сказать блоку width: 100%;

А в дефолтной реализации блок получается `DIV` тоесть тянется на всю длинну. а контролл inline-block

Проблемы
1. Не возможность использовать этот модификатор по дефолту без темы. Хотя кажется может стать очень полезным. 
2. `textarea` прилетает с тегом `div` надо бы `span` 

Версия библиотеки `2.0.0`

**Comment by innabelaya** [comment]
@voischev не ослеп ;) Использование темы обязательное, а так как сейчас тема у нас одна, то, считай, все модификаторы «только для темы `islands`». Как появится еще одна тема, будут добавляться заметки на полях – что и для какой темы.

**Comment by voischev** [comment]
@innabelaya :) ясно. Но давайте рассмотрим возможность использования этого модификатора вне любой темы, кажется может быть удобно.

**Comment by deeonis** [comment]
@tadatuta ты обещал завести общий issue на все контролы, у которых есть такие же модификаторы. Заведешь?

**Comment by sipayRT** [comment]
https://github.com/bem/bem-components/issues/1404

**Comment by sipayRT** [comment]
fixed in https://github.com/bem/bem-components/pull/1405
