### ISSUE TITLE
Inaccurate usage of Array.prototype.splice throw the library internals

### ISSUE THREAD

**Issue by narqo** [bem/bem-components#1319]
We have cases where `Array.prototype.splice` usage is not 100% accurate. E.g. `visiblePopupsStack.splice(visiblePopupsStack.indexOf(this), 1);`

In the example above, the last element of `visiblePopupsStack` would be dropped, if `this` instance isn't in the collection.

``` js
arr = [1,2,3];
arr.splice(-1, 1);

arr === [1,2];
```

**Comment by dfilatov** [comment]
But there's no case when `visiblePopupsStack.indexOf(this) === -1`

**Comment by qfox** [comment]
@narqo Can we make a comment for that line for future questions?

**Comment by narqo** [comment]
Yes, we can ;)
