### ISSUE TITLE
menu-item: size modifier examples at bem.info

### ISSUE THREAD

**Issue by qfox** [bem/bem-components#1321]
If there is no difference what I paying for?

https://bem.info/libs/bem-components/v2.0.0/desktop/menu-item/docs/#size-modifier-8

![image](https://cloud.githubusercontent.com/assets/677518/5986998/c2057eaa-a925-11e4-8ef1-ff57f461d642.png)

**Comment by tadatuta** [comment]
cc @innabelaya

**Comment by qfox** [comment]
It looks like there are no styles for `.menu-item_size_l`. Probably `deps` or something.

**Comment by tadatuta** [comment]
nope, there's just no such modifier for `menu-item` at all

**Comment by innabelaya** [comment]
description was removed in https://github.com/bem/bem-components/commit/f7866d9bacbbb577316a8cd72f15ead364bfd62d

**Comment by deeonis** [comment]
done
