### ISSUE TITLE
dist: desktop.browser+bemhtml.js has no BEMHTML templates

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-components#1322]

**Comment by blond** [comment]
Now dependencies of blocks not have tech section for `js`. Need add BEMHTML dependencies for js techs.

Example for `button.deps.js`:

``` js
{
    tech : 'js',
    mustDeps : { tech : 'bemhtml', block : 'button' }
},
```

**Comment by qfox** [comment]
Don't forget to update docs plox.
