### ISSUE TITLE
input + progressbar.pause: trouble on showcase

### ISSUE THREAD

**Issue by qfox** [bem/bem-components#1328]
http://bem.github.io/reports/3883/showcase/showcase.html

How to repeat:
- Pressing pause twice (starting and stopping progress)
- Removing text manually (cross still here? ouch)
- Pressing input_clear (cross) in input
- Type something in input (no cross? you are looser bro ;-) _visible mod is absent)
- And after some time (or clicks between tabs) it starts working again

Expected:
That cross should be shown on filled input, and disappears on empty even if we stopped progress bar.

fyi:
Trouble begins only on the second click on pause — on stopping progress bar.

**Comment by hcodes** [comment]
Fixes #1332

**Comment by qfox** [comment]
@hcodes Thanks!
