### ISSUE TITLE
Put/update links to showcase and reports in PR on each build

### ISSUE THREAD

**Issue by qfox** [bem/bem-components#1331]
Based on https://github.com/bem/bem-components/pull/1329

Instead of adding new comments for each action we should:
- Read current PR from GH API;
- Check for special html comment with links in it;
- Carefully clean up it (left links with current build number only);
- And update PR finally.

Feels like it's easier to make with node.js or python.

If I'm not wrong: also would be great to move all travis publishing scripts to some `.travis-scripts` (or `.travis`) folder.

**Comment by qfox** [comment]
@deeonis thanks.

**Comment by tadatuta** [comment]
Implemented
