### ISSUE TITLE
textarea: Style does not resizing 

### ISSUE THREAD

**Issue by gela-d** [bem/bem-components#1334]
If we have `textarea_width_avaliable` and try to drag corner of textarea control, our text would be moving, but control border will be still stay 
![1](https://cloud.githubusercontent.com/assets/1333220/6042887/64e5368a-ac99-11e4-9977-779e1b048f81.png)

**Comment by sipayRT** [comment]
https://github.com/bem/bem-components/issues/1330

**Comment by hcodes** [comment]
Duplicate
