### ISSUE TITLE
Replace this.isArray -> Array.isArray in bemhtml

### ISSUE THREAD

**Issue by hcodes** [bem/bem-components#1339]

**Comment by dfilatov** [comment]
for what?

**Comment by hcodes** [comment]
https://github.com/bem/bem-components/search?utf8=%E2%9C%93&q=Array.isArray

**Comment by hcodes** [comment]
В bemhtml this.isArray есть.
В bh ctx.isArray нет.

**Comment by dfilatov** [comment]
Я не понимаю зачем вообще использовать что-то кроме `Array.isArray`

**Comment by hcodes** [comment]
В bh Array.isArray, в bemhtml this.isArray.
То же не понимаю почему нужно писать this.isArray в bemhtml?

**Comment by qfox** [comment]
Как минимум, IE8, поддержка которого еще есть, не умеет Array.isArray

**Comment by dfilatov** [comment]
для IE8 нужно использовать соответствующий полифил

**Comment by qfox** [comment]
@dfilatov Пошто вы меня заставляете это делать? ;)

**Comment by dfilatov** [comment]
любители и те, кто поддерживают IE8 должны страдать по определению )

**Comment by hcodes** [comment]
А те кому нужна поддержка IE8 подключают es5-shim.

**Comment by qfox** [comment]
Жестоко ;-). Еще есть кейс, который усложняет использование шаблонов as is на других платформах. Например, все шаблоны bh из bem-core/components можно было бы автоматически конвертировать в bh-php, если бы был хелпер isArray и еще кой-что.

**Comment by qfox** [comment]
@hcodes Тут вопрос не в том, что должны. А в том, что заявляется библиотекой. Если в библиотеке написано, что IE8 — ок, то получается, что надо либо shim включать, либо делать так, чтобы без него работало. Не прав?

**Comment by dfilatov** [comment]
В библиотеке должно написано что IE8 поддерживается при наличии соответствующих полифилов.

**Comment by qfox** [comment]
@dfilatov Ну сейчас там IE10+ ;-) Но, видимо, будет написано. ок.

**Comment by hcodes** [comment]
@dfilatov Меняем `this.isArray` на `Array.isArray` в bemhtml  шаблонах?

**Comment by qfox** [comment]
@hcodes Тогда и хелпер не нужен, его надо выпиливать из док (https://ru.bem.info/technology/bemhtml/v2/templating/#Контекстно-независимые-поля), и депрекейтить до следующего мажорного релиза.

Думаю, это надо обсуждать.

**Comment by voischev** [comment]
> любители и те, кто поддерживают IE8 должны страдать по определению ) 

:+1:

**Comment by dfilatov** [comment]
@hcodes Мое мнение — да, заменить

**Comment by hcodes** [comment]
Fixed #1347

**Comment by Guria** [comment]
sorry wrong reference
