### ISSUE TITLE
input: doesn't support list attribute

### ISSUE THREAD

**Issue by Guria** [bem/bem-components#1346]
list attribute for input element doesn't supported.
http://www.w3schools.com/tags/tag_datalist.asp

**Comment by qfox** [comment]
You can make it possible on your level.

**Comment by tadatuta** [comment]
we need some way to collect such requests
// cc @veged @hcodes

**Comment by qfox** [comment]
@tadatuta Make a Label for that ;-)

**Comment by tadatuta** [comment]
@Guria We agreed not to implement support for attributes without full browser support and/or wide usage. Otherwise we can't guarantee compatibility.
So you are to add it on your own level with the help of templates. E.g.:

``` js
block('input')(
    elem('control').attrs()(function() {
        var attrs = applyNext() || {};
        attrs.list = this.ctx.list;
        return attrs;
    })
);
```
