### ISSUE TITLE
`icon` block has redundant deps from `i-bem`

### ISSUE THREAD

**Issue by Guria** [bem/bem-components#1351]
`icon` block has deps from `i-bem` but has not any js technology.
https://github.com/bem/bem-components/blob/v2/common.blocks/icon/icon.deps.js#L2

``` js
({
    mustDeps : 'i-bem'
})
```

Is it really neccessary or just mistake?

**Comment by tadatuta** [comment]
@Guria `icon` has BEMHTML templates so it requires `i-bem.bemhtml` to work properly.

**Comment by qfox** [comment]
@tadatuta So I don't need i-bem if I using bh.js ?

**Comment by Guria** [comment]
I had same question.

**Comment by tadatuta** [comment]
@Guria @zxqfox yes, you don't. one day we'll fix it with the help of depsByTech but actually there's no much sense for it as anyways there are always other blocks using `i-bem`.

**Comment by qfox** [comment]
Got it, thanks ;-)
