### ISSUE TITLE
icon: Move out styles to design level under some mod

### ISSUE THREAD

**Issue by Guria** [bem/bem-components#1352]
Default styles in `icon` block assumes positioning on baseline case only. It uses some sort of hack and magic number and moreover require setting proper line-height value (not described in documentation) in case of using `img` or `svg` tag inside.
This styles affects unpredictable when trying to achieve another way to position icon element, eg using flexbox (which will override `display: inline-block` property). I had to redefine this properties on one of my project's level. Would be usefull if current styles will be moved out to mod declaration which will enable possibility to use technic from library optionally.

**Comment by tadatuta** [comment]
cc @mishanga

**Comment by mishanga** [comment]
Блок icon специально адаптирован для использования внутри других блоков и выравнивания по baseline. Если нужна какая-то другая функциональность, проще создать новый блок `my-icon` и использовать его.
UPD: добавлю, что это выравнивание не зависит от дизайна, поэтому и лежит в common.blocks, а не в папке design.

**Comment by Guria** [comment]
Ok, I get a point. Could styles used for icon block be more specific? Currently there are high probability of interreference of common `.icon` selector with project or third-party libraries styles.
For example, we could mix element on block itself and use it for styling purposes.
