### ISSUE TITLE
menu-item: check icon displays under `menu-item` mod checked true without parent `menu` block

### ISSUE THREAD

**Issue by Guria** [bem/bem-components#1354]
`menu-item` block supposed to be used inside `menu` block, but snippets in documentation provided without parent `menu` block.  Therefore, snippet used to demonstrate `menu-item_checked` in documentation looks broken:
![screenshot](https://api.monosnap.com/rpc/file/download?id=Y0rpspYDB43C8gyiDkRemokMq2SwwP)

**Comment by tadatuta** [comment]
cc @innabelaya

**Comment by innabelaya** [comment]
Should I remove the description of the "checked", "theme" and "size" modifiers for the `menu-item` block? It inherits all these modifier values from the `menu` block.

**Comment by tadatuta** [comment]
@innabelaya yes, looks like so
