### ISSUE TITLE
Button "text-overflow: ellipsis" doesn't work

### ISSUE THREAD

**Issue by idmytro** [bem/bem-components#1374]
bem-components/design/common.blocks/button/_theme/button_theme_islands.styl
https://github.com/bem/bem-components/blob/c7150a5c2e56d965d091bbf557f6eb5e4118b70b/design/common.blocks/button/_theme/button_theme_islands.styl
This code looks like a legacy code.

**Comment by dfilatov** [comment]
It works as expected in case of usage `button` as an element of `select`.

**Comment by idmytro** [comment]
nice bem, select styles are written in button block

**Comment by dfilatov** [comment]
It's not a `select` style. It's a style for `button` which enables you properly use it in `select`.

**Comment by idmytro** [comment]
So close issue, if everything is ok here
