### ISSUE TITLE
popup: reattach to body occurs after popup already visible

### ISSUE THREAD

**Issue by Guria** [bem/bem-components#1377]
https://github.com/bem/bem-components/blob/v2/common.blocks/popup/popup.js#L41
I have an issue with custom styles for popup animation. First time `popup` appears immediately without animation. It caused by reattach to `document.body`.
It could be solved by moving out handlers for mod `visible` from `onSetMod` to `beforeSetMod`.
Another way is perform reattach in `_js_inited` handler.
Both solutions works fine for me.
Also take a note that it is not save to assume that `BEMDOM.scope` will contain `document.body` because it could be redefined. See [this forum post](https://github.com/bem/bem-forum-content-ru/issues/237) for reference.

**Comment by tadatuta** [comment]
// cc @Coltspb

**Comment by dfilatov** [comment]
Note: you mustn't use `beforeSetMod` for anything excepting checks to prevent mod set.

**Comment by Guria** [comment]
I got it, thanks.

**Comment by dfilatov** [comment]
@Guria Why do you have problems with custom styles? What's the significant difference between your style and style in `_theme_islands`?

**Comment by Guria** [comment]
My styles used animation of height property. It works fine all times except the first time when reattach occurs. When I checked in debugger step by step: first popup appeared on page because visible mod was set, then popup moved to target block already fully opened when dom node was reattached.
I am sure there is no differences which styles is used. Reattach should be done before popup will be visible anyway.

**Comment by dfilatov** [comment]
@Guria Could we see the code of your animation?

**Comment by Guria** [comment]
``` js
({
  block: 'page',
  head: [
    { elem: 'css', url: '_popup.css' },
    { elem: 'js', url: '_popup.js' }
  ],
  content: [
    {
      block: 'test',
      js: true,
      content: [
        { block: 'input' },
        { 
          block: 'popup',
          mods: { target: 'anchor', autoclosable: true },
          directions: ['bottom-left']
        }
      ]
    }
  ]
})
```

``` js

modules.define('test', ['i-bem__dom'], function(provide, BEMDOM) {

provide(BEMDOM.decl(this.name, {
  onSetMod : {
    js : {
      inited : function(){
        var field = this.findBlockInside('input'),
            popup = this.findBlockInside('popup');

        popup.setAnchor(field);
        field.on('change', function(){
          popup.setMod('visible', true);
        });
      }
    }
  }
}));
});
```

``` styl
.popup
  height 0
  width 300px
  background wheat
  transition all 0.5s ease-out
  &_visible
    height 100px
```

**Comment by narqo** [comment]
@Guria we have realised the problem, but currently we don't have right solution for it. We can't make such things in the `onSetMod–js–inited` handler, because it will cause a lot of unnecessary DOM manipulations (e.g. popups which will never be opened).

May be you can use CSS-animation instead transition?

**Comment by Guria** [comment]
@narqo Problem could be solved on my level. I can init block manually or use another way to animate `popup`, for example. But I still sure that reattach should be done before `popup` will be visible.
How about: in `beforeSetMod` `visible` `true` handler discard setting mod if reattach wasn't made and call some private method which will perform reattach and set back `visible` mod. Is it acceptable solution?

Also what about `BEMDOM.scope` redefinition?

**Comment by narqo** [comment]
> How about: in beforeSetMod visible true handler discard setting mod if reattach wasn't made and call some private method which will perform reattach and set back visible mod

The solution looks more or less ok. Summoning @dfilatov as he is more relevant about the questions of the API.

> Also what about BEMDOM.scope redefinition?

It seems that we need to add more details to the docs about the cases when someone can (or can't) redefine `BEMDOM.scope`.

**Comment by narqo** [comment]
After a small conversation \w @dfilatov it turned out that it's impossible to discard mod set in `beforeSet` handler and set it back within single event loop.

``` js
beforeSetMod : {
  'visible' : {
    'true' : function() {
      if(!this._isAttachedToScope) {
        this._attachToScope();
        this.setMod('visible');    // ☚ this is impossible, as you're in the setMod processing already
        return false;
      }
    }
}
```

> Also what about BEMDOM.scope redefinition?

As about `BEMDOM.scope` problem, we're going to write a more detailed explanation about it use cases in `i-bem__dom` documentation (#914). In short: `BEMDOM.scope` isn't supposed to be set with something that is outside the `body`.

**Comment by Guria** [comment]
`nextTick` also will not make a deal in our case, I suppose?

Could you also add a note about `BEMDOM.scope` usage in [forum post](https://github.com/bem/bem-forum-content-ru/issues/237) I've referenced?

**Comment by narqo** [comment]
> nextTick also will not make a deal in our case, I suppose?

Unfortunately `nextTick` will bring much more troubles here.

**Comment by Guria** [comment]
> We can't make such things in the onSetMod–js–inited handler, because it will cause a lot of unnecessary DOM manipulations (e.g. popups which will never be opened).

I have a thought recently. `Popup` always should be called from another blocks and it is [their responsibility to init it](https://github.com/bem/bem-components/blob/v2/common.blocks/dropdown/dropdown.js#L55). Let just set `{ live: true }` to popup and move popup reattach to _js_inited handler.

**Comment by Guria** [comment]
Oh my. It is already has `{ live: true }`. Popup initialised only by blocks that used it. So suggestion about `lot of unnecessary DOM manipulations (e.g. popups which will never be opened)` is not true at all.

**Comment by narqo** [comment]
> So suggestion about lot of unnecessary DOM manipulations (e.g. popups which will never be opened) is not true at all.

But it is, actually. 

`select` (or `dropdown`) will be initialised if focus on `select__button` occurs as well as with other cases. This will lead to `popup` initialisation through the `find`-method inside `select`. In our practice, such select can be never opened at all.

**Comment by Guria** [comment]
Dropdown initializes popup only when it need to display it not on his init event.
I don't see a reason not to use the same technic in any block that uses popup.

**Comment by narqo** [comment]
> I don't see a reason not to use the same technic in any block that uses popup.

It'd been done in such way in `select` from the beginning. But it turned out, that it brings additional complexity to the block's internals. For example, `_menu` handling would be "tricky" (I don't support hop-searching for blocks, e.g. `select.findBlockInside('menu')`), as you still can do `Select#setVal()` from the outside.

From this point of view, to avoid CSS `transitions` looks like a much easier solution.

**Comment by narqo** [comment]
After a long chat /w others, we've decided to close this issue, as no one have any idea of how to fix transitions in `popup`. Sorry
