### ISSUE TITLE
.input_has_clear.input_type_search: inadequate `text-overflow: ellipsis` behaviour in chrome

### ISSUE THREAD

**Issue by Guria** [bem/bem-components#1382]
``` js
{ 
  block : 'input',
  mods : { theme : 'islands', size : 'l', 'has-clear' : true, type : 'search' },
}
```

Start input long text in input. It will get ellipsised once getting to edge of control.
![demo](http://i.imgur.com/wBs50LW.gif)

**Comment by Guria** [comment]
I don't see a point why we have `input_type_search`. It doesn't have nor js, nor css technologies. It only sets html attribute `type="search"`. Some browsers adding native button to clear input, but it supressed in styles of `input` block. Moreover `input` block provides own realization for it. According to ~~#1339~~ #1379  such things can be implemented on project sides.

**Comment by sipayRT** [comment]
it looks like bug in Chrome, because it works fine without `outline: none;` property.

**Comment by sipayRT** [comment]
proof - http://dabblet.com/gist/19ecd11905343f47f50e
you can remove `outline: none;` to fix this bug

**Comment by Guria** [comment]
I've guessed that it is only Chrome bug, but wasn't able to reproduce it on native input. Thanks for clarification. But questions in 2nd comment still actual. Why we have `type="search"` if library provides own implementation of clear button?

**Comment by sipayRT** [comment]
custom implementation of clear button is just for `islands` theme. In your own theme you'll get native clear button.

**Comment by dfilatov** [comment]
@sipayRT Could you add a workaround to make it works in Chrome?

**Comment by Guria** [comment]
@sipayRT custom implementation of clear button is not just for `islands` theme. it provides common js functionality without relate to any theme used.

**Comment by sipayRT** [comment]
@Guria I told you about visual realization. For example, 

```
{
    block : 'input',
    mods : { type : 'search', theme : 'custom' },
    val : 'search query'
}
```

in this case you will get native clear button - 
![input](https://cloud.githubusercontent.com/assets/1658415/6441159/0c797b2a-c0f6-11e4-97a0-cf0ccd0aa43c.png)

**Comment by sipayRT** [comment]
> Could you add a workaround to make it works in Chrome?

@dfilatov I'll try

**Comment by Guria** [comment]
@sipayRT please see @tadatuta opinion in #1379 and #1346 about `type: hidden`, `list` attributes and other features that doesn't have a broad support.
We could use standart html attribute for native browser features, and don't need a support for it in library.

**Comment by sipayRT** [comment]
@Guria  I know about these issues, but in bem-components we have some rule, where you can add some functionality just if it's needed for big count of users. So `type='search'` - it's this case. You can ask @veged about this rule

**Comment by Guria** [comment]
OK, got the point.
