### ISSUE TITLE
input: placeholder in IE8

### ISSUE THREAD

**Issue by deeonis** [bem/bem-components#1388]
It seems that placeholder doesn't work in IE8 (cause it based on native). 
Need to check it up.

**Comment by sipayRT** [comment]
@mishanga what do you think about adding placeholder to IE8?

**Comment by mishanga** [comment]
Мы договаривались, что все костыли для ИЕ8 будем делать только на уровне CSS. Если это невозможно — c'est la vie.

**Comment by sipayRT** [comment]
вот полностью согласен!

**Comment by narqo** [comment]
@mishanga а как быть с формами в которых placeholder — это единственный способ понять, как этим пользоваться? Точно мы хотим, чтобы в IE8 форма регистрации ящика выглядила так:
![screen shot 2015-03-10 at 14 29 59](https://cloud.githubusercontent.com/assets/88045/6574096/19417d84-c732-11e4-9af7-e0c5fcc7de30.png)

**Comment by sipayRT** [comment]
@narqo добавить подписи к инпутам? Ведь в твоем примере подписано поле "С помощью телефона Вы сможете восстановить пароль".

**Comment by mishanga** [comment]
+1 к @sipayRT 
Для таких форм нужно делать специальный фолбек для ИЕ8 на уровне сервиса или мета-блока (домика).

**Comment by dfilatov** [comment]
Мое мнение: добавить input.ie8.js с полифилом, и тот, кому нужна поддержка IE8, должен включать в сборку такие файлы, наравне с *.ie8.styl.

**Comment by sipayRT** [comment]
Как это реализовать - понятно. имхо, тут другой вопрос - кому это нужно? Тут как раз подходит правило Вегеда - не делать то, что никому не нужно. Т.е. сначала нужно найти тех, кто заинтересован в этом полифиле

**Comment by mishanga** [comment]
@1999 Дима, вам это надо?

**Comment by 1999** [comment]
Обойдемся без него

**Comment by aristov** [comment]
[maybe](https://github.com/bem/bem-components/blob/ie8-blocks/msie8.blocks/input/__placeholder/input__placeholder.js)

**Comment by sipayRT** [comment]
@aristov это ничем не будет отличаться от input.ie8.js

**Comment by aristov** [comment]
Вопрос в том, является ли IE8 платформой или технологией. На мой взгляд, логичнее делать разделение по платформам и считать IE8 частным случаем `desktop`, тогда мы выносим все костыли на специальный уровень, реализующий функционал библиотеки в этом браузере и подключаем его вместе с `desktop` там где это нужно.

**Comment by qfox** [comment]
Я в чем-то солидарен с @aristov. Часть того, под что есть специальные технологии, сильно элегантнее могло было быть решено выносом на отдельный уровень.
Не знаю, правда, получится ли так полноценно с i18n, но и там тоже руки чешутся переосмыслить все.
В любом случае, ie вполне подходит под отдельный уровень с моей точки зрения. И даже вполне вписывается в платформы.

**Comment by narqo** [comment]
Коллективным разумом решили, что `placeholder` в IE нужен. Но, поскольку кода про него, кажется, немного, можно оставить его реализацию в основном JS-коде, добавив проверку на ie.

**Comment by tadatuta** [comment]
С последнего обсуждения доля IE8 упала еще сильнее. Давайте закрывать? :)

**Comment by tadatuta** [comment]
Nobody cares
