### ISSUE TITLE
textarea в депсах нет инпута

### ISSUE THREAD

**Issue by aliosv** [bem/bem-components#1413]

**Comment by blond** [comment]
`textarea` зависит не от всего `input`, а только от `js` технологии: https://github.com/bem/bem-components/blob/v2/common.blocks/textarea/textarea.deps.js#L10-L13

**Comment by tadatuta** [comment]
@aliosv собирать JS в результате нужно примерно так: https://github.com/bem/bem-components/blob/v2/.enb/make.js#L198-L217

**Comment by aliosv** [comment]
@andrewblond, @tadatuta спс
