### ISSUE TITLE
input: add `hidden` value to the `type` modificator

### ISSUE THREAD

**Issue by remnev** [bem/bem-components#1441]
It's necessary for hidden fields, like `<input type="hidden"/>`.
I'm going to contribute it. Are there any objections?

**Comment by Guria** [comment]
Yes, please search an issues.

**Comment by aristov** [comment]
It could be implemented as a separate block or as an element of control, that needs it, but, anyway, it's not a type of the `input` block.

**Comment by tadatuta** [comment]
https://github.com/bem/bem-components/issues/1379
