### ISSUE TITLE
select: Keyboard support degradation after v2.1.0

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-components#1456]
For more details please refer https://github.com/bem/bem-forum-content-ru/issues/353

**Comment by tadatuta** [comment]
cc @aristov

**Comment by tadatuta** [comment]
degradation was introduced in https://github.com/bem/bem-components/pull/1383
// cc @dfilatov

**Comment by qfox** [comment]
@tadatuta @narqo That's interesting. Code stops listening on losing focus, but selection (hover?) still exists. That means:
1) Focus should be on `menu` while we walking on `menu-item`s;
2) But logically there can be internal blocks with focus (which can ruin block itself);
3) Focus/blur should listen for bubbling events from internal DOM-nodes.

Am I right here?

**Comment by qfox** [comment]
![image](https://cloud.githubusercontent.com/assets/677518/6998928/7aa6363c-dbfa-11e4-8187-38ea986d1602.png)
![image](https://cloud.githubusercontent.com/assets/677518/6998965/8e2f6b36-dbfc-11e4-859f-7ab7b11c6e9d.png)
But
![image](https://cloud.githubusercontent.com/assets/677518/6998932/b323e554-dbfa-11e4-91a2-14987173a1f8.png)

@tadatuta Btw, this hover in location bar hiding away on keyboard activity. While there is no special state for hover in system menus of browsers (chrome/yandex). But still there are special buttons in them which could ruin menu block.

**Comment by tadatuta** [comment]
as far as I understand, `_onFocus()` is never called when a user opens `select` because `menu` is not focusable (so native `focusin` is not fired). at least when I added force call of `_onFocus()` to `_focus()` keyboard started working as expected.

but `menu` itself not being a part of `select` works just fine.

**Comment by qfox** [comment]
@tadatuta I'd make a test with focusable block/element inside menu-item.
