### ISSUE TITLE
menu: проверить соответствие руководству по доступности

### ISSUE THREAD

**Issue by aristov** [bem/bem-components#1458]
Проверить, соответствует ли блок `menu` описанию из руководства по доступности:

> Механика меню
> Фокус устанавливается только на кнопку, открывающую меню — фокус всегда установлен на этой кнопке. Элементы меню должны быть исключены из навигации, с использованием клавиши Tab.
> Выпадающее меню открывается только при активации кнопки, закрывается — при нажатии Escape.
> Первый элемент меню становится текущим после открытия. Текущий элемент выделяется визуально. Стрелка вниз делает текущим следующий элемент, стрелка вверх — предыдущий. Если следующего нет — текущим становится первый, если нет предыдущего — последний.
> Меню может содержать вложенное меню. Вложенное меню открывается нажатием стрелки вправо и закрывается нажатием стрелки влево.
> Текущий элемент меню активируется нажатием Spacebar или Enter. После активации текущего элемента меню закрывается.

Внести исправления, если найдутся несоответствия.

**Comment by Guria** [comment]
Блок `menu` кажется  совсем не про меню. Скорее всего это некий `list`.
То что описано в руководстве, в библиотеке не реализовано.
Возможно стоит рассмотреть возможность переименования, по аналогии с #1447

**Comment by tadatuta** [comment]
@Guria 
не возьмусь судить про соответствие названию `menu`, но `list` — это скорее про контент/типографику типа:
- раз
- два
- три

**Comment by Guria** [comment]
Может не list, но точно не меню. Это же список итемов.
А вообще похожие по смыслу сущности, правда более навороченные, чаще всего называются по типу ListView.
https://msdn.microsoft.com/en-us/library/windows/apps/br211837.aspx
http://demos.telerik.com/kendo-ui/mobile-listview/index

**Comment by qfox** [comment]
@Guria ;-) В Яндексе своя терминология, не спорь! Можно, правда, поставить вопрос при переезде на v3, но это опять всем всё сломает. С другой стороны, порог входа от этого только уменьшится. Можно пообсуждать.

**Comment by Guria** [comment]
Ну в руководстве по доступности под меню явно имеют ввиду именно меню :)
На фоне изменений i-bem в bem-core@v3 переименование пары блоков будет наименьшей проблемой.

**Comment by qfox** [comment]
@Guria Согласен, если возвращаться к issue — путаница.

**Comment by aristov** [comment]
В приведенной цитате из руководства речь идет о выпадающем меню, которым у нас по сути является блок `select`. В рамках этого ишью достаточно проверить только те требования, которые относятся непосредственно к меню:

> Элементы меню должны быть исключены из навигации, с использованием клавиши Tab.
> 
> Текущий элемент выделяется визуально. Стрелка вниз делает текущим следующий элемент, стрелка вверх — предыдущий. Если следующего нет — текущим становится первый, если нет предыдущего — последний.
> 
> Текущий элемент меню активируется нажатием Spacebar или Enter.

Вложенные меню у нас не поддерживаются.

**Comment by aristov** [comment]
[issue про `select`](1465)

**Comment by aristov** [comment]
Проверено. Меню работает правильно, исправления не требуются. Закрываю.
