### ISSUE TITLE
modal: проверить соответствие руководству по доступности

### ISSUE THREAD

**Issue by aristov** [bem/bem-components#1459]
Проверить, соответствует ли блок `modal` описанию из руководства по доступности:

> Механика модальных окон
> Модальное окно запоминает элемент, на котором был установлен фокус до его открытия. При открытии, фокус устанавливается на любой элемент, пригодный для фокуса, внутри модального окна, в соответствии с алгоритмом табуляции.
> Модальные окна зацикливают фокус внутри себя. Последний пригодный для фокуса элемент, внутри модального окна, перехватывает нажатие клавиши Tab и устанавливает фокус на первый. Первый элемент перехватывает нажатие Shift + Tab и устанавливает фокус на последний.
> Модальное окно закрывается нажатием Escape или активацией элементов внутри него. После закрытия модального окна, фокус возвращается на тот элемент, на котором он был установлен до его открытия.

Внести исправления, если найдутся несоответствия.

**Comment by tadatuta** [comment]
не забыть https://github.com/bem/bem-components/issues/1026

**Comment by aristov** [comment]
Проверил: есть несоотвествия. 
Подробности в #1674. Этот ишью закрываю.
