### ISSUE TITLE
input: split `val` method into 'setVal' and 'getVal'

### ISSUE THREAD

**Issue by dfilatov** [bem/bem-components#146]

**Comment by dfilatov** [comment]
closed by bceefa5f3e5867ac5fa15c6ba8b53a6ed8c7cb7a

**Comment by narqo** [comment]
@dfilatov 

А что будет со «сложными» `vals()`, как например в слайдере:

```
Slider#vals(
  [ Number idx ], 
  Number | Array<Number> val
)
```

**Comment by dfilatov** [comment]
Видимо, прислушиваясь к мнению большинства, буду сделаны несколько конкретных геттеров/сеттеров:
`getVal([idx=0])`
`getVals()`
`setVal(val, [idx=0])`
`setVals(vals)`
