### ISSUE TITLE
popup: проверить соответствие руководству по доступности

### ISSUE THREAD

**Issue by aristov** [bem/bem-components#1460]
Проверить, соответствует ли блок `popup` описанию из руководства по доступности:

> Механика общего случая всплывающих окон
> Фокус переходит на кнопку, открывающую всплывающее окно. Окно открывается и закрывается при последовательной активации кнопки. Фокус остаётся на кнопке после открытия окна.
> Внимание! Не следует переставлять фокус после активации! Это важно. Не смешивайте активацию и навигацию!
> Кнопка начинает перехватывать нажатие Tab. Нажатие клавиши Tab переносит фокус на первый пригодный для фокуса элемент, внутри всплывающего окна; нажатие Shift+Tab — на последний. Порядок элементов, пригодных для фокуса, определяется алгоритмом табуляции.
> Последний, пригодный для фокуса элемент, перехватывает нажатие Tab и возвращает фокус на кнопку, которая открыла окно. Первый элемент – перехватывает нажатие Shift+Tab и возвращает фокус на кнопку. То есть всплывающее окно зацикливает фокус между своими элементами и кнопкой, его открывшей.
> Всплывающее окно может содержать вложенные всплывающие окна. Вложенное окно создаёт собственный цикл из элементов для фокуса.
> Нажатие Escape закрывает последнее открытое окно. Фокус возвращается на кнопку, его открывшую.

Внести исправления, если найдутся несоответствия.

**Comment by tadatuta** [comment]
jfyi, https://nda.ya.ru/3QjAfE

**Comment by aristov** [comment]
Проверил: есть несоотвествия. 
Подробности в #1673. Этот ишью закрываю.
