### ISSUE TITLE
No tags for release commits?

### ISSUE THREAD

**Issue by qfox** [bem/bem-components#1461]
Guys, can we add a rule in maintainers guide to mark with tags releases?

/cc @tadatuta @narqo @veged @dfilatov

**Comment by narqo** [comment]
But we have tags for all of our releases: 
- https://github.com/bem/bem-components/tags 
- https://github.com/bem/bem-core/tags

**Comment by qfox** [comment]
Sorry. I've mixed up bem-core and bem-components version. Didn't find 2.5 and 2.6 ;-(
