### ISSUE TITLE
Rename .bemhtml files to .bemhtml.js

### ISSUE THREAD

**Issue by arikon** [bem/bem-components#1464]
For that we will get:
- syntax highlighting on Github and in all the editors for free
- linters (jshint, jscs) will work with templates without additional configuration

Linked issue https://github.com/bem/bem-core/issues/984

**Comment by qfox** [comment]
:+1:

**Comment by awinogradov** [comment]
:+1:

**Comment by sbmaxx** [comment]
:+1:

**Comment by voischev** [comment]
:+1:
