### ISSUE TITLE
menu-item_type_link: move out css rule to fit clickable area out of islands theme

### ISSUE THREAD

**Issue by Guria** [bem/bem-components#1467]
https://github.com/bem/bem-components/blob/v2/design/common.blocks/menu-item/_theme/menu-item_theme_islands.styl#L44

This rule should be applied without any theme used, I think

**Comment by aristov** [comment]
cc @sipayRT

**Comment by sipayRT** [comment]
@Guria but in custom theme can be used horizontal menu in which this property is not needed. I'm not sure that we need to add `:after` by default // cc @mishanga

**Comment by mishanga** [comment]
+1 to @sipayRT

**Comment by Guria** [comment]
@sipayRT horizontal menu in custom theme with [current](https://github.com/bem/bem-components/blob/v2/common.blocks/menu/menu.js#L184) `menu` block implementation? :laughing: 
Currently `menu` block very specific and it is not about menu in fact.

**Comment by sipayRT** [comment]
> Currently menu block very specific

exactly! And this theme is very specific too. Thats why this part of code can't be used by default. For example, in your theme you may not use `padding` property and you can apply to the link `display: block;` instead of `::after`. In this case you don't need pseudo-element at all

**Comment by Guria** [comment]
I got a point. Just loled about custom implementations.
`menu` good block, but too specific both in templates in js tech. But it is a topic for another issue.
