### ISSUE TITLE
checkbox: Doesn't work on touch devices

### ISSUE THREAD

**Issue by narqo** [bem/bem-components#1472]
`checkbox` doesn't work properly on touch devices, at least on iPad/iPhone under the iOS 8.3 as well as touch devices emulator in Chrome.

In the [checkbox](https://en.bem.info/__example/bem-components/v2.1.0/desktop.examples/checkbox/5nmu9H4NkVi7P48W_Yx7tHZy6Hk/5nmu9H4NkVi7P48W_Yx7tHZy6Hk.html) example it is impossible to toggle `checked` state by tapping on the checkbox itself. While tapping on the `label` text works as expected.

See ftlabs/fastclick#351 for additional details

**Comment by narqo** [comment]
Looks like there is a problem(-s) with iOS and the FastClick library (`bem-core/jquery__event_type_pointerclick`).

**Comment by narqo** [comment]
One possible solution, is to move `checked` state maintaining from `change` event in `__control` to modifier, as we do in `button_type_check`. 

Here is the monkey-patched version with project level overrides:

``` js
modules.define('checkbox', ['i-bem__dom', 'jquery', 'dom'], function(provide, BEMDOM, $, dom) {

provide(BEMDOM.decl(this.name, {
    /** @override */
    _onChange : function() {
        this.elem('control').prop('checked', this.getMod('checked'));
    },

    _onPointerPress : function() {
        if(!this.hasMod('disabled')) {
            this.bindToDoc('pointerrelease', this._onPointerRelease);
        }
    },

    _onPointerRelease : function(e) {
        this.unbindFromDoc('pointerrelease', this._onPointerRelease);
        dom.contains(this.domElem, $(e.target)) && this._updateChecked();
    },

    _updateChecked : function() {
        this.toggleMod('checked');
    }
}, {
    live : function() {
        this.liveBindTo('pointerpress', this.prototype._onPointerPress);
        return this.__base.apply(this, arguments);
    }
}));

});

```

**Comment by dfilatov** [comment]
Doesn't this patching affect `checkbox_type_button`?
What about keyboard?

**Comment by narqo** [comment]
Yep, it seems, that both keyboard and `checkbox_type_button` won't work with it :( Guess, we need to think about fixing FastClick problem from `bem-core` first
