### ISSUE TITLE
No tmpl-tests for progressbar_theme_simple?

### ISSUE THREAD

**Issue by qfox** [bem/bem-components#1478]
Not sure that we need it, but since there is a template, I think we should provide a simple case.

**Comment by sipayRT** [comment]
this theme is just for example. So we don't need any tests for it

**Comment by qfox** [comment]
@sipayRT I think we should move this theme to separate level then ;-\ Or something... It looks like inconsistency.

**Comment by narqo** [comment]
@zxqfox we don't have any kind of the specs for simple theme in general. The main thing of why do we have it is that we had a lot of problems with themeless blocks in the past. In the bem-components we're trying to prevent such things like "default" theme styles, so we need `simple` one to check our blocks are steel "themeable". 

`_theme_simple` is definitely not the thing that we should start test now, as there are still a lot of other useful stuff to be done and fix, IMHO.

**Comment by qfox** [comment]
@narqo So, decision is: we will test it in future, we drop them in future, or else?

**Comment by narqo** [comment]
> we drop them in future, or else

I prefer to have one of these. But I don't have any exact timelines currently.

**Comment by qfox** [comment]
@narqo I'd suggest to move them all to separate level for now (as it does for design). Not sure really why we need them at all.

**Comment by narqo** [comment]
To move what? `tmpl-specs` or `_theme_simple` files? To be honest I don't understand what problem do we try to solve here?

**Comment by qfox** [comment]
> To move what? tmpl-specs or _theme_simple files?

Useless `_theme_simple` files. I suggest to keep codebase clean, to have tmpl-specs for each supported templates. If we don't need `_theme_simple` then we can move them out of active code base.

**Comment by narqo** [comment]
> If we don't need _theme_simple then we can move them out of active code base.

I think, to move something out (or remove at all) and don't add additional tests for useless stuff, are different questions from the compatibility point. We can add an issue about removing `simple` from the bem-components, but to `v3` future only

**Comment by qfox** [comment]
:+1: Fine for me.
