### ISSUE TITLE
button: rename _togglable modifier

### ISSUE THREAD

**Issue by aristov** [bem/bem-components#1480]
`button_togglable_check` => `button_type_checkbox`
`button_togglable_radio` => `button_type_radio`

`togglable` and `type` modifiers can not be used simultaneously.
So I propose to merge them into `type` modifier and correct values.

**Comment by sipayRT** [comment]
`button_type_checkbox` and `checkbox_type_button`?

**Comment by aristov** [comment]
Oh shit...

**Comment by veged** [comment]
in consistency with other blocks better not use `_type` for such modifications
