### ISSUE TITLE
link: add ability to prevent native behaviour

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-components#1485]
**Usecase**

``` js
BEMDOM.blocks.link.on('click', function(e) {
    e.preventDefault(); // won't work as e is BEM event
});
```

**Proposal**
Provide original DOM event as a second argument to BEM `click` event so it could be used like this:

``` js
BEMDOM.blocks.link.on('click', function(bemEvent, domEvent) {
    domEvent.preventDefault();
});
```

**Comment by qfox** [comment]
Can `bemEvent` be extended by `domEvent`?

**Comment by dfilatov** [comment]
If all you need is `preventDefault`, there's no need to pass `domEvent`. It can be done within `link`.

**Comment by tadatuta** [comment]
@dfilatov can you please show an example?
I tried two snippets:

``` js
this.bindTo(this.findBlockInside('link').domElem, 'click', function(e) {
    console.log('e', e);
    e.preventDefault(); // works fine
});

BEMDOM.blocks.link.on(this.domElem, 'click', function(e) {
    console.log('e', e);
    e.preventDefault(); // doesn't work
});
```

**Comment by dfilatov** [comment]
It doesn't work currently. We need to add a few lines of code to `link` to support such thing.
