### ISSUE TITLE
popup: Fix typos in popup.examples/20-popup.bemjson.js

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-components#1494]
`mods` should be `elemMods` in https://github.com/bem/bem-components/blob/v2/common.blocks/popup/popup.examples/20-popup.bemjson.js#L75-L77 (and further on).

**Comment by qfox** [comment]
Hey there: bem/bem-method#250

**Comment by tadatuta** [comment]
@zxqfox At least until that issue is answered it's a bug ;)
