### ISSUE TITLE
input: improve JAWS readability

### ISSUE THREAD

**Issue by aristov** [bem/bem-components#1504]
JAWS should read
- [x] `input` as "edit"
- [x] `input_type_password` as "password edit"
- [x] `input_type_search` as "edit"
- [x] `_disabled` as "unavailable"
- [x] `val` field
- [x] `val` field of `input_type_password` as "star, star, star"
- [x] `placeholder` field of `input_focused`

Check and fix divergencies.

**Comment by aristov** [comment]
http://www.w3.org/TR/wai-aria/roles#textbox
http://www.w3.org/TR/wai-aria/states_and_properties#aria-disabled

**Comment by sipayRT** [comment]
Block was tested. It complies with standarts

**Comment by aristov** [comment]
Ok.
