### ISSUE TITLE
checkbox, radio: emit change

### ISSUE THREAD

**Issue by voischev** [bem/bem-components#1506]
Почему эти блоки не кидают событие change?

**Comment by tadatuta** [comment]
Потому что можно подписаться на изменение модификатора.

**Comment by voischev** [comment]
@tadatuta Приведи пример и можно закрыть

**Comment by tadatuta** [comment]
``` js
// подписка из самого себя
this.on({ modName: 'checked', modVal: '*' }, function(e, data) {
    // e — объект события
    // data содержит поля modName, oldModVal и modVal
});

// подписка из блока-родителя
checkbox.on(this.domElem, { modName: 'checked', modVal: '*' }, function(e, data) {});
```

**Comment by voischev** [comment]
а такое `this.findBlockInside('checkbox').on({ modName: 'checked', modVal: '*' }, function(e, data) {})` тоже же работает внутри блока родителя?

**Comment by narqo** [comment]
@voischev «событие изменения модификатора» ничем, принципиально, не отличаются от обычных БЭМ-событий. Единственное отличие — в `data` параметре придет структура `{ modName, modVal, oldModVal }`.

Такие события работают везде, где работают БЭМ-события: `on()`, `un()`, `liveInitOnBlock*()` и пр.

Примеры:
- [menu](https://github.com/bem/bem-components/blob/v2.1.1/common.blocks/menu/menu.js#L223-L229)
- [select](https://github.com/bem/bem-components/blob/v2.1.1/common.blocks/select/select.js#L38-L40)

**Comment by voischev** [comment]
@narqo @tadatuta Красота! Спасибо!
