### ISSUE TITLE
input, textarea: _width_available не работает без модификатора _theme

### ISSUE THREAD

**Issue by AndreyGladkov** [bem/bem-components#1514]
Ребят вопрос по этому модификатору, прикрутил bem-components к своему проекту, заюзал input  c модификатором width:available который должен распирать на всю ширину input, но этого не происходит, потому как у вас в css

``` css
.input_width_available
{
    width: 100%;
}
```

и в bemhtml

``` js
block('input')(
    tag()('span'),
    js()(true),
    def()(function() {
        applyNext({ _input : this.ctx });
    }),
    content()({ elem : 'box', content : { elem : 'control' } })
);
```

А тег span это inline, а надо бы задать display: inline-block что бы width работал, и протащить по остальному каскаду вложенности.
Или я что то не правильно понял в библиотеке?

**Comment by aristov** [comment]
Вероятно ты используешь блок без темы: https://github.com/bem/bem-components/blob/v2/design/common.blocks/input/_theme/input_theme_islands.styl#L7
Если тебе нужно сделать свою тему, то ты можешь просто написать эти стили на своем уровне.

**Comment by tadatuta** [comment]
@aristov 
На самом деле это все равно баг, т.к. мы специально выносили `_width_available` из темы (https://github.com/bem/bem-components/pull/1405) :(

**Comment by voischev** [comment]
:+1:

**Comment by dfilatov** [comment]
Вынести стили для `_width_available` из темы в коммон было ошибкой. Какие стили нужны блоку в конкретной теме, чтобы растягиваться на всю ширину, может решаться только в пределах темы с учетом всех остальных стилей. Кажется эту булочку мы уже ели.

**Comment by qfox** [comment]
@dfilatov :+1: :smirk_cat:

**Comment by aristov** [comment]
#1548
