### ISSUE TITLE
textarea: improve JAWS readability

### ISSUE THREAD

**Issue by aristov** [bem/bem-components#1515]
JAWS should read
- [x] `textarea` as "edit"
- [x] `textarea_disabled` as "edit unavailable"
- [x] `textarea_focused` with specified `val` field as "edit, contains text"
- [x] `val` field
- [x] `placeholder` field of `textarea_focused`

Check and fix divergencies.

**Comment by aristov** [comment]
Depends on #1504.

**Comment by aristov** [comment]
http://www.w3.org/TR/wai-aria/roles#textbox
http://www.w3.org/TR/wai-aria/states_and_properties#aria-multiline
http://www.w3.org/TR/wai-aria/states_and_properties#aria-disabled

**Comment by sipayRT** [comment]
Block was tested. It complies with standarts

**Comment by aristov** [comment]
Ok.
