### ISSUE TITLE
Migrate to postcss in major version update

### ISSUE THREAD

**Issue by Guria** [bem/bem-components#1535]
PostCSS could manage all needed build steps.
What you think about migration on it in next major update?

**Comment by blond** [comment]
:+1:

**Comment by tadatuta** [comment]
@Guria migrate from `borschik`? It there a reason for that if we still need `borschik` for JS-based techs and can share same config?

**Comment by Guria** [comment]
@tadatuta I mean all css transformations:
[postcss-import](https://github.com/postcss/postcss-import), [postcss-simple-vars](https://github.com/postcss/postcss-simple-vars), [postcss-nested](https://github.com/postcss/postcss-nested) with [postcss autoprefixer](https://github.com/postcss/autoprefixer) could replace stylus with autoprefixer.
[Fallback plugins](https://github.com/postcss/postcss#fallbacks) could manage IE hacks
[Optimization plugins](https://github.com/postcss/postcss#optimizations) could replace borschik including freezes and minifying.
And we'll get first class sourcemap support free of charge, of course.
Also I'd suppose to create own set of bem oriented plugins:
- configurable custom selectors for Blocks, Elements and Modifiers;
- additional optional namespacing for blocks;
- etc

**Comment by awinogradov** [comment]
Problems:
- postcss-simple-vars plugin can't work with arrays. `$var: [1,2]; .sel_$(var[i]) {}` don't work
- you can't freeze js without borschik
- syntax highlithing don't work right on *.css with nested selectors, operators and variables
- you need compiled version of all css for every block, because many users don't use postcss
- postcss-each, postcss-for and postcss-simple-vars can work with conflicts when you use them in a different order or with equal vars
- postcss-each to my recent edits I could not work simultaneously with the selection of values and increment (Solved)

I switched all projects to postcss with [enb-postcss](https://github.com/verybigman/enb-postcss)

**Comment by tadatuta** [comment]
@verybigman if there's such a lot of problems why have you switched to it? :)

**Comment by awinogradov** [comment]
@tadatuta We have many many hours with code refactoring in last weeks:)

**Comment by tadatuta** [comment]
OK, will try to ask what I really wanted to know: having this experience would you switch anyway? And why if so?

**Comment by awinogradov** [comment]
You really know postcss is not stylus and most of the code will have to rewrite. Especially in places where there are cycles. But cssnext features, automatic fallbacks and lost grid(bem-grid is wrapper for it now) cover all the shortcomings. Also simple plugins scheme allows you to do anything;) Furthermore CSS becomes similar to CSS and not arbitrary code contains. You must be prepared for the fact that for any nonsense have to put a little plug-in.

**Comment by belozer** [comment]
To writing css selectors we will use a `pobem`, or `rebem-css`?

`Rebem-css` - works faster (fewer calculations) and it is less flexible in use. Designed to rebem organization.
`Pobem` - supports rebem syntax and allows you to write more concise code. Designed to bem organization. Easier to do PR.

**Comment by tadatuta** [comment]
@belozyorcev  let's use `rebem` in `bem-components` which is backward compatible with `pobem` and as so users will have  ability to choose from both.

**Comment by belozer** [comment]
@tadatuta I agree with you.

**Comment by belozer** [comment]
``` stylus
.attach
{
    touch-action: manipulation;

    &__file,
    &__no-file,
    .button__text,
    .attach_disabled .attach__clear // This is Bug ?
    &.attach_disabled .attach__clear // Maybe it should be? 
    &_disabled .attach__clear // Or 
    {
        display: none;
    }
}
```

https://github.com/bem/bem-components/blob/issues/1535%40v4/common.blocks/attach/attach.post.css

upd.
![2016-08-27 01-19-37](https://cloud.githubusercontent.com/assets/1655916/18022067/89ee32d0-6bf4-11e6-8f40-ca95b56d41f2.png)
