### ISSUE TITLE
spin: improve JAWS readability

### ISSUE THREAD

**Issue by aristov** [bem/bem-components#1537]
Should we add any sound notification for [`spin_visible`](https://ru.bem.info/__example/bem-components/v2.2.0/desktop.examples/spin/NadQI6Wwr2e2t73Ypu5Vp3Jg6JI/NadQI6Wwr2e2t73Ypu5Vp3Jg6JI.html)?

**Comment by aristov** [comment]
cc @ruslansagitov

**Comment by ruslansagitov** [comment]
I guess no. I see it as a decoration. You may set `aria-busy` on `<body>` or any enclosing element, which is updating, to notify about the change but as I know no browsers are support this state.
