### ISSUE TITLE
Uncaught Error: Module "textarea": can't resolve dependence "input"

### ISSUE THREAD

**Issue by 4ok** [bem/bem-components#1565]
Textarea не подтягивает в сборку технолгию js блока input, хотя в deps он прописан

**Comment by blond** [comment]
Скорее всего это особенности сборки. У `js` технологии блока `textarea` есть зависимость от `js` технологии блока `input`: https://github.com/bem/bem-components/blob/v2/common.blocks/textarea/textarea.deps.js#L10-L13.

Чтобы они попали нужно проделать ряд дополнительных манипуляций при сборке: https://github.com/bem/bem-components/blob/v2/.enb/make.js#L73-L94

**Comment by Guria** [comment]
Как раз недавно думал что за js-js такой в конфиге ENB. Зачем такое усложнение?

**Comment by narqo** [comment]
> Как раз недавно думал что за js-js такой в конфиге ENB. Зачем такое усложнение

Это было сделано, чтобы при подключении на страницу только `textarea` не приезжали шаблоны и CSS блока `input`. По факту, `textarea` нужен только js-блока `input` в качестве baseBlock'а.

@blond а нет в планах (хотя бы на 2015-й :) начать делать честные `depsByTech`, чтобы результат сборки технологией deps, был не просто список БЭМ-сущностей, а полный граф зависимостей `tech → tech`?. Все текущие deps'ы при этом могут выражаться через `{ block='a', tech='*' } → { block='b', tech='*' }`

**Comment by Guria** [comment]
На сколько я понимаю сейчас это не работает и все равно приезжает весь блок? И при этом усложняется корректная сборка в сторонних проектах. Сама сборка тоже не очень документированы.

**Comment by Guria** [comment]
И если уж нужна такая хитрая зависимость корректнее было бы сделать в обычных shouldDeps зависимость от технологии js блока input.

**Comment by blond** [comment]
> хотя бы на 2015-й

ты хотел сказать 2016-й? ))

> а нет в планах начать делать честные depsByTech

В очень слабом приоритете есть — https://github.com/bem-incubator/bem-deps/issues/2. Прямо сейчас пишем [спецификацию](https://github.com/bem-incubator/bem-deps/tree/master/spec). Пока там всё сыро, план работ — https://github.com/bem-incubator/bem-deps/issues/3. Дальше спецификации в ближайшее время вряд ли что-то сделаем.

> На сколько я понимаю сейчас это не работает и все равно приезжает весь блок?

Нет, сейчас работает правильно. Проблема только в сложности сборки любых `depsByTech` зависимостей.

> И если уж нужна такая хитрая зависимость корректнее было бы сделать в обычных shouldDeps зависимость от технологии js блока input.

Что ты имеешь ввиду?

**Comment by Guria** [comment]
> Что ты имеешь ввиду?

Я имел ввиду, что зависимость блока textarea, по идее, должна быть описана так: 

``` js
{
    mustDeps : { block : 'i-bem', elems : 'dom' },
    shouldDeps : [
        {
            mods : ['disabled', 'focused']
        },
        'control',
        { tech : 'js', block : 'input' }
    ]
}
```

Но как раз для этого и нужны "честные" `depsByTech`. Уточнение, что зависит именно технология js блока `textarea` избыточно, и требовалось только для выделения этого особого случая и сборки с помощью `js-js`.

> Нет, сейчас работает правильно. Проблема только в сложности сборки любых depsByTech зависимостей.

Ага, понял. Понятно, что честные `depsByTech` гораздо более трудоёмки, чем дополнительные шаги для сборки, но...

> Это было сделано, чтобы при подключении на страницу только textarea не приезжали шаблоны и CSS блока input. По факту, textarea нужен только js-блока input в качестве baseBlock'а.

Стили и так бы не приехали, т.к. подключаются только по модификатору. Экономия на шаблонах кажется смехотворной: [input.bemhtml](https://github.com/bem/bem-components/blob/v2/common.blocks/input/input.bemhtml), [input__box.bemhtml](https://github.com/bem/bem-components/blob/v2/common.blocks/input/__box/input__box.bemhtml) и [input__control.bemhtml](https://github.com/bem/bem-components/blob/v2/common.blocks/input/__control/input__control.bemhtml).
Мне кажется усложнение сборки ради одного блока `textarea` и экономии 29 строк шаблонов в особом вырожденном случае (не используется блок `input`) неоправданно.

**Comment by blond** [comment]
> Но как раз для этого и нужны "честные" depsByTech. Уточнение, что зависит именно технология js блока textarea избыточно, и требовалось только для выделения этого особого случая и сборки с помощью js-js.

Не совсем так. Такая запись предполагала бы, что любая технология этого блока зависит от `js`.

И если говорить об честных зависимостях и «умной» сборке, то сборка бы решила, что чтобы корректно работала скажем `css`, то ей нужно ещё собрать `js` и как-то их склеить.

> Мне кажется усложнение сборки ради одного блока textarea и экономии 29 строк шаблонов в особом вырожденном случае (не используется блок input) неоправданно.

Наверное, соглашусь :)

@narqo, что скажешь?

**Comment by Guria** [comment]
> Такая запись предполагала бы, что любая технология этого блока зависит от js.

Эта запись говорит, что блоку в целом нужна js технология другого блока и без неё не имеет смысла.

**Comment by blond** [comment]
> Эта запись говорит, что блоку в целом нужна js технология другого блока и без неё не имеет смысла.

Сборка не бывает абстрактной, она всегда по технологиям. Поэтому, если мы не указываем явно технологию, это равносильно `tech: '*'`. 

Если в результате мы хотим получить только декларацию БЭМ-сущностей, то \* -> js и js -> js дадут одинаковый результат. 

Но в общем случае результат разный, т.к. кроме самой декларации мы можем получить ещё дополнительную информацию о том, что эта декларация зависит от других технологий.

**Comment by narqo** [comment]
> > Наверное, соглашусь :)
> > @narqo, что скажешь?

Нормально, давайте напишем, только добавим комментарий, что это не «от хорошей жизни», а потому что нет нормальной поддержки `depsByTech`.

**Comment by qfox** [comment]
Нашли комментарий в textarea.deps.js со ссылкой на это issue.

В bem-deps это выражается как и не требует изменений сборки:

``` js
{
    tech : 'js',
    shouldDeps: [
        { block: 'input' }
    ]
},
```

При такой декларации в сборку css-файла, равно как и других технологий, не попадут файлы блока input. Только js.
