### ISSUE TITLE
button: wrong definition of real button

### ISSUE THREAD

**Issue by sipayRT** [bem/bem-components#1566]
Now in templates we check just `type` modifier:

```
var modType = ctx.mod('type'),
      isRealButton = !modType || modType === 'submit';
```

But if we will change in BEMJSON tag, for example, to `<div>`, variable `isRealButton` still will be `true`. It's wrong because we can't add some attributes such as `disabled` to `<div>`. 

In the `attach` block it's very important because we use `<span>` tag instead of `<button>`. As a result — disabled button in `attach` block will be disabled only visually for a11y's programs.

**Comment by sipayRT** [comment]
@veged @dfilatov @narqo @tadatuta @aristov 
Are we really need to keep in mind the possibility of changing the tag? Or we shouldn't support it?

**Comment by tadatuta** [comment]
as we already use different tag in `attach` I suggest to add the check for tag to `isRealButton` condition as well
