### ISSUE TITLE
input: support `text` attribute for label

### ISSUE THREAD

**Issue by Guria** [bem/bem-components#1570]
input fields often used with labels. `checkbox` and `radio` has `text` attribute for use as labels.
I suggest to add the same attribute for `input`.

**Comment by tadatuta** [comment]
@Guria actually it [was there](https://github.com/bem/bem-components/commit/c4ab364347f44417bfce38f6407f11de37f0d8d6).
We decided that `label` should be implemented as element of `form` block. Here's the discussion: https://github.com/bem/bem-components/issues/538.

Then `form` was considered to be quite huge to be separated into `bem-forms` library giving higher level interface to build forms. So https://github.com/bem/bem-forms was created and some blocks (and `label` [as well](https://github.com/bem/bem-forms/tree/master/common.blocks/label)) were implemented by [community members](https://github.com/bem/bem-forms/graphs/contributors).

But core team still has no time to participate :(

**Comment by aristov** [comment]
@tadatuta says everything.
