### ISSUE TITLE
Update islands theme

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-components#1581]
- [x] ~~attach~~
- [ ] button
- [ ] checkbox, checkbox-group
- [x] ~~dropdown~~
- [ ] input
- [ ] link
- [x] ~~menu~~
- [x] ~~menu-item~~
- [x] ~~modal~~
- [ ] popup
- [x] ~~progressbar~~
- [ ] radio, radio-group
- [ ] select
- [x] ~~spin~~
- [x] ~~textarea~~

**Comment by sipayRT** [comment]
don't forget about #1484

**Comment by narqo** [comment]
Do we really want it to be 2.x minor? What if _someone_ overrides something in current `_theme_islands` (e.g. colours of the theme). We need to discuss potential damage :(

**Comment by tadatuta** [comment]
Implemented in https://github.com/bem/bem-components/pull/1771
