### ISSUE TITLE
Support BH 4.0

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-components#1587]
Should replace `blockMods` with `mods` in
common.blocks/dropdown/_switcher/dropdown_switcher_button.bh.js
common.blocks/dropdown/_switcher/dropdown_switcher_link.bh.js
common.blocks/select/__button/select__button.bh.js
common.blocks/select/__control/select__control.bh.js

**Comment by kompolom** [comment]
+1

**Comment by tadatuta** [comment]
Misha @mishanga let's discuss the way this issue can be resolved.

Now we have such options:
1. Update BH and drop backward compatibility in templates
2. Update BH and support both versions in templates with `mods || blockMods` as suggested by @zxqfox  in https://github.com/bem/bem-components/pull/1588
3. Do not update BH until `bem-components 3.0`

**Comment by qfox** [comment]
Don't go the 3rd way plx. We want to use BH4.0 with bem-components 2.x.

**Comment by mishanga** [comment]
+1 for 1

**Comment by blond** [comment]
> 1. Update BH and drop backward compatibility in templates

@tadatuta @mishanga Why do you want to ignore semver recommendations? Maybe you love to hurt users? 

Is there still reason to do stupid things?

> 1. Update BH and support both versions in templates with mods || blockMods as suggested by

Can anyone think of reasons why not to do this?

**Comment by sipayRT** [comment]
@mishanga instead of @ mishaberezin ;)

**Comment by blond** [comment]
> @mishanga instead of @ mishaberezin ;)

sorry ))

**Comment by aristov** [comment]
Don't forget to remove compatibility [workarounds](https://github.com/bem/bem-components/pull/1588) in `v3`.

**Comment by qfox** [comment]
Yeah, need to make an issue for that.
