### ISSUE TITLE
checkbox: Doesn't work in MS Edge

### ISSUE THREAD

**Issue by narqo** [bem/bem-components#1590]
Unfortunately b26d1670b9cdc73dedda37d23e5daac628a37b57 has broken the behaviour of our checkboxes, so now we have the same bug described in #1472 but in the upcoming Edge/IE11 browsers.

Note, that I've used `bem-core#v2` HEAD with bem/bem-core#1066 fixies to test.

**Comment by sipayRT** [comment]
@narqo on an extreme case we can use IE11 hack:

```
@media all and (-ms-high-contrast: none), (-ms-high-contrast: active) {
    .checkbox_theme_islands .checkbox__box
    {
        pointer-events: auto;
    }
}
```

it works fine for me

**Comment by narqo** [comment]
Does it work in the Edge? [MSDN says](https://msdn.microsoft.com/en-us/library/windows/apps/hh465764.aspx):

> As of Microsoft Edge, -ms-high-contrast: none is no longer supported

Do you now any CSS hack for iOS Safari only?

**Comment by sipayRT** [comment]
Just found mega-dirty-hack:

```
_::-webkit-full-page-media, _:future, :root .checkbox_theme_islands
{
    background: red !important;
}
```

Tested on:
- Safari for Mac 8.0.7 (Yosemite)
- iOS Simulator (version 8.0.3 and 8.0.4):
  - Safari on iPhone 4s
  - Safari om iPad Retina

Proof:
![image](https://cloud.githubusercontent.com/assets/1658415/8871057/214e79c6-31fb-11e5-9b05-831dddc9b7ea.png)

So, we can wrap `pointer-events` value under this hack

**Comment by narqo** [comment]
Well, one mega-dirty-hack is better than three ugly hacks. Let's switch to it ([this hack for Firefox](https://github.com/bem/bem-components/blob/aae2b1df3fde2a8851b145969f481bbb662e2b69/design/common.blocks/checkbox/_theme/checkbox_theme_islands.styl#L3) can be removed as well) and check that checkboxes work everywhere. Please add comment link with original issue about iOS and this one.
