### ISSUE TITLE
Use more JetBrains IDE's friendly jsdoc annotations

### ISSUE THREAD

**Issue by apsavin** [bem/bem-components#16]
According to this [issue](http://youtrack.jetbrains.com/issue/WEB-1257) in jetbrains issue tracker, it's better to use

``` javascript
/**
 * @class Button
 * @extends BEM.DOM
 */
BEM.DOM.decl('button', /** @lends Button */ {
    // Button code
}, /** @static Button */{
   //static Button methods
}
```

then @namespace, like now.
I can make a pull request with changes in jsdoc, if you agree.

**Comment by apsavin** [comment]
I think, many of you use JetBrains IDE's (WebStorm or Idea or ...). We can just change BEM.DOM declaration to this:

``` javascript
/**
 * @class BEM.DOM
 * @extends BEM
 */
var DOM = BEM.DOM = BEM.decl('i-bem__dom',/** @lends BEM.DOM */{
    /**
     * @constructs
     * @private
     * @param {jQuery} domElem DOM element that the block is created on
     * @param {Object} params Block parameters
     * @param {Boolean} [initImmediately=true]
     */
    __constructor : function(domElem, params, initImmediately) {
```

And this:

``` javascript
/** @static BEM.DOM */{

    //another static props

    /**
     *
     * @param decl
     * @param props
     * @param staticProps
     * @returns {*}
     */
    decl : function(decl, props, staticProps) {
```

And, of course, BEM declaration:

``` javascript
/** @class BEM */
var BEM = this.BEM = $.inherit($.observable, /** @lends BEM */ {
```

And then create blocks like this:

``` javascript
       /**
         * @param {Function} provide
         * @param {BEM.DOM} DOM
         */
        function (provide, DOM) {

        /**
         * @class SomeBlock
         * @extends BEM.DOM
         */
          var SomeBlock =  {/*some code here*/};
          DOM.decl('some-block', SomeBlock, {
                live: function () {
                /**
                 * @this SomeBlock
                 */
                this.liveBindTo('click', function () {
                    this.trigger('click');
                });
            }
          });
          provide(DOM);
```

And you'll see that JetBrains IDE's much smarter then you (may be) think.

It's really painful to see that IDE even can't understand, for example, setMod method. Or when it can't understand that current method is redeclaration of same-name-method of "parent class". And so on.
Don't you think it's important?
Or, may be, you are disagree with my point of view?
It will not too complex for me to change jsdocs at bem-core, bem-bl and here, at bem-controls - I'm understand, that you have not enough time.

**Comment by tadatuta** [comment]
// cc @dfilatov

**Comment by dfilatov** [comment]
Кирилл Дмитренко обещал исследовать до начала следующей недели вопрос о том, как более правильно писать jsdoc с учетом модульной системы.

**Comment by apsavin** [comment]
Круто, спасибо.
В своих проектах, в IDE я легко могу увидеть всю цепочку переопределений методов, причем в обе стороны - то есть как по направлению от класса, который переопределяет родительские методы, так и наоборот - в каких классах данный метод переопределен, легко перейти к родительскому классу или методу. В IDE от JetBrains в самом деле хорошая поддержка jsdoc - и к этому очень быстро привыкаешь. А потом открываешь BEM-проект и не можешь в один клик какой-нибудь setMod или liveBindTo открыть... 

Это я все к тому, что для меня "более правильно" - это чтобы профит от такой документации был как можно больше, а не чтобы какие-нибудь каноны соблюдались неизвестно кем и для чего выдуманные). В данном случае не вижу ничего плохого в том, чтобы взять ту же WebStorm за валидатор.

**Comment by apsavin** [comment]
Кстати, если перед trigger писать 

``` javascript
/**
 * @event
 * @name show
 */
```

То по ctrl+click по "show" в

``` javascript
block.on('show', this.someMethod)
```

можно будет перейти к триггеру (в том же WebStorm). Тоже упрощает жизнь.
@dfilatov как дела у Кирилла с его исследованием?

**Comment by apsavin** [comment]
Anybody?..

**Comment by dfilatov** [comment]
Кирилл не осилил (

**Comment by tarmolov** [comment]
// cc @dmikis

**Comment by dfilatov** [comment]
@apsavin, а ты можешь исследовать вопрос правильного написания jsdoc с учетом реалий модульной системы?

**Comment by apsavin** [comment]
@dfilatov, я уже писал выше свое мнение о том, что считаю "правильным написанием jsdoc". А вообще, есть вот такая [документация](http://usejsdoc.org/howto-commonjs-modules.html), вполне можно взять за основу.

**Comment by dfilatov** [comment]
Ты это писал, когда еще не было модульной системы. Ссылку, которую ты прислал, я конечно же видел и даже делал пробный подход, но, к сожалению, с наскоку, у меня не получилось сделать так, чтобы webstorm/idea начали "правильно" учитывать jsdoc, написанный способом из твоей ссылки.

**Comment by apsavin** [comment]
Месяц назад уже была, на самом деле.
Но ок, я еще раз попробую добавить jsdoc для bem-core, о результатах отпишусь.

**Comment by apsavin** [comment]
Добавил вот [здесь](https://github.com/apsavin/bem-core/tree/jsdoc). 
Можно склонировать, создать проект в JetBrains IDE и посмотреть, что получилось.
Лучше всего среда понимает комментарии к модулю events. 
По добавленному тестовому блоку видно, что и таких минимальных изменений достаточно, чтобы сделать разработчиков счастливее. IDE понятно, откуда берутся те или иные методы несравнимо лучше, чем, например, в версии с bem-bl.

**Comment by dfilatov** [comment]
Спасибо за пример. Но как-то оно плохо, по крайней мере у меня, работает.
Даже в случае с `events` взять твой обработчик `_onEvent(e)` -- для объекта `e` у меня IDEA подсказывает все что угодно, кроме того, что нужно.
В целом, хотелось бы достичь следующего (я не знаю, возможно ли это): есть мой модуль `test-block`, я у него в зависимостях пишу другой модуль `tick` и по клику могу перейти в код модуля `tick`. А подсказки для `tick` подсказывают мне его методы.

``` javascript
modules.define('test-block', ['tick'], function(provide, tick) {
    tick. // хотелось бы тут увидеть подсказки из этого модуля
});
```

**Comment by apsavin** [comment]
Тоже не уверен, что возможно такого добиться, но попробую.

**Comment by dfilatov** [comment]
Ну просто без этого оно как-то слишком уже мало помогает.

**Comment by apsavin** [comment]
Может быть и так, но между "помогает совсем чуть-чуть" и "совсем не помогает" я предпочитаю первый вариант. В любом случае, давайте подождем, я попробую добиться от IDE желаемого максимума.

**Comment by apsavin** [comment]
Да, у меня тоже не получилось добиться желаемого результата. Баги в трекере JetBrains ([1](http://youtrack.jetbrains.com/issue/WEB-7868),[2](http://youtrack.jetbrains.com/issue/WEB-6116),[3](http://youtrack.jetbrains.com/issue/WEB-674),[4](http://youtrack.jetbrains.com/issue/WEB-7254)) намекают, что поддержка может улучшиться в 7-ой версии WebStorm. Видимо, придется подождать и вернуться к вопросу позже.

**Comment by narqo** [comment]
Вроде уже анонсировали WebStorm 8 в начале 2014-го. Тут что-нибудь изменилось?

**Comment by apsavin** [comment]
Баги ([1](http://youtrack.jetbrains.com/issue/WEB-3574), [2](http://youtrack.jetbrains.com/issue/WEB-6116), [3](http://youtrack.jetbrains.com/issue/WEB-1257), [4](http://youtrack.jetbrains.com/issue/WEB-9086), [5](http://youtrack.jetbrains.com/issue/WEB-674)) по-прежнему не исправлены. Но я не думаю, что совсем никаких изменений нет. Выйдет восьмая версия - обязательно попробую еще раз.

**Comment by narqo** [comment]
@dfilatov @apsavin закроем за неактуальностью?

**Comment by dfilatov** [comment]
@narqo я бы закрыл

**Comment by bu1ka** [comment]
Нет никаких новостей?

**Comment by narqo** [comment]
@bu1ka оно же полтора года как закрыто — каких новостей?
