### ISSUE TITLE
Error in Webpack with bem-components-dist

### ISSUE THREAD

**Issue by andre487** [bem/bem-components#1606]
I installed bem-components via bower: `bower i bem/bem-components-dist#v2`

And using it with Webpack like this:

``` js
import '../bower_components/bem-components-dist/desktop/bem-components.css';
import '../bower_components/bem-components-dist/desktop/bem-components.dev.js+bh.js';
```

And I got an error:

```
Uncaught ReferenceError: modules is not defined
(anonymous function) @ bem-components.dev.js+bh.js:39
(anonymous function) @ bem-components.dev.js+bh.js:3096
(anonymous function) @ app.bundle.js:1247__webpack_require__ @ app.bundle.js:521fn @ app.bundle.js:76
(anonymous function) @ app.js:15
(anonymous function) @ app.bundle.js:899__webpack_require__ @ app.bundle.js:521fn @ app.bundle.js:76
(anonymous function) @ multi_app:3
(anonymous function) @ app.bundle.js:551__webpack_require__ @ app.bundle.js:521
(anonymous function) @ app.bundle.js:544
(anonymous function) @ app.bundle.js:547
```

Maybe it occurs because of exporting modules via `this` as reference to global object.

**Comment by tadatuta** [comment]
Most likely it's really so. The issue with `this` for global object was fixed at https://github.com/ymaps/modules/pull/50 and released in https://github.com/ymaps/modules/releases/tag/0.1.2

I just created an issue to update version in https://github.com/enb-make/enb-modules/issues/10

**Comment by tadatuta** [comment]
@Andre-487 can you please check it with `2.3.0` release?

**Comment by andre487** [comment]
No, error is pretty exists. You can test it using [this project](https://github.com/Andre-487/web-experiments/tree/master/bem.angular.webpack). There is [an instruction](https://github.com/Andre-487/web-experiments/tree/master/bem.angular.webpack#issue-bembem-components1606) in readme.

**Comment by andre487** [comment]
This issue has solved by adding excludes to config:

``` js
{
  test: /\.js?$/,
  exclude: /node_modules|bower_components/,
  loader: 'babel'
}
```

**Comment by tadatuta** [comment]
thank you for the tip!
