### ISSUE TITLE
Use linter for stylus

### ISSUE THREAD

**Issue by Yeti-or** [bem/bem-components#1628]
Guys did you try this https://github.com/rossPatton/stylint ?

**Comment by tadatuta** [comment]
@Yeti-or not yet, we're gonna take a look, thanks!

**Comment by sipayRT** [comment]
I just tried it. I added one rule to config for testing:
`"brackets": "always"` and got an errors while linting. This plugin tried to find open bracket on the same line with selector (open bracket on the next line will be ignored) and there is no possibility to configure it. :(

**Comment by tadatuta** [comment]
Created https://github.com/rossPatton/stylint/issues/180
