### ISSUE TITLE
enb: build is broken

### ISSUE THREAD

**Issue by aristov** [bem/bem-components#1648]
> Error: Cannot find module 'enb-bh-05x/techs/bh-server'

This error occurs on any try to execute `enb make *` or `magic server` commands.

**Comment by aristov** [comment]
cc @blond

**Comment by blond** [comment]
Hi! It seems that this is problem in `bem-components` library. 

To fix it you need perform [npm_install_other_versions.sh](https://github.com/bem/bem-components/blob/v2/npm_install_other_versions.sh) or `npm run deps`.

Maybe need to add `postinstall` script?

``` json
"scripts": {
  "postinstall": "./npm_install_other_versions.sh"
}
```

**Comment by aristov** [comment]
Thanks, the `npm run deps` command execution solves the problem.

> Maybe need to add postinstall script?

cc @tadatuta

**Comment by tadatuta** [comment]
I don't like postinstall idea as it's just dev-dependency. We can migrate to https://github.com/bem/bh-3x as soon as it's ready to solve the complexity of installation process.

**Comment by tadatuta** [comment]
Irrelevant since https://github.com/bem/bem-components/commit/e53aaeb086c1238790fc1aaf4fd10faa2cd77236
