### ISSUE TITLE
Move contributing guidelines to Contributing.md

### ISSUE THREAD

**Issue by kizu** [bem/bem-components#1669]
Github allows it to use a special `Contributing.md` file in the root of the project for all the contributing guidelines. This way Github would show a link to this file when someone opens an issue or a PR:

![image](https://cloud.githubusercontent.com/assets/177485/9799873/6f132c5a-5812-11e5-8801-26a79534e9c6.png)

Right now the contributing guidelines are [placed in Readme](https://github.com/bem/bem-components#how-to-contribute) and can be easily missed.

**Comment by tadatuta** [comment]
:+1:
