### ISSUE TITLE
"Showcase" page is blank on iOS Safari 9

### ISSUE THREAD

**Issue by narqo** [bem/bem-components#1676]
Clicking the "showcase" link from the [library page](https://en.bem.info/libs/bem-components/v2.3.0/), shows a blank page with only header of the service.

I believe it's a CSS problem as there are no errors related to JS or Network in the dev console.

<img width="733" alt="screen shot 2015-09-18 at 00 07 37" src="https://cloud.githubusercontent.com/assets/88045/9946140/0fef40b4-5d9a-11e5-8488-68b106454533.png">

The problem can be reproduced both in iOS9 Emulator in Xcode and on the real device with iOS9 installed.

**Comment by narqo** [comment]
I guess the issue should be moved to bem.info bug tracker, but I couldn't find where it is.

**Comment by tadatuta** [comment]
created task there

**Comment by narqo** [comment]
@tadatuta is it still in progress?

**Comment by tadatuta** [comment]
it was fixed
