### ISSUE TITLE
radio-group doesn't work on iOS9

### ISSUE THREAD

**Issue by narqo** [bem/bem-components#1677]
After the first click on the `radio__box` the block stops responding on future clicks. Clicks on the label are processing as expected.

Can be reproduced on current [showcase page](https://en.bem.info/__example/bem-components/v2.3.0/desktop.pages/showcase/showcase.html).

**Comment by tadatuta** [comment]
Fixed in https://github.com/bem/bem-components/releases/tag/v3.0.0
