### ISSUE TITLE
modal: close on the "Escape" keypress

### ISSUE THREAD

**Issue by aristov** [bem/bem-components#1679]
`modal` without `_autoclosable` modifier creates a trap without the ability to close it.
The "Escape" keypress must close `modal` in any case.

In addition, `modal` should contain at least one closing element on touch devices.

**Comment by dfilatov** [comment]
I can't agree with you. As application developer you should provide a right way to close such modal window. If you force to close modal using escape it might lead to unpredictable behaviour. Imagine you need to implement a quiz via modal windows.

**Comment by aristov** [comment]
> Imagine you need to implement a quiz via modal windows.

This can be implemented by the `preventDefault` method call on the event object.

> As application developer you should provide a right way to close such modal window.

At least we must describe this in docs.

**Comment by aristov** [comment]
Discussed and rejected by the core maintainers team.
