### ISSUE TITLE
Retest all blocks after the a11y improvement

### ISSUE THREAD

**Issue by aristov** [bem/bem-components#1683]
After the #1665 containing a lot of changes was merged we should retest blocks in all supported browsers.

The [showcase](https://ru.bem.info/libs/bem-components/v2.3.0/showcase/) and a new showcase created from the current `v2` may be used for comparison.

cc @tadatuta

**Comment by aristov** [comment]
cc @deeonis

**Comment by narqo** [comment]
No regressions related to a11y have been found, so [2.4.0](https://github.com/bem/bem-components/releases/tag/v2.4.0) was released.
