### ISSUE TITLE
Dropdown mechanics

### ISSUE THREAD

**Issue by awinogradov** [bem/bem-components#1692]
Давече зашел я в `dropdown`. Моему взору открылся шаблона фрагмент:

``` js
return [
    { elem : 'switcher', content : this.ctx.switcher },
    popup
];
```

Пошел я `dropdown__switcher` смотреть:

``` js
block('dropdown').elem('switcher').tag()(false);
```

Сижу теперь в раздумьях весь. Почему так? Почему `popup` прокидывается без фейкового шаблона элемента, а свитчер вот нет? Надумал и нашел еще вопрос, отчего не вот так все:

``` js
content()(function() {
    var popup = this.ctx.popup,
        switcher = this.ctx.switcher;

    if(this.isSimple(popup) || popup.block !== 'popup') {
        popup = { block: 'popup', content: popup };
    }

    var popupMods = popup.mods || (popup.mods = {});
    popupMods.theme || (popupMods.theme = this.mods.theme);
    popupMods.hasOwnProperty('autoclosable') || (popupMods.autoclosable = true);

    popupMods.target = 'anchor';

    popup.mix = this.extend(popup.mix || {}, { block: this.block, elem: 'popup' });
    switcher.mix = this.extend(switcher.mix || {}, { block: this.block, elem: 'switcher' });

    return [switcher, popup];
})
```

Далее логично посмотреть на код в `dropdown_switcher_button.js` и `dropdown_switcher_link.js`. После чего возникает вопрос почему это не один универсальный бинд на `dropdown__switcher`?

Глубинное изучение вопроса дает понять, что `dropdown` заточен на бинд БЭМ-события, что не дает сделать универсальный код. Как быть, как жить, что делать дальше? ;)

**Comment by voischev** [comment]
Ну да. Чего бы не слушать события на элементе `switcher`?

**Comment by voischev** [comment]
А еще... получается что на каждый switcher по модификатору есть live и если нужно добавить еще логику по модификатору, то на два модификатора придется копипастить весь код на все свитчеры

**Comment by dfilatov** [comment]
Свитчер дропдауна требует определенного "интерфейса" от свитчера, а именно:
- BEM-события "click". Не низкоуровневого DOM-события, а именно высокоуровневого BEM-события. Только сам нижележащий блок знает что такое click и как оно получается. И вовсе необязательно что это DOM-клик один в один. И на примере той же кнопки это можно увидеть.
- способность быть disabled путем установки соответствующего модификатора.

**Comment by awinogradov** [comment]
Но это вынуждает копипастить код для каждого типа свитчера. Зачем, если можно этого избежать?

**Comment by dfilatov** [comment]
Каким образом, учитывая эти два пункта, ты предлагаешь этого избежать?

**Comment by awinogradov** [comment]
А какие аргументы учитывать первый? Если его избежание решает проблему?

**Comment by dfilatov** [comment]
Достаточно того, что клик по кнопке, и клик по кнопке в дропдауне почему станут двумя разными, иногда несовпадающими, вещами.

**Comment by awinogradov** [comment]
@dfilatov я бы потрудился поискать `иногда`, будь в моих интересах пояснить свое решение.

**Comment by dfilatov** [comment]
@awinogradov Я не понял смысла твоего предложения.

**Comment by awinogradov** [comment]
Я говорю, что хотелось бы более развернутое пояснение. С чего вдруг клик по кнопке не станет таковым в дропдауне и когда это такое иногда произошло.

**Comment by dfilatov** [comment]
Посмотри код в кнопке, там видно, как получается bem-событие click.

**Comment by awinogradov** [comment]
Ясно, спасибо за пояснение. Подождем еще. Даже если учесть что кнопка что-то по особенному умеет, то умеет она это ровно так как умеет control, впрочем как и link, ибо она не нем основана. Я повторю свой вопрос: правда надо копипастить код для всех типов свитчеров, если требуемая от них функциональность заложена в одном базовом блоке?

**Comment by awinogradov** [comment]
Почему просто не подумать над этим? Что за нападки?

**Comment by awinogradov** [comment]
В общем меня не это интересовало в первую очередь.

**Comment by dfilatov** [comment]
Я не понимаю, почему ты считаешь что она одинаковая, когда по факту она разная и зависит от типа свитчера. Да, при этом там есть и похожие куски. Но их количеством, на мой взгляд, можно пренебречь в угоду консистентности.

Ps. Я вроде не нападал. Извини, если что.

**Comment by awinogradov** [comment]
Пока их 2 как в либе то можно, конечно. Но мне вот понадобилось сделать еще и на иконку. Оборочивать в ссылку мне ее не нужно. А еще хочется чтобы dropdown умел по ховеру и фокусу открываться в зависимости от модификатора. Этому очень сильно мешает код либы. Оттуда и вопросы.

**Comment by awinogradov** [comment]
Завтра я вот буду делать на инпут) И шо тогда? Выглядит не очень. Хочется по красивей.

**Comment by dfilatov** [comment]
Ну конкретно для твоего случая — иконку в кнопку с view=plain. Это даже логичнее и правильнее.

**Comment by dfilatov** [comment]
> А еще хочется чтобы dropdown умел по ховеру и фокусу открываться в зависимости от модификатора.

Каким образом мешает? И как бы перестал мешать, если бы там был dom-клик?

**Comment by awinogradov** [comment]
Если ты заглянешь в код свитчеров, то увидишь зависимость от бем события клика. Хотя если бы событие слушалось на элементе дромадера, а не конкретном блоке, то это можно было бы регулировать параметром. Без дубляжа кода. А так мне надо для каждого свитском ещё и все виды событий описать.

**Comment by dfilatov** [comment]
К сожалению, сейчас нет возможности в bem-core слушать BEM-события от любого блока (без знания его имени) на DOM-элементе.

**Comment by voischev** [comment]
@dfilatov я не понял чем тут обосновывается бэм событие? Почему не дом?

**Comment by dfilatov** [comment]
@voischev Я же вроде написал выше про это.

**Comment by voischev** [comment]
@dfilatov так не понятно же написал. Я не понял чем это обосновано

**Comment by awinogradov** [comment]
Поэтому я и предложил DOM. И все ещё не вижу проблем. Можно биндиться на них от элемента внутри дропдауна и создавать БЭМ событие если надо. Но тогда зависимость от типа свитчеров уйдёт.

**Comment by dfilatov** [comment]
> так не понятно же написал. Я не понял чем это обосновано

Тем что DOM-событие клика и BEM-событие клика не равны между собой. Только тот блок, который отвечает за свитчер в дропдауне, знает что такое клик и как он получается, и на примере внутреннего устройства кнопки видно это.

cc @veged @narqo

**Comment by narqo** [comment]
Я не понял о чем это обсуждение, почему нельзя в дропдауне слушать DOM-клик, вместо БЭМ-клика? Потому что DOM-клик не учитывает внутренние состояния контрола на котором вызывается событие (например `_disabled`); потому что БЭМ-click правильно учитывает работу с клавиатуры (keyup пробела, если кнопка была в фокусе, вызывает клик, неважно, сколько  миллисекунд прошло с момента keydown); потому что DOM-клик не сработает для псевдо-ссылки / псевдо-кнопки реализованной через `<span>` при работе с клавиатуры (искусственный клик работает только для `<a>`). Потому что DOM-`click` до сих пор плохо работает на важных нам тач-устройствах (а `fastclick`, на самом деле, создает еще больше проблем).

Список можно продолжить, но, непонятно, зачем про эти особенности реализации БЭМ-события `click` в конкретном типе свитчера знать человеку, который занимается `dropdown`'ом. Это обычное разделение ответственностей через «высоуровневые интерфейсы». «_Я мейтейнер дропдауна, я не хочу ~~ничего решать~~ чинить баги связанные с работой DOM-событий в твоей реализации кнопки — я хочу чтобы контрол кидал событие БЭМ-`click`, когда ты определишься, что уже можно_» :D

И да, все эти «особенности» можно учесть на уровне `dropdown__switcher`, скопипастив код из кнопки/сслыки, а потом тоже самое сделать во всех местах, где используется эти блоки (например в `select`). Вопрос в том, зачем менять копипаст в одном месте + четкое разграничение «внутренняя реализация — внешнее консистентное API», на копипаст в других местах.

**Comment by dfilatov** [comment]
@narqo :+1:

**Comment by awinogradov** [comment]
Ой все!) А c миксами и шаблоном что не так? Почему фейки с фальшивым тегом?

**Comment by narqo** [comment]
> А c миксами и шаблоном что не так? Почему фейки с фальшивым тегом?

Раскрой, пожалуйста, вопрос: я не все еще не понимаю, что мы пытаемся исправить?

**Comment by awinogradov** [comment]
Не исправить) Улучшить.Три первых абзаца к посту;)

**Comment by narqo** [comment]
> Три первых абзаца к посту.

В [HEAD-версии блока](https://github.com/bem/bem-components/tree/5615a1dcfc1383976c81d414b89abace8a70e2d3/common.blocks/dropdown) (кажется, после #1393) уже нет кода шаблонов про который говоришь в самом начале.

**Comment by voischev** [comment]
@awinogradov так мы решили проблему с модификаторами?

**Comment by awinogradov** [comment]
Получается, что либо лайв и копипаст, либо без лайва и можно нормально чекать значение модификатора, что уберет копипаст.
