### ISSUE TITLE
Не могу получить событие change от select

### ISSUE THREAD

**Issue by just-boris** [bem/bem-components#1693]
У меня есть такой код: http://jsfiddle.net/z1cLLt4w/
На скрытом инпуте событие change не триггерится. Как мне узнать об изменении значения?

**Comment by Guria** [comment]
А чем не устраивает БЭМ событие на самом блоке?

**Comment by Guria** [comment]
http://jsfiddle.net/z1cLLt4w/1/

**Comment by dfilatov** [comment]
@Guria там не совсем корректный код, не надо `.bem('select')` вызывать на `.form`, надо на самой ноде селекта вызывать.

**Comment by just-boris** [comment]
@dfilatov обновил код. Так лучше? http://jsfiddle.net/z1cLLt4w/2/
@Guria всем устраивает. Я не знал, что так можно.

**Comment by dfilatov** [comment]
@just-boris Там еще `val : [2, 3]` неправильно передается. Для mode=radio-check он не может быть array.

**Comment by just-boris** [comment]
Все оказалось сложнее. Вокруг есть еще Backbone.View. У них есть декларативная подписка на события:

```
events: {
  'change .select__control': 'onSelectChange'
},
```

И она не работает. Есть ли какой-нибудь рекомендованный способ интеграции с Backbone?
Обновленный пример вот: http://jsfiddle.net/z1cLLt4w/4/

**Comment by Guria** [comment]
Значит декларативный способ из коробки не получится использовать. Придётся делать свой метод для Backbone.View который будет знать про БЭМ. А пока можно написать в императивном виде: http://jsfiddle.net/z1cLLt4w/6/

**Comment by just-boris** [comment]
@Guria да, так и придется сделать. Только лучше код подписки положить внутрь компонента, чтобы после render все работало: http://jsfiddle.net/z1cLLt4w/7/

@dfilatov а можно оставить хотелку о срабатывании dom-событий для совместимости bem-components с другими фреймворками? Нужно [здесь](https://github.com/bem/bem-components/blob/v2/common.blocks/select/_mode/select_mode_radio-check.js#L28) добавить ручное срабатывание change:

```
  control.val(val).trigger('change');
```

[Ответ об этом на Stackoverflow](http://stackoverflow.com/questions/6533087/jquery-detect-value-change-on-hidden-input-field)

Могу прислать PR с этим, если ок

**Comment by dfilatov** [comment]
@just-boris Это невозможно сделать для всех случаев, в том же селекте для модификатора mode=check создается куча внутренних скрытых инпутов, и ты в принципе не сможешь подписаться на какое-либо DOM-событие.

**Comment by voischev** [comment]
@just-boris ты используешь либу как dist? можно допределить селект что бы было еще и дом событие

**Comment by just-boris** [comment]
@dfilatov я думал об этом. Поэтому мне нравится вариант в Лего. У них вместо скрытого input используется select. Для mode=check может использоваться select multiple.
Еще как вариант можно триггерить событие change прямо на ноде .select, но это несемантично.

**Comment by just-boris** [comment]
@voischev, да, как dist. Если это можно сделать в рамках [нашего fiddle](http://jsfiddle.net/z1cLLt4w/7/),  то мне подойдет

**Comment by Guria** [comment]
http://jsfiddle.net/z1cLLt4w/9/

**Comment by voischev** [comment]
@Guria опередил)

**Comment by just-boris** [comment]
@Guria, @voischev, ясно, спасибо

Но вопрос про то, сделать ли pull-request, чтобы работало для всех, остается в силе

**Comment by Guria** [comment]
@just-boris врядли ментейнеры согласятся вносить изменения для всех, которые нужны не всем. Вы можете довольно не хитрым способом наладить свою dist сборку таких модифицированных блоков.

**Comment by voischev** [comment]
@just-boris а еще практика показывает что за счет переопределения на своем уровне можно достаточно спокойно жить со своими костылями :)

**Comment by dfilatov** [comment]
Конечно же, таким костылям, работающим в части случаев, не место в общей библиотеке. Что касается именно данной проблемы, то правильным решением здесь бы было разобраться и запилить в backbone плагин/аддон/вотэвер с возможностью биндиться к bem-компонентам.

**Comment by just-boris** [comment]
@dfilatov я предлагаю в любом mode сохранять значение в тег `<select />`. Не вижу в чем здесь костыльность, потому что во-первых тег select для этого и предназначен, во-вторых, так уже сделали в _другой популярной библиотеке bem-блоков_, и всех это устраивает

**Comment by dfilatov** [comment]
@just-boris Ну а событие-то откуда возьмется? Даже если допустить что здесь так можно было бы сделать (наверное), то, в bem-components есть контролы, аналога которых в DOM вообще нет, тот же checkbox-group или menu. Там на чем триггерить событие change?  Нельзя в библиотеке в одном месте впилить какой-то костыль. Кроме того, есть BEM-события, аналога которых в DOM нет. Для этого и были придуманы bеm-абстракции, чтобы поменьше на DOM завязываться.

**Comment by just-boris** [comment]
Посмотрел откуда берется событие в других кастомных селектах. Его везде триггерят сами в коде библиотеки, в том числе и в Лего.

И это хорошо, поскольку позволяет другим компонентам думать, что перед ними обычный select и не думать о его деталях реализации. Это важно, когда компоненты используются лишь как компоненты и не объединены общим БЭМ-фреймворком

**Comment by just-boris** [comment]
А можно делегировать БЭМ-события?

Главное преимущество нативных событий, что BackboneView слушает их делегированно на основном элементе. Это позволяет перерендерить компонент много раз, а слушатели слетать не будут

**Comment by dfilatov** [comment]
Если это библиотека одного селекта, то да, так допустимо делать. В рамках же библиотеки блоков поведение всех ее составляющих должно быть консистентным.

По поводу делегации: через делегирование BEM-события вложенных блоков можно слушать в пределах какого-нибудь DOM-контейнера (https://ru.bem.info/technology/i-bem/v2/i-bem-js-events/#%D0%94%D0%B5%D0%BB%D0%B5%D0%B3%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%91%D0%AD%D0%9C-%D1%81%D0%BE%D0%B1%D1%8B%D1%82%D0%B8%D0%B9).

``` js
Select.on(domElem, 'change', function(e) { console.log(e.target.getVal()); });
```

**Comment by just-boris** [comment]
> Если это библиотека одного селекта, то да, так допустимо делать. В рамках же библиотеки блоков поведение всех ее составляющих должно быть консистентным.

Можно добиться консистентности, если сделать то же самое для input, checkbox, и radio. Это не кажется сложным

За делегацию спасибо, вышло неплохо
http://jsfiddle.net/z1cLLt4w/11/

**Comment by narqo** [comment]
> [..] так уже сделали в другой популярной библиотеке bem-блоков, и всех это устраивает

@just-boris могу добавить, как человек, ответсвенный за нативный селект во _внутренней библиотеки_ (_оригинальному селекту почти 4 года и годы тот код не красят_), что его наличие приносило и продолжает приносить очень много проблем как мейнтейнерам, так и пользователям.

**Comment by just-boris** [comment]
@narqo а можно рассказать пример проблемы? Может я не в курсе, что меня в будущем ждет

**Comment by narqo** [comment]
@just-boris _ниже получился длинный рассказ (sorry), основанный на реальных событиях «внутри»_

> а можно рассказать пример проблемы

Самая большая проблема, про которую помню: некоторые браузеры «кешируют» выбранные в селекте пункты. Если пользователь что-то выбрал, а потом перезагрузил страницу, в селекте можно получить рассинхрон состояний (в нативном контроле выбран пункт оставшийся до перезагрузки, а на кнопке указано, что выбран пункт пришедший с сервера). Никаких DOM-событий при этом не происходит и отключение `autocomplete` у контрола не помогает. 

Чтобы победить проблему, пришлось отказаться от ленивой инициализации, и принудительно синхронизировать надпись на кнопке с выбранным по факту пунктом. 

Дополнительно, если внешняя форма должна как-то среагировать на изменение в селекте (например, разблокировать кнопку отправки формы, если что-то выбрано), никакой реакции не произойдет, потому что DOM-события, на которое подписался разработчик формы, не порождается. Приходится, вместе с синхронизацией надписи на кнопке, «руками» тригерить DOM-событие в селекте.

**Comment by just-boris** [comment]
@narqo спасибо за рассказ.

А как тогда вы боролись с автокомплитом в текстовом input?

**Comment by just-boris** [comment]
Сейчас по очереди попробовал input, textarea, checkbox-group и radio-group. Все они декорируют соотвествующий нативный контрол и я могу подписаться на его change. 

Получается, что select особый, только на него я не могу подписаться

**Comment by dfilatov** [comment]
От какого нативного контрола ты слушаешь change у checkbox-group? Под ним лежит несколько чекбоксов и bem-контрол собирает с них правильное значение.

**Comment by dfilatov** [comment]
@just-boris С автокомплитом текстовых полей у нас борется поллинг.

**Comment by just-boris** [comment]
@dfilatov вот такой у меня сценарий использования checkbox-group: http://jsfiddle.net/z1cLLt4w/13/

**Comment by dfilatov** [comment]
@just-boris Ну это очень своеобразное использование чекбокс-группы. В bem-components это одно поле с множественным значением в виде массива, а не группа разных чекбоксов.

**Comment by just-boris** [comment]
Финальное решение получилось такое:

```
modules.define('select', function(provide, Select) {
    provide(Select.decl({
        _onMenuChange : function() {
            this.__base.apply(this, arguments);
            this.findElem('control').trigger('change');
        }
    }));
});
```

Я сам доопределяю событие и получаю нужное мне поведение. Fiddle: http://jsfiddle.net/z1cLLt4w/15/

Пока работает норм. Когда наберу побольше опыта эксплуатации такого решения и соберу больше граблей, могу написать об этом какой-нибудь пост.

Всем спасибо за ответы!
