### ISSUE TITLE
Feedback for "Блок events"

### ISSUE THREAD

**Issue by bu1ka** [bem/bem-components#1698]
[тут](https://ru.bem.info/libs/bem-core/v2.8.0/desktop/events/#Элементы-блока) и [тут](https://ru.bem.info/libs/bem-core/v2.8.0/desktop/events/#Функции-предоставляемые-элементами-блока) битые ссылки на [Элемент-channels-блока-events](https://ru.bem.info/libs/bem-core/v2.8.0/desktop/events/#Элемент-channels-блока-events)

**Comment by tadatuta** [comment]
`#Элемент-channels-блока-events`
