### ISSUE TITLE
Unable to mark input as required

### ISSUE THREAD

**Issue by just-boris** [bem/bem-components#1700]
I am using bem-components from the [dist build](https://github.com/bem/bem-components-dist).

Now I am wondering how to add `required` attribute to `<input />` tag to prevent undesired submits of empty form.

As I found in [the source code](https://github.com/bem/bem-components/blob/v2/common.blocks/input/__control/input__control.bh.js#L7-L14) there is a fixed set of attributes passed to the tag. Is there an ability to make this set extendable or add `required` option here?

**Comment by tadatuta** [comment]
We treat all available fields in BEMJSON as a garanteed API for all supported browsers and as `required` is not implemented in IE 9 we intentionally ommited it.

To use it you should write something like

``` js
block('input').elem('control').attrs()(function() {
    return this.extend(applyNext(), { required: this.ctx.required });
});
```

**Comment by just-boris** [comment]
@tadatuta as far as I know, dist-build already has compiled templates and I can't override them.

In other words, how can I override input template in the jsfiddle: http://jsfiddle.net/r0Laywmf/ ?

**Comment by qfox** [comment]
You loading bh.js, using BEMHTML variable and talking about compilation. Stop blowing our minds please. BH bulding matchers function at run time and that means you can easily append your own matchers to it and they will be recompiled/rebuilt. Just do it! Nothing stops you except yourself.

http://jsfiddle.net/kch0Lqq9/

**Comment by just-boris** [comment]
@tadatuta I got the point, but there is more:
1. This required attributes behaviour can be polyfilled. It is easier to make when required inputs has the corresponding semantic attribute.
2. It provides better accessibility for forms: [article on MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-required_attribute) and [one another](http://john.foliot.ca/required-inputs/)

@zxqfox sorry, I just brought this code from the [documentation](https://github.com/bem/bem-components/blob/v2.3.0/README.ru.md#Установка-с-помощью-bower). Anyway, thanks for the clue. Finally I came up with the following solution: http://jsfiddle.net/kch0Lqq9/1/

**Comment by narqo** [comment]
Looks like the solution was found.

**Comment by just-boris** [comment]
@narqo one question wasn't answered: if you care about accessibility, why you don't consider using `aria-required` attribute? At least for it, you should use that modifier.

**Comment by narqo** [comment]
@just-boris in https://github.com/bem/bem-components/issues/1700#issuecomment-152587554 above there is a workaround for adding attributes to the block. As far as I know current bem-xjst allows to add templates in the runtime, so it should work for dist as well.

As for adding the property to the templates to the library level, we don't plan to extend current API of the templates if this new API doesn't work natively in all supported browsers. We may consider to change the list of supported browsers in future.

**Comment by just-boris** [comment]
It is not a question whether can it be worked around or not, it is about consistency. Now I am talking about native `aria-required` support. Some aria-attributes are supported, but this one is ignored.

Browser support doesn't matter here. If some browser can't validate required fields, why we can't add a hint for screen readers, which fields are necessary to fill?
