### ISSUE TITLE
checkbox, radio-group: not react on second tap

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-components#1707]
`checkbox` and `radio-group` (e.g. on `touch.tests/checkbox/simple/simple.html`, `touch.tests/checkbox-group/simple/simple.html` or `touch.tests/radio-group/simple/simple.html`) do not react on second tap on any touch device on any OS: https://yadi.sk/i/pAL4RzaujtZrb

**Comment by narqo** [comment]
Possibly related to bem/bem-core#1088

**Comment by tadatuta** [comment]
Fixed in https://github.com/bem/bem-components/releases/tag/v3.0.0
