### ISSUE TITLE
modal: Zoom on Safari on iOS9.0.2

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-components#1708]
On `desktop.tests/modal/simple/simple.html` (the issue only exists on `desktop` bundle on iPad, touch bundle is fine) on iOS9.0.2 (iOS8 works fine) on Safari (other browsers work fine) openning modal increases  zoom: https://yadi.sk/i/OngicV1LjtVNd

**Comment by veged** [comment]
Investigations show us that this behaviour depends on `.page_hide-scroll { overflow: hidden; }`. Without this style there is no auto zoom. Zoom appear exactly in moment when body gains `overflow: hidden` (no matter how exactly).

Have no idea for now how can we fix it :-(

**Comment by veged** [comment]
WebKit bug exactly about this: https://bugs.webkit.org/show_bug.cgi?id=150715

**Comment by veged** [comment]
this fix our examples

``` diff
--- common.blocks/modal/modal.tests/simple.blocks/test/test.styl
+++ common.blocks/modal/modal.tests/simple.blocks/test/test.styl
@@ -11,4 +11,5 @@

 .page_hide-scroll {
     overflow: hidden;
+    min-height: 100vh;
 }
```

but not sure about other cases

since it only reproduces when body is short — let's assume that this is enough
