### ISSUE TITLE
Border does not appear for autofilled inputs

### ISSUE THREAD

**Issue by just-boris** [bem/bem-components#1710]
Chrome and other Blink-based browsers highlight inputs which was filled automatically. (Usually this is for login forms).

Input block in that case loses their border:
![image](https://cloud.githubusercontent.com/assets/812240/11144614/03a67cae-8a0f-11e5-81be-d328c36c47c5.png)

Maybe this is an expected behavior but it does not look nice.

**Comment by narqo** [comment]
Thanks for report, I'll ask our designers if such behaviour acceptable.

**Comment by narqo** [comment]
It's time to introduce a label «**it'd be cool if you PR**»
