### ISSUE TITLE
В чем разница checkbox_type_button и button_togglable_check?

### ISSUE THREAD

**Issue by just-boris** [bem/bem-components#1737]
Насколько я понял, в результате я и там, и там получаю кнопку, которая выделяется при клике. Еще я заметил, что checkbox генерирует `<input />`, а button – нет.

Так зачем нужны два варианта одного и того же?

**Comment by just-boris** [comment]
А еще у button_toggleable рисуется двойной border:

![image](https://cloud.githubusercontent.com/assets/812240/12051676/b9d6ba5c-af17-11e5-884e-24e43fdedd48.png)

Checkbox так не делает

**Comment by awinogradov** [comment]
@just-boris https://github.com/bem/bem-components/issues/1685 может помочь с ответом

**Comment by tadatuta** [comment]
@just-boris 
Баг с бордером был исправлен в https://github.com/bem/bem-components/commit/8718599227bd2e81d3e9172e56d4f05c9a1f48f2

По поводу разницы ответ Антона помог? Можем закрывать?

**Comment by just-boris** [comment]
В тикете идет обсуждение нюансов API.

У меня был вопрос, зачем нужны два блока, которые выглядят и ведут себя одинаково.

**Comment by veged** [comment]
checkbox_type_button сделан через button_togglable_check и обладает дополнительной функциональностью про `<input>` которая позволяет использовать его на формах как поле со значением
