### ISSUE TITLE
Incorrect behaviour of "Checkbox" on mobile devices

### ISSUE THREAD

**Issue by ocopant** [bem/bem-components#1738]
Open this link https://ru.bem.info/libs/bem-components/v2.4.0/touch/checkbox/ from mobile browser
and try to check/uncheck "Checkbox".
You need to tap several times for this action. Also tap on text doesn't work.

I expect that I need only one tap to check or uncheck "Checkbox"

I can reproduce on
Android 5.1.1 Ya.Browser 15.12
Android 5.1.1 Chrome 47
Android 4.4.2 Chrome 47
![2016-01-11_15-22-54](https://cloud.githubusercontent.com/assets/8094249/12233320/5732b5d6-b877-11e5-9381-375c396e3311.png)

**Comment by dfilatov** [comment]
Seems that it duplicates #1707

**Comment by tadatuta** [comment]
Related internal ticket: https://nda.ya.ru/3RRuAs

**Comment by tadatuta** [comment]
Yet another internal ticket: https://nda.ya.ru/3RT63h
video: https://yadi.sk/i/pRy8B4Y-jtTUH

**Comment by tadatuta** [comment]
Fixed in https://github.com/bem/bem-components/releases/tag/v3.0.0
