### ISSUE TITLE
checkbox-group without check mark on FF 43

### ISSUE THREAD

**Issue by alexeimoisseev** [bem/bem-components#1739]
On page https://ru.bem.info/libs/bem-components/v2/desktop/checkbox-group/ no check mark when checkbox checked.

https://yadi.sk/i/lsNj4jw9mqD6k

Firefox 43.0.4
MacOS 10.11.2

**Comment by tadatuta** [comment]
Thank you for report, you may use https://ru.bem.info/libs/bem-components/v2.4.0/desktop/checkbox/ until we fix `v2`.

**Comment by tadatuta** [comment]
Closing issue here in favour of task for bem.info
