### ISSUE TITLE
control-group: Wrong styling for dropdown

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-components#1741]
Since `dropdown` is two DOM nodes now (trigger + popup) `last-child` selector works wrong:
http://i.imgur.com/DAMqGDb.png

**Comment by narqo** [comment]
Looks like this is a degradation after #1392.

**Comment by veged** [comment]
@tadatuta can it be fixed in CSS or it's better to rollback #1392

**Comment by tadatuta** [comment]
it can with several selectors with `:last-of-type`

**Comment by veged** [comment]
ok, so keep it _[ready]_

**Comment by narqo** [comment]
@tadatuta @gela-d any estimates here?
