### ISSUE TITLE
gemini: Move windowSize property to browser config level

### ISSUE THREAD

**Issue by gela-d** [bem/bem-components#1757]
Because of bug in Gemini top level property windowSize does't work,
Correct type:

```
browsers:
  ie11:
    windowSize: 1280x920
```

In this issue gemini screenshots shoul be re-screened.

**Comment by tadatuta** [comment]
If we need to update screenshots anyway, let's also update `gemini` to latest version as well.
And wait for solution from @just-boris to get rid of SauceLabs.

**Comment by sipayRT** [comment]
@tadatuta you don't need update screenshots to update `gemini`.

**Comment by tadatuta** [comment]
irrelevant after `gemini` update
