### ISSUE TITLE
Publish version with precompiled CSS

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-components#1758]
Now we force users of `bem-components` to use `Stylus` in their projects.
But quite often they use some other pre/postprocessor or just plain CSS.
For them it's just useless dependency, config complication and slowdown of build pipeline.

And even for people who use Stylus there's no profit of having our source in Stylus.

So @zxqfox proposed to release `bem-components` with already compiled CSS.

I like this idea and now we have theree options:
1. Keep everything as is.
2. Compile CSS and publish versions with both files (`button.styl` and `button.css`).
3. Compile CSS and publish with just CSS.

I vote for 3 and even think that becouse of the way `enb-stylus` works it's a minor update.

// cc @veged @narqo @blond @vithar

**Comment by veged** [comment]
since we have no any helpers for Stylus which are can be used inside user styles I think we can omit 2 and do 3

**Comment by voischev** [comment]
:fire:

**Comment by awinogradov** [comment]
You can publish with npm and use postinstall for precompile or publish precompiled ;) npm package is good because we can export some meta for builder such as levels and techs.

**Comment by tadatuta** [comment]
@awinogradov we can discuss publication to `npm` as a separate task as we need `bower` package anyway.

**Comment by tadatuta** [comment]
https://github.com/bem/bem-components/releases/tag/v3.0.0 was published with precompiled CSS.
