### ISSUE TITLE
radio: Possibility to combine blocks by names

### ISSUE THREAD

**Issue by gela-d** [bem/bem-components#1759]
In html-word we have possibility to use two separate `<input type="radio"` with identical name combined  two radio-buttons in different places of the page.
![1](https://cloud.githubusercontent.com/assets/1333220/13397552/89432de8-df0b-11e5-8586-27135577cc99.png)
![2](https://cloud.githubusercontent.com/assets/1333220/13397564/98f7d266-df0b-11e5-8a26-0e20d5c72c77.png)

But, if I combine two radio-buttons from bem-components, they do not want to be combined, even though they have the same names.
![3](https://cloud.githubusercontent.com/assets/1333220/13397639/e9c375c4-df0b-11e5-94b1-3a63825ac1cd.png)
![4](https://cloud.githubusercontent.com/assets/1333220/13397704/295811ae-df0c-11e5-9a33-6a0cab547677.png)

This feature is very important to use block `radio` in such structures as tables, when we haven't posibility to use block `radio-group`.
![6](https://cloud.githubusercontent.com/assets/1333220/13397922/108dbb8c-df0d-11e5-8a2c-5a4ac57f1a79.png)

**Comment by dfilatov** [comment]
You have to use the same js parameter `id` for this case.

**Comment by gela-d** [comment]
> You have to use the same js parameter id for this case.

If I understand correctly, I shall use this entry:

```
{
    block : 'radio',
    mods : { theme : 'islands', size : 'm' },
    name : 'radio-islands',
    js: { id: 123 },
    val : 'BEMHTML',
    text : 'Использовать BEMHTML-1'
},
{
    block : 'radio',
    mods : { theme : 'islands', size : 'm' },
    name : 'radio-islands',
    js: { id: 123 },
    val : 'BEMHTML',
    text : 'Использовать BEMHTML-2'
}
```

?
If this entry correct - it doesn't work, both of radio checked simultaneously
![11](https://cloud.githubusercontent.com/assets/1333220/13398414/376ecb18-df0f-11e5-87ff-dbaac21b878a.png)

**Comment by dfilatov** [comment]
Oh. You mustn't use `radio` without `radio-group`.

**Comment by gela-d** [comment]
Yes, this is my problem - to use radio in table, where I haven't possibility to use radio-group.

**Comment by dfilatov** [comment]
It's not a problem, just use `radio-group`s (with the same `id`) instead of `radio`s.

**Comment by gela-d** [comment]
Thanks, it works, but I still think that posiibility to use this:

``` js
{
    block : 'radio',
    mods : { theme : 'islands', size : 'm' },
    name : '123',
    text : 'first'
},
{
    block : 'radio',
    mods : { theme : 'islands', size : 'm' },
    name : '123',
    text : 'second'
}
```

is better than

``` js
{
    block : 'radio-group',
    mods : { theme : 'islands', size : 'm' },
    js: { id: 123 },
    options : [
        { val : 1, text : 'first' }
    ]
},
{
    block : 'radio-group',
    mods : { theme : 'islands', size : 'm' },
    js: { id: 123 },
    options : [
        { val : 2, text : 'second' }
    ]
}
```

**Comment by dfilatov** [comment]
`radio` isn't supposed to be used without `radio-group`.

**Comment by gela-d** [comment]
Dima, thanks for answers.

**Comment by tadatuta** [comment]
Let's discuss it a bit more.

We claim that `bem-components` provide blocks which work the same way as native.
Shouldn't we keep this task as improvement for `radio` to work independently?

**Comment by gela-d** [comment]
By the way, i have some problem with `radio-group`.
I use two `radio-group` with one option and one ID in bemjson.
Then, I add one more `radio-group` width the same ID from javascript `BEMHTML.apply({})`. In html I see that all of three blocks have identical ID, but two of them (from bemjson) works together, and third, from js, hasn't connected to them.

**Comment by dfilatov** [comment]
@gela-d blocks are joined during initialization. You can't add another part after.

**Comment by dfilatov** [comment]
> We claim that bem-components provide blocks which work the same way as native.

It can't be true. We already have blocks and behaviours which don't have corresponding ones in html.

**Comment by tadatuta** [comment]
> It can't be true. We already have blocks and behaviours which don't have corresponding ones in html.

I meant «not worse than native».

**Comment by tadatuta** [comment]
Suggested solution:

``` js
_onChange : function(e) {
        var blockName = this.__self.getName(),
            selector = this.buildSelector(),
            controlSelector = this.buildSelector('control'),
            control = e.currentTarget,
            name = this.getName(),
            isChecked = control.attr('checked');

        $(controlSelector + '[name=' + name + ']')
            .parents(selector)
            .each(function() {
                $(this).bem(blockName).delMod('checked');
            });

        this.setMod('checked', !isChecked);
    }
```

**Comment by dfilatov** [comment]
I don't like the idea to use global selectors just to support this edgecase.

**Comment by tadatuta** [comment]
Maybe we can implement it as a modifier?

**Comment by narqo** [comment]
Can't such modifier be implemented on the project level first? We could backport it to the library if the case'd be seen more often.
