### ISSUE TITLE
Popup_target_anchor: возможность сохранять блок при удалении anchor

### ISSUE THREAD

**Issue by aliosv** [bem/bem-components#1765]
Пример: todo list с одним попапом(автокомплит) для всех инпутов. 
input.onFocus -> popup.setAnchor
input.destruct -> popup.destruct - не айс
Метод delAnchor или флаг noDestruct позволили бы избежать хаков.

**Comment by narqo** [comment]
Мы у себя на одном проекте решали похожую задачу, «перевешия» `popup` на перманентный анкор, который (почти) никогда из DOM не удаляется. В вашем примере, это будет
дополнительный шаг «input.onBlur → popup.setAnchor(permanentAnchor)».

Решение, про отвязку `popup` от анкора накладывает дополнительные обязательства: нужно руками удалять/строить `popup` в ситуации, когда происходит полный перерендер (основного содержимого) страницы. Пока, кажется, что это слишком advanced-фича, от которой больше проблем, чем пользы.

**Comment by aliosv** [comment]
> нужно руками удалять/строить popup в ситуации, когда происходит полный перерендер (основного содержимого) страницы

поясни пожалуйста

**Comment by narqo** [comment]
> поясни пожалуйста

Представь, что твоя страница с TODO-листом, это всего лишь одна из «страниц» сложного SPA. После перехода вперед-назад по «страницам», «мусорные» попапы будут копиться в дереве. На больших приложениях, в которых пользователь проводит N часов (дней), все это приводит к текущей памяти :(
