### ISSUE TITLE
Вложенные menu

### ISSUE THREAD

**Issue by aliosv** [bem/bem-components#1766]
Планируете реализовать? Пример - многоуровневая навигация.

**Comment by awinogradov** [comment]
@aliosv а чем не подходит `menu->menu-item->dropdown->menu->menu-item->dropdown`?

**Comment by aliosv** [comment]
@awinogradov, popup'ами

**Comment by awinogradov** [comment]
разверни мысль немного подробнее? Что ты хочешь?

**Comment by aliosv** [comment]
древовидное многоуровневое меню

![screenshot 1](https://cloud.githubusercontent.com/assets/2275425/13724412/96fcd660-e88d-11e5-97b1-d58868acd093.png)

**Comment by awinogradov** [comment]
Ок;) Чем не подходит  `menu->menu-item->menu->menu-item`?

UPD: можно добавить `menu-item_collapsed` и сворачивать когда надо и не надо.

**Comment by aliosv** [comment]
Именно так и хотелось бы, но не работает: верхнее меню найдет все вложенные menu-item и сломается.

**Comment by awinogradov** [comment]
Что сломается?

**Comment by aliosv** [comment]
клик на вложенном item снимает checked на его родителе

```
1. checked
  a.
  b.
```

клик на "a" сделает

```
1.
  a.checked
  b.
```

а хочется

```
1. checked
  a.checked
  b.
```

**Comment by tadatuta** [comment]
@aliosv Древовидное многоуровневое меню вполне можно сделать на основе существующего `menu` и просто не использовать `mode`:

``` css
.menu_hidden {
    display: none;
}
```

``` js
modules.define('menu-item', ['i-bem__dom'], function(provide, BEMDOM) {

provide(BEMDOM.decl(this.name, {
    onSetMod: {
        js: {
            inited: function() {
                this.on('click', function() {
                    this.findBlockInside('menu').toggleMod('hidden');
                });
            }
        }
    }
}));

});
```
