### ISSUE TITLE
Fail on dropdown.bh.js in absence of “switcher”

### ISSUE THREAD

**Issue by GreLI** [bem/bem-components#1770]
If `switcher` key is absent in BEMJSON, [dropdown.bh.js](https://github.com/bem/bem-components/blob/v2.4.0/common.blocks/dropdown/dropdown.bh.js#L13) fails on lines [13](https://github.com/bem/bem-components/blob/v2.4.0/common.blocks/dropdown/dropdown.bh.js#L13) and [44](https://github.com/bem/bem-components/blob/v2.4.0/common.blocks/dropdown/dropdown.bh.js#L44) with error messages like “Cannot read property "mix" of undefined”.

**Comment by narqo** [comment]
I believe, the only relevant solution currently is to add a note to docs that particular fields are required. See relevant issue #1576.

**Comment by GreLI** [comment]
Why not to allow to add `elem: 'switcher'` in `content`?

**Comment by narqo** [comment]
It's a really weird API, when two different things do the same stuff. And it's getting weirder when you try to document such API (this is the reason we haven't documented `content` field of the `button`).
