### ISSUE TITLE
Drop bem-tools support

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-components#1816]
Looks like there's no reason to keep `bem-tools` npm deps and configs here as templates for `bem create` are in `bem-core`.

// cc @veged

**Comment by veged** [comment]
but how I get bem-tools here if there is no `devDependencies`?

**Comment by tadatuta** [comment]
You mean there's someone who needs `bem-tools` while working on `bem-components` and that person can't install it without such dependency? ;)

**Comment by veged** [comment]
exactly!

**Comment by tadatuta** [comment]
I don't believe such person exists. And even if he exists how often he's going to use `bem create` inside `bem-components`? Once in a year or two?

And take a look on amount of useless code we can get rid of: https://github.com/bem/bem-components/pull/1819 (as well as 4 top-level npm dependencies).

**Comment by veged** [comment]
ok — and do not say that it is impossible to convince me ;-)
