### ISSUE TITLE
overused `applyNext()` calls

### ISSUE THREAD

**Issue by Guria** [bem/bem-components#1858]
In some places looks overused, because it much simpler just to pass values in ctx.
- https://github.com/bem/bem-components/blob/99ba4f447e762b76992adec927649fd74686beeb/common.blocks/input/input.bemhtml.js#L5
- https://github.com/bem/bem-components/blob/99ba4f447e762b76992adec927649fd74686beeb/common.blocks/input/__control/input__control.bemhtml.js

Is it intended or subject to fix?

**Comment by miripiruni** [comment]
In first link `applyNext(…)` reasonable.
In second link there is no `applyNext()` at all.

In general `applyNext()` is OK. Why you open this task? Can we close it?
