### ISSUE TITLE
link: move pseudo-specific behavior to corresponding mod

### ISSUE THREAD

**Issue by fi11** [bem/bem-components#186]
Стоит хотя бы одному блоку link поставить js: true, все остальные ссылки тоже подключают js, и как следствие не работает дефолтный переход по href. Наверное стоит убрать js в модификатор pseudo как было в bem-bl

**Comment by fi11** [comment]
или лучше, наверно просто убрать liveBindTo по умолчанию, а кому надо, например для модификатора pseudo,  добавит в live секцию: liveBindTo({modName: 'pseudo', modVal: true})

**Comment by gela-d** [comment]
@dfilatov Дим, это в v2

**Comment by tadatuta** [comment]
@dfilatov Дим, согласен с тем, чтобы завести `_pseudo`, сделать PR или есть лучшее решение?

**Comment by narqo** [comment]
А нельзя просто `preventDefault` дергать только для `_disabled`?

**Comment by tadatuta** [comment]
`preventDefault` имеет смысл на всех ссылках с `href`, которые предполагают какую-то js-обработку, но такие ссылки раньше были псевдоссылками (см. https://github.com/bem/bem-bl/blob/0.3/blocks-desktop/b-link/_pseudo/b-link_pseudo_yes.js), а теперь этот же код попал в базовый блок.

**Comment by narqo** [comment]
Я про то, что сейчас у ссылок есть событийное API, через которое с ними можно взаимодейстовать: например повесить счетчики кликов. При этом превентить нативное поведение не обязательно

**Comment by dfilatov** [comment]
@tadatuta про `_pseudo` cогласен
