### ISSUE TITLE
inputs should trigger dom/jquery 'change' in the same time as bem 'change'

### ISSUE THREAD

**Issue by tyv** [bem/bem-components#187]
if you want to know your form has any changes its easy to subscribe to it like this:

``` javascript
this.bindTo(this.domElem, 'change', function(e) { // this.domElem is form
    this.trigger('change');
});
```

as you know dom elems, like input trigger it's change only on blur, bem inputs has cool mechanism to solve that problem. 
so my advice is to add this.elem('control').change(); after this bem change trigger: https://github.com/bem/bem-components/blob/v1/common.blocks/input/input.js#L71

**Comment by tyv** [comment]
same need to be added to blocks (look below), because they didn't trigger dom/jquery change at all
checkbox: https://github.com/bem/bem-components/blob/v1/common.blocks/checkbox/checkbox.js#L50
radiobox (didnt test): https://github.com/bem/bem-components/blob/v1/common.blocks/radiobox/radiobox.js#L85 and https://github.com/bem/bem-components/blob/v1/common.blocks/radiobox/radiobox.js#L177

**Comment by dfilatov** [comment]
You should use BEM-events and binds like `BEM.blocks['input'].on(domElem, 'change', ...)` where `domElem` is form, instead using of low-level DOM-events.

**Comment by tyv** [comment]
I dont know what exactly form elements will appear in my form.
so do I need in this case to repeat this subscription for all?

**Comment by dfilatov** [comment]
You need introduce high-level block, e.g. `form`, with approximately the following code (in case of v2):

``` javascript
modules.define('i-bem__dom', function(provide, BEMDOM) {

BEMDOM.decl('form', {
    onSetMod : {
        'js' : {
            'inited' : function() {
                ['input', 'radio', 'checkbox', 'select'].forEach(function(block) {
                    BEMDOM.blocks[block].on(this.domElem, 'change', this._onControlChange, this);
                }, this);
            },
            ...
        },
        ...
    },

    _onControlChange : function(e) {
        // e.target is a block that has changed
    },
    ...
});

provide(BEMDOM);

});
```

**Comment by dfilatov** [comment]
May be later we introduce in v2 subscription to all block to reduce the code:

``` javascript
 ['input', 'radio', 'checkbox', 'select'].forEach(function(block) {
    BEMDOM.blocks[block].on(this.domElem, 'change', this._onControlChange, this);
}, this);
```

to:

``` javascript
BEMDOM.blocks['*'].on(this.domElem, 'change', this._onControlChange, this);
```

**Comment by tyv** [comment]
thanks!

**Comment by narqo** [comment]
@dfilatov Maybe we could implement this `form` block as part of bem-components#v2?

**Comment by dfilatov** [comment]
@narqo I don't mind, but we must think about the interface (methods, events, etc).
