### ISSUE TITLE
Writing lib styles with postcss-nested and pobem insted stylus

### ISSUE THREAD

**Issue by belozer** [bem/bem-components#1885]
Example from bem-components
https://gist.github.com/belozyorcev/4a6dd62f2750f4f7dac6127ea281dc7e

Rewrtite with [postcss-nested](https://www.npmjs.com/package/postcss-nested) and [pobem](https://www.npmjs.com/package/pobem)
https://gist.github.com/belozyorcev/888b67c87b4f1ed27231c33ab4c5dd2c

**Comment by belozer** [comment]
Or button_theme_islands

https://gist.github.com/belozyorcev/4171da6fd247ad2ff9afd30f73862a52

**Comment by tadatuta** [comment]
@Guria created [an issue](https://github.com/bem/bem-components/issues/1535) to switch from stylus long time ago and we kinda agree with it.

@belozyorcev, will you be able to help us to convert `bem-components` to postCSS if we finally agree on needed plugin chain?

**Comment by belozer** [comment]
@tadatuta It's my duty

**Comment by tadatuta** [comment]
Closed in favor of https://github.com/bem/bem-components/issues/1535
