### ISSUE TITLE
Add link to live demo page and add blocks screenshots

### ISSUE THREAD

**Issue by a-x-** [bem/bem-components#1923]
Can we run showcase page as a demo service?

https://github.com/bem/bem-components/pull/1122

And, as I think, we have to add a lot of pictures to current readme.
As a quick solution, I propose adding `button`, `checkbox`, `input`, `radio` and `spin` screenshots.

**Comment by a-x-** [comment]
The following picture is very incompact (sparse/scattered/tenuous).
![](https://cloud.githubusercontent.com/assets/1658415/5200975/d9fcffc4-757c-11e4-9353-dc0801364084.png)

Block must be placed more closely in my vision.

**Comment by tadatuta** [comment]
we strongly believe that `bem-components` documentation should be viewed at https://en.bem.info/libs/bem-components/ where there's a link to https://en.bem.info/libs/bem-components/3.0.0/showcase/ at the very top of the menu.

**Comment by a-x-** [comment]
Ok
