### ISSUE TITLE
Не миксуются блоки к блокам link, button

### ISSUE THREAD

**Issue by yar-usenko** [bem/bem-components#1956]
Из за
```js
mix()({ elem : 'control' })
```

к блокам link и button ничего нельзя примиксовать. Возможно есть ещё блоки с подобным поведением.

Предалагаю изменить на
```js
mix()({ elem : 'control' }).concat(this.ctx.mix || [])
```

**Comment by tadatuta** [comment]
@yar-usenko это справедливо только для `bem-xjst` версий >= 8.x, где было изменено поведение режимов и добавлены новые `add*` режимы (см. https://github.com/bem/bem-xjst/releases/tag/v8.0.0).
`bem-components` сейчас не поддерживают `bem-xjst 8.x`, соответствующая задача — https://github.com/bem/bem-components/issues/1942

**Comment by yar-usenko** [comment]
@tadatuta спасибо)
