### ISSUE TITLE
The `modal__autocloseable` closes immediately after opening in touch browsers (touch events)

### ISSUE THREAD

**Issue by veged** [bem/bem-components#1958]
Button opens modal with autocloseable modifier. After click modal shows a one moment. It's happens because modal catches 'click' event. The 'click' event is a program event after 'touchend'.

I can reproduce in iOS (bem-core#v4), AndroidBrowser (bem-core#v4, bem-core#v3), Chrome for Android (bem-core#v4, bem-core#v3), Chromium on Windows 10 with touchscreen (bem-core#v4, bem-core#v3).

@vsesh

**Comment by veged** [comment]
@vsesh Can you say in which Android versions this can be reproduced?

**Comment by veged** [comment]
Looks like we can move `click` emiting from https://github.com/bem/bem-components/blob/v4/common.blocks/button/button.js#L119 to `pointerclick`.

**Comment by vsesh** [comment]
@veged I could reproduce in Android 4.x and 5.0.

**Comment by narqo** [comment]
@vsesh doesn't meta with `device-width` solve the problem?

```
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=3">
```
