### ISSUE TITLE
Modal: inside blocks not init

### ISSUE THREAD

**Issue by aliosv** [bem/bem-components#1991]
Для вставки попапа используется $.append(вместо BEMDOM.append), который не вызывает инициализацию внутренних блоков
https://github.com/bem/bem-components/blob/v5/common.blocks/popup/popup.js#L41

**Comment by dfilatov** [comment]
Вроде как внутренности попапа находятся на странице до его открытия и должны быть инициализированы еще до этого места.

**Comment by aliosv** [comment]
у меня попапы/модалки почти всегда создаются динамически

**Comment by dfilatov** [comment]
Так когда они создаются ты их как добавляешь? Не через BEMDOM.* методы?

**Comment by aliosv** [comment]
раньше так и делал, а потом увидел, что достаточно только выставить модификатор visible:true, и они сами себя вставят.

**Comment by dfilatov** [comment]
Не совсем понял про "они сами себя вставят". Можешь пример кода показать?

**Comment by aliosv** [comment]
````
var modal = $(BEMHTML.apply({ block:'modal })).bem('modal');
modal.setMod('visible', true);
````

**Comment by dfilatov** [comment]
На мой взгляд, закладываться на то, что при перемещении себя в body попап должен почему-то инициализировать свои внутренности, нельзя. Это чисто техническая операция для того чтобы z-index'ы правильно работали. Инициализация в этот момент была бы очень странным побочным эффектом.

**Comment by aliosv** [comment]
> перемещении себя в body

без предварительной вставки через BEMDOM.* получаем создание, а не перемещение. Т.е. следуя этой логике перед перемещением нужно проверять вставлен ли блок в DOM, и если нет - ничего не делать по onSetMod:{visible:true}.
Тогда и неочевидность 
> Это чисто техническая операция

пропадет

**Comment by dfilatov** [comment]
```js
var modal = BEMDOM.init(BEMHTML.apply({ block:'modal' })).bem('modal');
```

**Comment by dfilatov** [comment]
> Тогда и неочевидность

Это не неочевидность, а внутренняя логика блока, о которой снаружи вообще знать не нужно. Другие же блоки не ведут себя так, почему этот должен?

**Comment by aliosv** [comment]
>  снаружи вообще знать не нужно

на сколько помню, я узнал об этом функционале именно из-за того, что забыл добавить вставку с помощью BEMDOM. 
> почему этот должен?

но ведь нигде и не написано, что не должен

В общем ответ ясен - любые блоки вставлять всегда через BEMDOM. Можно закрывать.
