### ISSUE TITLE
Example from readme doesn’t work

### ISSUE THREAD

**Issue by miripiruni** [bem/bem-components#1992]
Look at https://github.com/bem/bem-components#working-with-the-library-as-dist method 2 doesn’t work. I just copied code example to index.html, open it and saw:

<img width="432" alt="screen shot 2017-01-07 at 19 35 35" src="https://cloud.githubusercontent.com/assets/144537/21743305/82836a12-d510-11e6-99d0-cdb8ca07725d.png">

The select doesn’t open on click. Console without JS errors. What am I doing wrong?

**Comment by tadatuta** [comment]
Init's missed :(

```diff
@@ -9,7 +9,7 @@
     <form class="form" action="/"></form>
 <script src="https://yastatic.net/bem-components/latest/desktop/bem-components.no-autoinit.js+bemhtml.js"></script>
 <script>
-modules.require(['i-bem__dom', 'BEMHTML', 'jquery'], function(BEMDOM, BEMHTML, $) {
+modules.require(['i-bem__dom', 'BEMHTML', 'jquery', 'i-bem__dom_init'], function(BEMDOM, BEMHTML, $, init) {
     var html = BEMHTML.apply({
         block : 'select',
         mods : { mode : 'check', theme : 'islands', size : 'm' },
@@ -24,6 +24,8 @@ modules.require(['i-bem__dom', 'BEMHTML', 'jquery'], function(BEMDOM, BEMHTML, $
     });

     BEMDOM.append($('.form'), html);
+
+    init();
 });
 </script>
 </body>
```

We'll update the docs, thanks for the report!

**Comment by dfilatov** [comment]
@tadatuta Но там же вроде вызывается `BEMDOM.append`, который делает инициализацию.

**Comment by tadatuta** [comment]
@dfilatov для вставленной через `BEMDOM.append()` разметки достаточно просто явно зарекваирить `i-bem-dom__init` (при автоинициализации он предоставляется за счет `i-bem-dom_init_auto`, который не включен в сборку в данном случае), но, кмк, в данном примере есть смысл и явно дергать `init()`, т.к. часть разметки присутствует на странице заранее и потенциально может содержать БЭМ-блоки.

**Comment by dfilatov** [comment]
Для вставленной через `BEMDOM.append` не должно быть нужно никакого `i-bem-dom__init`, так как внутри зовется `BEMDOM.init`: https://github.com/bem/bem-core/blob/v3/common.blocks/i-bem/__dom/i-bem__dom.js#L1095

**Comment by tadatuta** [comment]
Насколько я понимаю, кто-то все-таки должен явно рекваирить `i-bem-dom__init` из-за https://github.com/bem/bem-core/blob/cfb1332f89b692d613dff3a5cc31dc4f5f8a1178/common.blocks/i-bem-dom/i-bem-dom.js#L1101-L1111

Собственно, вот песочница, где можно проверить: https://jsfiddle.net/tb8e8k2b/

**Comment by dfilatov** [comment]
Это да (кто-то все-таки должен явно рекваирить `i-bem-dom__init`), но должно все работать без `init()`, который ты явно написал. Пример-то вроде про `select` и вызов общего `init()` тут не нужен.

**Comment by tadatuta** [comment]
Это пример про использование dist-поставки `bem-components`, а не именно `select`-а (вот он https://github.com/bem/bem-components#working-with-the-library-as-dist). И потенциально разметка может быть на странице заранее. Я бы все-таки оставил, т.к. использующие dist вряд ли сильно переживают об оптимизации, а когда часть блоков не будет работать, могут и не разобраться в чем дело.

**Comment by dfilatov** [comment]
Все-таки, в этом случае, этот пример выглядит скорее запутывающим для меня: вставляется результат в конкретный DOM-элемент, а `init` зовется на все DOM-дерево.

**Comment by tadatuta** [comment]
ок, заменю на комментарий

**Comment by tadatuta** [comment]
Fixed in https://github.com/bem/bem-components/pull/1993
