### ISSUE TITLE
Скомпилированный CSS в npm и bower

### ISSUE THREAD

**Issue by awinogradov** [bem/bem-components#1994]
__Лирика:__
Постпроцессинг в пакетах на ES6, ES7 нужен только для удобства разработки. Сами пакеты поставляются в скомпилированном виде. Если необходимо кастомное поведение то всегда можно поставить пакет с гитхаба и радоваться. Но сама же поставка в скомпилированном виде позволяет не обязывать пользователей ставить себе процессоры или траншпиллеры с плагинами. 

__По делу:__
Сейчас компоненты поставляются в PostCSS как есть + CSS. Почему нельзя оставить PostCSS только в репозитории? Это решит несколько проблем сразу. Люди смогут использовать компоненты с любым сборщиком и технологиями и не вникать в чудо pobem. Если идея в нейминге, то это кастомщина и ее можно получить из репозитория. Ведь так или иначе в деве дефолтный нейминг. 

Откуда пошло: https://github.com/awinogradov/enb-postcss/issues/34

**Comment by tadatuta** [comment]
Я не вижу проблем в текущем виде (если не считать текущую поломку на уровне технологии сборки, которую просто нужно починить): пользователи вот прямо сейчас могут использовать компоненты с любым сборщиком и технологиями и не вникать в чудо pobem.

**Comment by awinogradov** [comment]
Как-то я упустил https://github.com/bem/bem-components/blob/v5/compile-postcss.js
