### ISSUE TITLE
link_disabled: mustn't have appearance as an active link

### ISSUE THREAD

**Issue by dfilatov** [bem/bem-components#2004]
Currently it has the same color, hover state and so on.

**Comment by tadatuta** [comment]
It was considered as won't fix in https://github.com/bem/bem-components/issues/537 (see https://nda.ya.ru/3SeuJu for details).

**Comment by dfilatov** [comment]
But it looks really weird. I have a set of `link_pseudo` which mustn't be available unless some condition is satisfied. And appearance should help users rather than confuse them.

**Comment by birhoff** [comment]
Where i can like for this as a bug?

**Comment by tadatuta** [comment]
All we need to fix it is official appearance for disabled link in `islands` theme.
I'll try to ask in internal mail once again.

**Comment by tadatuta** [comment]
Oh, I found styles in islands repo: https://nda.ya.ru/3SfY2o
Let's use them in bem-components as well.

**Comment by dfilatov** [comment]
@tadatuta Could you port it to v4 at least?

**Comment by tadatuta** [comment]
sure

**Comment by dfilatov** [comment]
and would be kind if to v3 as well )

**Comment by tadatuta** [comment]
done

**Comment by dfilatov** [comment]
👍
