### ISSUE TITLE
inaccuracy in the documentation

### ISSUE THREAD

**Issue by innomerphey** [bem/bem-components#2116]
https://ru.bem.info/libraries/classic/bem-components/6.0.0/touch-pad/icon/#%D0%9F%D0%BE%D0%BB%D0%B5-content-6
Should be `{
    block : 'icon',
        content : {
                html: '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"><path d="M1 13v2h14v-2h-14zm13-7h-3v-5h-6v5.031l-3-.031 6 6 6-6z"/></svg>'
}`

https://github.com/bem/project-stub/issues/256

**Comment by tadatuta** [comment]
@lim-bo Thank you, fixed in https://github.com/bem/bem-components/pull/2117/files
