### ISSUE TITLE
select: make block

### ISSUE THREAD

**Issue by dfilatov** [bem/bem-components#227]
- text
  - [x] static
  - [x] dynamic (initial state)
  - [x] dynamic with short titles
- [ ] icons
  - [x] options icon
  - [ ] ~~button icon~~
- width
  - [x] adaptive
  - [ ] ~~by the longest item~~
  - [x] max-width (+ #528)
  - [ ] ? ~~inline-width~~
- selection
  - [x] radio
  - [x] *check
- closable
  - [x] radio
  - [x] *check
- focus
  - [x] click inside menu
  - [x] close on blur
- keyboard
  - [x] open on <Space>
  - [x] open on <Arrow Up/Down> keys
  - [x] check (uncheck) options on <Space>
- [x] scroll
- [x] max height for options list
- [ ] ~~custom items~~ (#529)
- [x] disable state
- [ ] ~~content update~~ (build new select instead)

**Comment by fi11** [comment]
Может стоит из селекта выделить его специфическую часть в отдельный блок?  Что бы можно было собрать любой другой кастомный селект из этого блока, дропдауна и других нужных компонентов. Это например функционал отвечающий за выбор, как по клику, так и с клавиатуры.

**Comment by mishanga** [comment]
@fi11 готовый select нужен для простоты использования, а кастомный селект можно легко собрать из dropdown+menu.

**Comment by voischev** [comment]
А почему отказались от иконки в кнопке? Или я не правильно понял перечеркнутый текст?

**Comment by voischev** [comment]
Кажется нашел багу. 

Когда селекту задаешь отрицательный сдвиг попап не выбадает. 

margin или left

```
{
            block : 'select',
            mods : { type : 'radio', theme : 'normal', size : 'm' },
            name : 'select1',
            textMaxWidth : 100,
            attrs : { style : 'margin-left: -16px;' },
            optionsMaxHeight : 100,
            options : [
                { val : 1, text : 'first' },
                { val : 2, text : 'second', checked : true },
                { val : 3, text : 'third' },
                { val : 4, text : '4' },
                { val : 5, text : '5' },
                { val : 6, text : '6' },
                { val : 7, text : '7' },
                { val : 8, text : '8' },
                { val : 9, text : '9' },
                { val : 10, text : '10' },
                { val : 11, text : '11' },
                { val : 12, text : '12' },
                { val : 13, text : '13' },
                { val : 14, text : '14' }
            ]
        }
```

**Comment by tavriaforever** [comment]
ура) круто!

**Comment by dfilatov** [comment]
к сожалению, попытка прикрутить это к реальному проекту выявила фатальные недостатки, нужно доделывать.

**Comment by voischev** [comment]
Ждем :)

**Comment by dfilatov** [comment]
@tavriaforever @voischev вроде довели до работоспособного состояния
