### ISSUE TITLE
tumbler: make block

### ISSUE THREAD

**Issue by dfilatov** [bem/bem-components#229]

**Comment by mishanga** [comment]
nobody needs this

**Comment by losogudok** [comment]
guys, really need this block

**Comment by veged** [comment]
@losogudok sorry, but we recommend to use [`checkbox`](https://ru.bem.info/libs/bem-components/v2.4.0/desktop/checkbox/) or [`radio-group`](https://ru.bem.info/libs/bem-components/v2.4.0/desktop/radio-group/) — it's better for user experience
