### ISSUE TITLE
spin: make block

### ISSUE THREAD

**Issue by dfilatov** [bem/bem-components#230]

**Comment by sipayRT** [comment]
@dfilatov @mishanga насчет ИЕ9 - лучше поддерживать спиннер с помощью js-a(как в islands) или лучше просто добавить гифку?

**Comment by mishanga** [comment]
Я бы сделал гифку и повесил её на модификатор типа spin_css2, чтобы можно было опционально подключать.
Только для гифки важно не забыть вешать фон на модификатор _progress, иначе гифка продолжает крутиться, даже если не видна.

**Comment by mishanga** [comment]
Сделано в #324
