### ISSUE TITLE
Move 'release' event for block 'button' from v1 to v2

### ISSUE THREAD

**Issue by apsavin** [bem/bem-components#242]
What about that useful event?

**Comment by apsavin** [comment]
pull request https://github.com/bem/bem-components/pull/243

**Comment by dfilatov** [comment]
We have removed this event (and `press` too) from v2.
Could you provide example of the usefulness of `release` event?

**Comment by apsavin** [comment]
well, what event should i use to handle click and keypress both?

**Comment by dfilatov** [comment]
`click` event should work in both case. Doesn't it work?

**Comment by apsavin** [comment]
1. only pointer triggers 'click' event now (so mouse and touch [handles](https://github.com/bem/bem-components/blob/v2/common.blocks/button/button.js#L101), [keyboard](https://github.com/bem/bem-components/blob/v2/desktop.blocks/button/button.js#L56) [no](https://github.com/bem/bem-components/blob/v2/desktop.blocks/button/button.js#L70))
2. is it really good name for common event? I don't think so.

**Comment by dfilatov** [comment]
We use native button inside, it trigger dom-event `click` on keyboard event, then `pointerclick` wrapper from bem-core should pass it transparently and bem-event `click` should be emitted. If it is not, there is bug.

**Comment by apsavin** [comment]
Oh, I see now, thanks.
