### ISSUE TITLE
input: Ленивая инициализация

### ISSUE THREAD

**Issue by persidskiy** [bem/bem-components#292]
Привет! 
Сейчас инпут не имеет ленивой инициализации, чтобы выставлять `_focused` на себя, если контрол имел фокус. Не было ли идеи, при инициализации страницы смотреть на `document.activeElement`, и, если это `.input__control`, то форсить инициализацию?

/cc @dfilatov @narqo

**Comment by dfilatov** [comment]
Помимо фокуса, есть еще проблемы, например, наличие очищающего крестика. Его показ зависит от наличия значения у инпута. Соответственно, у неинициализированных инпутов адекватно оценить его можно только синициализировав сам инпут.

**Comment by arikon** [comment]
@dfilatov Ровно такую проблему разбираем сейчас в `ISLCOMPONENTS-539`

**Comment by persidskiy** [comment]
Можно в `BEMHTML` проверять: если есть `_has-clear` и `val`  не пустой, то сразу выставляем
`__clear_visible`

B еще идея решения проблемы с фокусировкой:

``` js
 BEMDOM.decl({block: 'input', modName: 'focused', modValue: true}, {}, {
    live: function() {
        this.__base();
        return false;
    }
});
```

**Comment by dfilatov** [comment]
1. Недостаточно это проверить только в шаблонах с учетом автокомплитов в браузерах.
2. Это не будет работать, статические свойства общие в пределах блока и его модификаторов.
