### ISSUE TITLE
attach: Drop "buttonText" field from block's BEMJSON API

### ISSUE THREAD

**Issue by narqo** [bem/bem-components#296]
BEMJSON for block `attach` could be specified as

``` js
{ block : 'attach', buttonText : 'text', /* .. */ }
```

and

``` js
{ block : 'attach', button : { block : 'button' }, /* .. */ }
```

Guess we could drop support for `buttonText` field and use polymorphic `button`, like we do in `dropdown`.

\cc @veged @dfilatov

**Comment by dfilatov** [comment]
:+1:

**Comment by veged** [comment]
+1
