### ISSUE TITLE
input: Add ability to use HTML5 input types

### ISSUE THREAD

**Issue by dkushnikov** [bem/bem-components#302]
Судя по коду common.blocks/input/__control
установить кастомный type для input, без переопределения шаблона никак нельзя?

**Comment by dfilatov** [comment]
Сейчас поддерживаются три типа: textarea, search, password.

**Comment by dkushnikov** [comment]
Чтобы сделать возможность добавить email и tel, нужно сделать bemhtml шаблон, также как и у password?

**Comment by dfilatov** [comment]
Я думаю, что можно отрефакторить базовый шаблон, в котором прозрачно пробрасывать этот атрибут в `attrs`, а в `_type_textarea` перекрыть его.

**Comment by aristov** [comment]
Решили сделать отдельный блок `textarea` (#1033) вместо модификатора `input_type_textarea`. Таким образом, модификатор `_type` становится более консистентным с HTML-атрибутом `type` (точнее с его новыми значениями, добавленными в HTML5, такими как `email`, `tel`, `url` и т.п.).
Договорились о том, что для каждого значения подобных атрибутов следует создавать свой модификатор, в котором и реализовано добавление нужного атрибута элементу `__control`. Кроме того, этот модификатор может содержать в себе дополнительные стили, логику или доопределения, реализующие функциональность атрибутов в тех браузерах, которые ее пока не поддерживают.
