### ISSUE TITLE
controls: На тачах контролы работают с багами

### ISSUE THREAD

**Issue by gela-d** [bem/bem-components#309]
button, checkbox
На iPad (iOS7) не нажимаются кнопки и чекбоксы
Проверял на кнопке-ссылке, которая должна отправлять на какую-нибудь другую страницу (например с добавлением якоря (anchor))
На Андроид-планшете не работают только кнопки, чекбокс работает.
На WP8 все работает хорошо.
Баг воспроизводится на всех трех стилях - дефолт, simple, normal (проверяли на чекбоксе на iPade с iOS7)

**Comment by dfilatov** [comment]
Мы влили новую реализацию pointer-ивентов, можешь протестировать еще раз? Или кто-нибудь другой с доступом на кучу устройств.

**Comment by gela-d** [comment]
Извините, упустила почему-то этот issue.
Договорились что в начале сентября Сережа Бритвин будет тестировать всю библиотеку.
От резульатов и полученных багов и будет плясать и заводить issue.
