### ISSUE TITLE
menu: make CSS

### ISSUE THREAD

**Issue by dfilatov** [bem/bem-components#315]
Use `issues/307@v2` as base branch.
- [x] icons (try to make them consistently with button block)
- [x] groups and groups with titles
- [x] checked mod, checked mod within group, checked mod + icons,  checked mod within group + icons

**Comment by sipayRT** [comment]
@veged @dfilatov @mishanga а можно мне сделать эту таску, чтобы влиться в вашу работу? никто не против?

**Comment by veged** [comment]
это совсем не самая простая задача — как минимум в режиме парного программирования должен участвовать @mishanga или кто-то кому он доверит

**Comment by narqo** [comment]
@mishanga menu влили в v2

**Comment by persidskiy** [comment]
А почему иконки не вынесли в отдельный блок?

**Comment by narqo** [comment]
Мы оставили `TODO` про иконки в `menu`. Посмотрим, как часто нужно будет копи-пастить одно и тоже (и на сколько оно действительно «одно и тоже») пока будем делать остальные контролы и решим, надо ли оно и в каком виде.

**Comment by sipayRT** [comment]
[влито](https://github.com/bem/bem-components/commit/ba10b769673b1ae387752a3be4c54fe00f528526)
