### ISSUE TITLE
link: Properly react on mod disable

### ISSUE THREAD

**Issue by narqo** [bem/bem-components#317]
`link_disabled` should not contain `href` attribute!

**Comment by narqo** [comment]
Guess, setting `tabindex: -1` would be much better solution

**Comment by dfilatov** [comment]
In case of tabindex you can't prevent opening of link in a new window by right click, but in case of href you can.

**Comment by dfilatov** [comment]
@narqo What's left to do here?

**Comment by narqo** [comment]
A month ago, I thought that it would be much faster to do it as part of `base-control`'s stuff. Guess I was wrong ;(
