### ISSUE TITLE
Pass data on change

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-components#328]
I thinks it'd be useful to pass data on change of every control in the library as it's done for input.

// cc @dfilatov @veged

**Comment by narqo** [comment]
Could you provide some use cases for other controls where this will be useful? 

As I understand, custom `data` could (or should) be used in cases where you call `Control#setVal()` method explicitly. But only some of our controls have it: `input`, `radio` and `attach`. 

For me this kind of API looks pointless for controls like `checkbox`, because you don't want change it's value in general. The only thing you need is to check control's "state", so we have common getter-method for this:

``` js
Checkbox.on('change', function(e) {
  console.log(e.target.hasMod('checked'));
  console.log(e.target.getVal());
});
```

**Comment by tadatuta** [comment]
isn't it straighter and more consistent to have possibility always get value with the same interface?

for `checkbox` we can pass value in data param just for `checked` state so just

``` javascript
Checkbox.on('change', function(e, data) {
  console.log(data);
});
```

would be enough.

**Comment by narqo** [comment]
There is nothing about consistency to look up for `value` key in `data` object for input, but `cheched` key for `checkbox`:

``` js
[Intput, Checkbox].forEach((blockClass) => blockClass.on('change', function(e, data) {
  // what was changed,
  // input's `value` or checkbox's `checked`?
  if(e.target.block instanceOf Checkbox) console.log('new value', data.changed)
  else console.log('new value', data.value)

  // in case of web forms, they both have `value` field, 
  // which should be send to server
  e.target.block.getVal();
});
```

Actually the only useful thing about custom data in `change` handler is ability to pass some guards from `setVal()`, like we did for [input_has-clear](https://github.com/bem/bem-components/blob/v2/common.blocks/input/_has-clear/input_has-clear.js#L16-L20).

**Comment by qfox** [comment]
@narqo The logic here could be in data object with the current and previous values. Or filled string and empty string (as opposite) for `checkbox`.

@tadatuta Are you sure that checkbox emits `'change'` event? I don't feel it atm.

**Comment by tadatuta** [comment]
@zxqfox it's not [anymore](https://github.com/bem/bem-components/commit/f556ccbe5fab5172cbbbb6dada8b118f150f8237#diff-9f0eb74d96423c7c0569aa3b1610be33L17), now you are to bind to `_checked` modifier for it

**Comment by qfox** [comment]
@tadatuta That's not funny thing. But thanks for a link.
