### ISSUE TITLE
borschik: update to 1.0.0

### ISSUE THREAD

**Issue by mishanga** [bem/bem-components#338]
Wildcards support was implemented in https://github.com/bem/borschik/pull/54
Now we can update version in `package.json` and write config file `.borschik` with defaults.

**Comment by narqo** [comment]
I'll try it, but it seems to me that it should be updated in bem-tools as well.

From the semver point of view borshik@1.0.0 is backward incompatible with borshik @ 0.7.x which is used as a dependency inside bem-tools. Npm will continue to install both versions, so bem-tools will use it's dependency, not ours.

**Comment by veged** [comment]
is it actual?

**Comment by tadatuta** [comment]
@veged nope, it's already there
