### ISSUE TITLE
button: getName, getVal & setVal methods

### ISSUE THREAD

**Issue by aristov** [bem/bem-components#346]

**Comment by persidskiy** [comment]
Will you do it? Or this issue waits for a contributor?

**Comment by aristov** [comment]
Now it waits.

**Comment by narqo** [comment]
JFI: The `get*` part of this issue would be done with #326

**Comment by sipayRT** [comment]
can we close this issue?

**Comment by aristov** [comment]
yes

**Comment by aristov** [comment]
done with https://github.com/bem/bem-components/pull/326
