### ISSUE TITLE
menu: pass disabled mod to every nested menu-item

### ISSUE THREAD

**Issue by dfilatov** [bem/bem-components#352]

**Comment by sipayRT** [comment]
can I make this issue in #315?

**Comment by narqo** [comment]
#315 is about written CSS styles. It would be much cleaner and easily to review if javascript and specs related to it would be done with a separate task.

**Comment by dfilatov** [comment]
@sipayRT but you could do that in separate issue and PR

**Comment by dfilatov** [comment]
@sipayRT ping

**Comment by sipayRT** [comment]
@dfilatov sorry for delay
