### ISSUE TITLE
attach: don't use BEMHTML in js

### ISSUE THREAD

**Issue by dfilatov** [bem/bem-components#355]

**Comment by mishanga** [comment]
As we agreed, BH should provide itself as BEMHTML.

**Comment by aristov** [comment]
Wait for https://github.com/enb-bem/enb-bem-techs/issues/69

**Comment by blond** [comment]
We can use `modules.isDefined` to detect the name of the template engine module.

``` js
modules.define(
    'attach',
    [modules.isDefined('BEMHTML') ? 'BEMHTML' : 'bh'],
    function(provide, BEMHTML) {

/* ... */

}
```

**Comment by veged** [comment]
@andrewblond no need in such complexity — BH should do mimicry for BEMHTML
