### ISSUE TITLE
input: make _readonly modifier

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-components#369]
It possible now to set HTML-attributes for controls just with full form of bemjson.

// cc @aliosv

**Comment by aristov** [comment]
https://github.com/bem/bem-components/issues/962

**Comment by aristov** [comment]
https://github.com/bem/bem-components/issues/302

**Comment by aristov** [comment]
@tadatuta why did this issue initially appear? Do anybody need `readonly` attribute as a part of the library, or we can close the issue with `wontfix` and tell users how to make it independently at the project level?

**Comment by tadatuta** [comment]
there was a request from @aliosv but I think we can close the issue and he can take implementation from https://github.com/bem/bem-components/pull/1052 if it's still needed
