### ISSUE TITLE
Предложение настроить тестирование на сервисе saucelabs

### ISSUE THREAD

**Issue by ilyar** [bem/bem-components#389]
https://saucelabs.com/opensource

[![Selenium Test Status](https://saucelabs.com/browser-matrix/bootstrap.svg)](https://saucelabs.com/u/bootstrap)

**Comment by persidskiy** [comment]
У нас вроде и так тесты через saucelabs гоняются в travis-е.

/сс @narqo

**Comment by narqo** [comment]
Еще нет, но в планах есть

**Comment by dfilatov** [comment]
we have experiment with saucelabs and gemini -- so let's think about wide use of saucelabs after it
