### ISSUE TITLE
Use `box-shadow` instead of opacity `border` for all components borders

### ISSUE THREAD

**Issue by veged** [bem/bem-components#397]
Right now we use opacity `border` but can use `box-shadow`.

**Comment by gela-d** [comment]
With box-shadow we have some problems during zooming
![2014-04-17_1159](https://cloud.githubusercontent.com/assets/1333220/2729283/7b065220-c606-11e3-96d1-4c67f76d7134.png)
What is the reason to change all borders?

**Comment by mishanga** [comment]
`border` affects size of element. It's very unuseful when you trying to work with an element in JavaScript.

**Comment by dfilatov** [comment]
The main reason is accordance to our visual guide.

**Comment by persidskiy** [comment]
With `border` buttons has ugly corners :(
