### ISSUE TITLE
popup: [IE 10] не выставляется модификатор visible

### ISSUE THREAD

**Issue by mishanga** [bem/bem-components#402]

**Comment by dfilatov** [comment]
The underlying problem is `pointerpress` event that's triggered twice on each `mousedown` in IE10. Seems like bug in `jquery__event_type_pointerpressrelease` by @deepsweet.

**Comment by dfilatov** [comment]
Corresponding issue in bem-core: https://github.com/bem/bem-core/issues/505

**Comment by narqo** [comment]
@dfilatov it seems that we have a logical problem in our `Popup → setMod → visibility → yes` handler. Look at [this part](https://github.com/bem/bem-components/blob/84dd6bacc8e1139770015b9661dee2b50ff54caf/common.blocks/popup/popup.js#L72-L81):

1) we call `_updateIsOwnerVisible()` on line 74
2) within `_updateIsOwnerVisible` we check `_direction` mod to calc owner visibility state (see [line 333](https://github.com/bem/bem-components/blob/84dd6bacc8e1139770015b9661dee2b50ff54caf/common.blocks/popup/popup.js#L333))
3) but it we don't have any `_direction` mod until we call `redraw()` method, which happens only in the end of `_visibility_yes`'s handler. So IE (somehow) decided that owner is hidden

**Comment by narqo** [comment]
Actually, if you change `_updateIsOwnerVisible`, so it'll return `true` for every call, everything works fine.

**Comment by dfilatov** [comment]
Is everything works fine if owner is `button` (see example with `dropdown`)?

**Comment by narqo** [comment]
That would be fixed with bem/bem-core#509

**Comment by narqo** [comment]
@mishanga @dfilatov could you check this with current [bem-core@v2.2.1](https://github.com/bem/bem-core/releases/tag/v2.2.1)?

**Comment by dfilatov** [comment]
@mishanga Is it actual?

**Comment by mishanga** [comment]
I'll check it.

**Comment by mishanga** [comment]
I got no IE10 nearby :( Can you check it by yourself? http://nda.ya.ru/3QTPrP

**Comment by sipayRT** [comment]
work for me - http://jing.yandex-team.ru/files/sipayrt/2014-06-30_0008.swf

**Comment by mishanga** [comment]
@sipayRT great, thanks!
