### ISSUE TITLE
popup: remake offsets param, add ability to have a offset from the window

### ISSUE THREAD

**Issue by dfilatov** [bem/bem-components#410]
I suggest to split `params.offsets` to `params.mainOffset`, `params.secondaryOffset`, `params.viewportOffset`.

**Comment by dfilatov** [comment]
@narqo @veged what do you think about that?

**Comment by veged** [comment]
I like this variant more: `params.offsets = { main: 5, secondary: 5, viewport: 5 }`

**Comment by dfilatov** [comment]
It's less convenient to extend (we have no deep extend) and describe in jsdoc.

**Comment by veged** [comment]
yeep... I know, I know — but repeated `*Offset` looks so ugly :-/
