### ISSUE TITLE
Implement counter block

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-components#421]
I think about two modifiers for `counter` block: `_provider_metrika` and `_provider_analytics`.

**Comment by narqo** [comment]
Don't you this that this is not a bem-component's space to have this kind of block?

**Comment by tadatuta** [comment]
dunno. counter is a must for any site. until we don't have enough blocks which are different from core and components why not to put them here?

**Comment by narqo** [comment]
Both Metrika and Analytics provide complex APIs for the the counters. I can't image a block that will provide suitable abstraction for both of them. 

For me it's easy to copy and paste some silly snippet of code that counter service gives me. But at the same time, hardcore analytics will always have there own view of what kind of setup they need.

I really want to think about our libraries as a set of blocks that user can't live without. Not as a set of blocks that user could use.

**Comment by tadatuta** [comment]
> I can't image a block that will provide suitable abstraction for both of them.

If it's really impossible we can create two different blocks.

> a set of blocks that user can't live without

I don't think there are many sites without any counters at all. So it seems to be exactly such a block ;)

**Comment by dfilatov** [comment]
We have discussed about it with @veged @narqo -- considered to close it (should create separate library for this)
