### ISSUE TITLE
Rename radio controls

### ISSUE THREAD

**Issue by dfilatov** [bem/bem-components#422]
Before we add `checkbox-group`, I suggest to make following changes:
- rename `radio` to `radio-group`
- rename `radio-option` to `radio`

**Comment by dfilatov** [comment]
@veged @mishanga @narqo 
I need your opinions.

**Comment by narqo** [comment]
I had some apprehensive about `checkbox-group`, but now it feels right

**Comment by mishanga** [comment]
:+1:
