### ISSUE TITLE
button: correct '_focused' modifier behavior

### ISSUE THREAD

**Issue by innabelaya** [bem/bem-components#424]
Two buttons at once can be focused on a page. If a '_focused_true' modifier is set for one button and you click the another one (in range of one theme), this button becomes focused too. 
Checked for simple and normal themes
Link to screenshot: http://yadi.sk/d/AdD6kUAUNVF2Q

**Comment by dfilatov** [comment]
I couldn't reproduce that. Could you provide more details?
