### ISSUE TITLE
Using blocks in BEMJSON which provide strings

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-components#448]
For example

In `attach.bemhtml` there is

``` js
this.isSimple(button) && (button = {
                block : 'button',
                tag : 'span',
                text : button
            });
```

which won't work when `i18n` is used in bemjson:

``` js
{
            block : 'attach',
            mods : { theme : 'simple' },
            button : {
                block: 'i-bem',
                elem: 'i18n',
                keyset: 'attach',
                key: 'button-text'
            },
            noFileText : {
                block: 'i-bem',
                elem: 'i18n',
                keyset: 'attach',
                key: 'no-file'
            }
        }
```

**Comment by sipayRT** [comment]
the same problem is in the dropdown block etc. What should we do?
@veged @mishanga

**Comment by veged** [comment]
we does not merge https://github.com/bem/bem-core/pull/514 yet — how it can work?

**Comment by tadatuta** [comment]
@veged the question is not about this particular block or i18n engine but about the way we write our templates. we test fields of bemjson to be `isSimple` to replace them with some block which content is source string in quite a few blocks already.

if we consider such approach is fine @sipayRT will rewrite them in BH and we will use same idea in new blocks but I think that as soon as we start using any i18n system it become a problem. so I just want to discuss it before we must support backward compatibility.

**Comment by veged** [comment]
ouch!... yep, we need to think about it...-- 
  Сергей Бережной

**Comment by deeonis** [comment]
@tadatuta could you plz provide more examples of such blocks which provide strings (as `i-bem__i18n` do)?

**Comment by deeonis** [comment]
@dfilatov @narqo

**Comment by veged** [comment]
the best what we invent is do something like this:

``` js
    this.isSimple(button) || button.block === 'i18n' && (button = {
        block : 'button',
        tag : 'span',
        text : button
    });
```

but since that issue doesn't hurt anyone much I suggest to wait for better approaches

**Comment by tadatuta** [comment]
irrelevant since there's no support for i18n in BEMJSON in `bem-core`
