### ISSUE TITLE
checkbox_type_button: Allow mixes

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-components#460]

**Comment by dfilatov** [comment]
Why only `checkbox`? And why only `_type_button`?

**Comment by tadatuta** [comment]
@dfilatov it seem that's the only block with such an issue, isn't it?

**Comment by dfilatov** [comment]
@tadatuta No. What's the difference between `checkbox_type_button` and `radio_type_button`?

**Comment by tadatuta** [comment]
@dfilatov Added same fix: https://github.com/bem/bem-components/pull/474
