### ISSUE TITLE
Module "button": can't resolve dependence "keyboard__codes" 

### ISSUE THREAD

**Issue by kompolom** [bem/bem-components#514]
В зависимостях button есть блок keyboard, в bem-core нет блока keyboard...
Проект создавал generator-bem-stub (До этого пользовался project stub и все было норм)

**Comment by narqo** [comment]
Наверное стоит переадресовать задачу в generator-bem-stub?

Возможно приезжает неправильная версия bem-core. Модуль `keyboard__codes` вошел в [bem-core 2.2.0](https://github.com/bem/bem-core/releases/tag/v2.2.0).

**Comment by kompolom** [comment]
Да, приезжает bem-core v2.1 В общем то проблема решилась обновлением bem core до 2.2.2
Как переадресовать задачу? Просто открыть новую в их репозитории?

**Comment by blond** [comment]
Завёл задачу в генераторе https://github.com/bem/generator-bem-stub/issues/23

**Comment by eGavr** [comment]
Починим в следующей версии генератора!
