### ISSUE TITLE
select: Add ability to navigate by typing

### ISSUE THREAD

**Issue by narqo** [bem/bem-components#531]
See native select behaviour for example.

**Comment by persidskiy** [comment]
Click yellow button [here](http://auto.yandex.ru/compare?id=on&id=9275341) for inspiration ;)

**Comment by narqo** [comment]
Native select works in a little different way. In your example I can't type "B" and than select "Audi" by pressing Up arrow.

But the real question is "How should it work for `_type_*check` mods"?

**Comment by hcodes** [comment]
resolves #1054
