### ISSUE TITLE
label как блок

### ISSUE THREAD

**Issue by voischev** [bem/bem-components#538]
Есть мысли на тему почему бы не сделать блок label как отдельный блок? 
Даже в ваших примерах есть код который хорошо иллюстрирует проблему: 

```
{ tag : 'p', content : [
            {
                block : 'input',
                elem : 'label',
                id : 'with-label',
                content : 'label'
            },
            ': ',
            {
                block : 'input',
                id : 'with-label',
                mods : { theme : 'normal', 'has-clear' : true, size : 'm' },
                val : 'separate',
                placeholder : 'placeholder'
            }
        ] }
```

А в случае с составным инпутом — вставлять блок label вместо елемента

Бывают случаи в вертске:  
label [ input ] [ input ] [ input ] 

Еще если не указывать id у лейбла то код ломается.

**Comment by sipayRT** [comment]
привет.
Это код из тестов - там могут быть различные кейсы для тестирования. Правильное использование label описано в документации. id генерируется автоматически. Например:

```
{
    block : 'input',
    mods : { theme : 'normal', size : 'm', 'has-label' : true },
    label : 'Label',
    placeholder : 'normal'
}
```

**Comment by voischev** [comment]
Привет. Да в случае когда один инпут = один лейбл все отлично. 

Кейс такой: Есть например страница редактирования статьи СМИ портала, там куча всяких инпутов/селектов/кнопочек и тд с лейблами. Стиль у лейблов одинакоый — соответснвенно хочется сделать его отдельным блоком. 

Что касается input+label все отлично сделано, но если применять лейбл не с input все плохо. Хочется какой то большей возможности работы с лейблом. 

Раскажите как делаете вы, я возможно пересмотрю свой взгляд

**Comment by sipayRT** [comment]
@Coltspb Вань, вы там у себя на сервисе как это делаете? И делаете ли вообще? :)

**Comment by voischev** [comment]
@sipayRT Если бы не делал, и было бы удобно работать с тем что есть не спрашивал :) Ну вот например кусок со статическими данными 

```
{
            block : 'editor-grid',
            content : [
                {
                    elem : 'l',
                    content : [
                        {
                            block : 'input',
                            elem : 'label',
                            id : 'type',
                            content : 'Тип'
                        },
                        {
                            block : 'select',
                            mods : { theme : 'editor' },
                            val : 2,
                            id : 'type',
                            options : [
                                { val : 1, text : 'Статья'},
                                { val : 2, text : 'Новость'},
                                { val : 3, text : 'Фотоотчет'},
                                { val : 4, text : 'Интервью'}
                            ]
                        }
                    ]
                },
                {
                    elem : 'r',
                    content : [
                        {
                            block : 'input',
                            elem : 'label',
                            id : 'day',
                            content : 'Дата публикации'
                        },
                        {
                            block : 'select',
                            mods : { theme : 'editor' },
                            val : 23,
                            id : 'day',
                            options : [
                                { val : 21 },
                                { val : 22 },
                                { val : 23 },
                                { val : 24 }
                            ]
                        },
                        {
                            block : 'select',
                            mods : { theme : 'editor' },
                            val : 3,
                            id : 'monts',
                            options : [
                                { val : 1, text : 'Января'},
                                { val : 2, text : 'Ноября'},
                                { val : 3, text : 'Сентября'},
                                { val : 4, text : 'Уебря'}
                            ]
                        },
                        {
                            block : 'select',
                            mods : { theme : 'editor' },
                            val : 2014,
                            id : 'year',
                            options : [
                                { val : 2012 },
                                { val : 2013 },
                                { val : 2014 },
                                { val : 2015 }
                            ]
                        },
                        {
                            block : 'input',
                            mods : { theme : 'normal', size : 'xl' },
                            attrs : { style : 'width : 88px; margin-left: 20px;' },
                            val : '16:37',
                            placeholder : 'Время'
                        }
                    ]
                }
            ]
```

Кстати жду ваш select ;)

**Comment by sipayRT** [comment]
ненене, я другого Ваню спрашивал :)

**Comment by voischev** [comment]
@sipayRT вот еще предложили быструю реализацию https://gist.github.com/verybigman/090af0ebd0d4c58bee60

**Comment by mishanga** [comment]
@voischev ты говоришь про сложную форму, состоящую из кирпичиков.
Мы про это уже давно думаем, т.к. задача довольно распространённая и она даже шире, чем ты описываешь, т.к. кроме собственно html-вёрстки часто бывает нужна валидация формы.

В качестве примера сложной формы мы держали в голове онлайн-заявки на кредит известных банков:
https://anketa.vtb24.ru/auto/
http://www.sberbank.ru/moscow/ru/person/credits/home/buying_complete_house/
https://www.raiffeisen.ru/retail/mortgageloans/program/request/

Для работы с такой формой мы придумали блок `form`, у которого могут быть элементы:
- `control` — абстрактный контрол, который может быть технически реализован через любой атомарный контрол,
- `label` — как раз то, о чём ты писал, чтобы было удобно пачкой делать лейблы для контролов,
  У этого блока удобное абстрактное API, которое позволяет удобно валидировать и сериализовать входные данные, работая с набором инпутов как с простым объектом.

Работа над блоком ведётся здесь: https://github.com/bem/bem-components/pull/293
Присоединяйся к обсуждению :)

**Comment by mishanga** [comment]
@voischev добавлю еще несколько тезисов, от которых мы отталкиваемся:
- простое должно быть простым
- сложное должно быть возможным
- много сложного можно автоматизировать и показать как простое

Вынесение элемента label из блока input — это как раз сложное, но возможное.
Если тебе нужно сделать это несколько раз — автоматизируй. Например, через блок form.

**Comment by voischev** [comment]
@mishanga Спасибо, со всем согласен! Жду новые блоки

**Comment by qfox** [comment]
@mishanga Это не тезисы! Это — КОНЦЕПЦИЯ!

**Comment by voischev** [comment]
И как движется? )

**Comment by tadatuta** [comment]
@voischev отложили как минимум до выпуска стабильной версии bem-components
