### ISSUE TITLE
input: move border styles from .input__box to .input 

### ISSUE THREAD

**Issue by persidskiy** [bem/bem-components#548]
The  main reason to do this is ability to clearly customizing input in cases like this one:
![disk](https://cloud.githubusercontent.com/assets/1527181/3139894/13be6fca-e8f8-11e3-8375-03615da21806.png)
In old-school input we have to hack inner elements (like `__hint`, `__found`, `__requery` etc.) for shift them from left border. I think more robust way is moving these elemets into `.input__box` and border styles to `.input`, it allow us to customizing left or right sides of input without hacks.

Also, I think it's unnecessary ability to insert `__label`, `__samples`, `__message` into input, because label good binds with input by `id`, and samples or messages rather refers to any outer block (like form).

**Comment by mishanga** [comment]
Я по-вражески не очень, буду по-нашему.
Короче, часто бывает полезно что-нибудь подхачить внутри инпута, добавить туда хинт, тапахед, количество найденного и всякое такое. Это всё логично класть внутрь инпута, но при этом не ломать box.
Пример с Афишей не подходит, т.к. стрелочка с именем сервиса является отдельным блоком, не связанным с инпутом.
