### ISSUE TITLE
strange signs in bem-components default russian page

### ISSUE THREAD

**Issue by Murdalay** [bem/bem-components#590]
В разделе "Использование" у меня в сафари и трусах последней версии отображается следующее:

"Подключить библиотеку в проект любы�� известным способом."

**Comment by Murdalay** [comment]
http://ru.bem.info/libs/bem-components/v2/

**Comment by tadatuta** [comment]
Баг связан со сборкой сайта и не имеет отношения к `bem-components`. Будет чиниться в рамках отдельной задачи.
