### ISSUE TITLE
ie: Graceful degradation

### ISSUE THREAD

**Issue by gela-d** [bem/bem-components#597]

**Comment by dfilatov** [comment]
@gela-d What is this issue about?

**Comment by gela-d** [comment]
@dfilatov It's actual issue, I'll take it after gemini-tests

**Comment by mishanga** [comment]
I can take it. At least some blocks, spin first of all.

**Comment by gela-d** [comment]
@mishanga Ok, also we have the project about сross-browser compatibility

**Comment by gela-d** [comment]
Our spin (and other blocks) works in supported IE9 and >
Can we close  this issue?
