### ISSUE TITLE
base-control: rename block to `control`

### ISSUE THREAD

**Issue by mishanga** [bem/bem-components#656]
Relates with #540

**Comment by narqo** [comment]
For now `base-control` is totally abstract and doesn't have any representations in DOM. It's main goal is to be a `baseBlock` for other "controls". How does it relate to the problem, described in #540?

**Comment by mishanga** [comment]
radio => radio-group
checkbox => checkbox-group
control => control-group

Name `control` is enough abstract, `base-` prefix is redundant.

**Comment by dfilatov** [comment]
+1 to @mishanga
