### ISSUE TITLE
Use Stylus instead of Roole

### ISSUE THREAD

**Issue by mishanga** [bem/bem-components#679]
- [x] write styles (#717)
- [x] build configuration (#736)
- [x] get rid of roole (#750)

**Comment by chayn1k** [comment]
:+1:

**Comment by tavriaforever** [comment]
:+1:

**Comment by denchistyakov** [comment]
:+1:

**Comment by gela-d** [comment]
@mishanga Let's our group do this.

**Comment by mishanga** [comment]
@gela-d сейчас гораздо важнее допилить все блоки, препроцессор пока особой роли не играет. Кроме того, мне нужно с этим разобраться, чтобы потом в Серп вкручивать.
Если у меня руки не дойдут в ближайшее время, я обращусь к вам за помощью :)
