### ISSUE TITLE
input: Add ability to take all available width 

### ISSUE THREAD

**Issue by dfilatov** [bem/bem-components#704]

**Comment by dfilatov** [comment]
Is there any progress?

**Comment by gela-d** [comment]
Sorry, I forgeot about this task.
I'll look today. Is here the same decision like a select task?

**Comment by dfilatov** [comment]
Yes, I think solution will be simpler than in `select`.

**Comment by gela-d** [comment]
@dfilatov Are we need this case for theme `simple`? This question is for the select task too.

**Comment by dfilatov** [comment]
I think yes.
