### ISSUE TITLE
select: Default state is not default

### ISSUE THREAD

**Issue by gela-d** [bem/bem-components#731]
Select with `theme`:
![1](https://cloud.githubusercontent.com/assets/1333220/3412770/ff36e41c-fe03-11e3-8d09-1bc86bbb7b47.png)
Select without `theme`
![2](https://cloud.githubusercontent.com/assets/1333220/3412906/8b1dbd2e-fe05-11e3-9957-b3a876945f6a.png)

What I expected
![4](https://cloud.githubusercontent.com/assets/1333220/3413051/21e76b50-fe07-11e3-9fcb-be8362485cb0.png)

I thought, that our contorls should be honestly default :)
For example, in case with the disabled items and groups, in default we have this:
![3](https://cloud.githubusercontent.com/assets/1333220/3412949/0d923276-fe06-11e3-89dc-22bd27bf0edc.png)

**Comment by gela-d** [comment]
@dfilatov @mishanga @sipayRT

**Comment by dfilatov** [comment]
@gela-d Sorry, I don't understand what exactly we should discuss (

**Comment by mishanga** [comment]
@dfilatov blocks with no theme should have native appearance.

**Comment by dfilatov** [comment]
@mishanga Our block couldn't be replaced by native control. What would you expect in case of `select_type_radio-check`?
It's not about appearance, it's about behaviour.

**Comment by mishanga** [comment]
@dfilatov I just said what @gela-d meant :)
@gela-d we don't even have native `<select>` inside block, it's too custom.

**Comment by gela-d** [comment]
@dfilatov @mishanga Ok, thanks
