### ISSUE TITLE
Убрать остатки внешнего вида из контролов

### ISSUE THREAD

**Issue by veged** [bem/bem-components#75]
Сейчас есть всякие остатки от внутреннего дизайна, например:
- галочка в `checkbox`
- крестик в `attach` и `input`
- иконка файла в `attach`
- ...

Наверное, это не совсем честно и нужно сделать `bem-controls` ещё более обезличенными.

cc @tadatuta @lento4ka @dfilatov

**Comment by lento4ka** [comment]
Нужно перенести дизайн во все примеры. В противном случае контролы будут действительно обезличенными. И добавить описание.

**Comment by veged** [comment]
dublicate by #81
