### ISSUE TITLE
popup_theme_normal: Completely hide popup until one is initialized

### ISSUE THREAD

**Issue by narqo** [bem/bem-components#809]
According to specs, elements with `visibility: hidden` property set are still occupy space in the layout, so the could affect initial page Layout time. 

At the same time we could fix that without any cost, with hiding `popup`s until they become initialized (e.g. got `popup_js_inited` CSS class).

See "[Render-tree construction, Layout, and Paint](https://developers.google.com/web/fundamentals/performance/critical-rendering-path/render-tree-construction)" article (for example) for inspiration ;)

**Comment by dfilatov** [comment]
Is animation working properly now?

**Comment by narqo** [comment]
At least I haven't noticed any difference in our "simple" example of `select`. Checked in Chrome and Firefox.
