### ISSUE TITLE
There is a lot of CSS in library that pretend to be "design free"

### ISSUE THREAD

**Issue by veged** [bem/bem-components#81]
cc @lento4ka @gela-d @tadatuta @dfilatov

**Comment by gela-d** [comment]
Explain, please :)

**Comment by lento4ka** [comment]
Поконкретнее пожалуйста...

**Comment by dfilatov** [comment]
Во многих стилях есть установка цветов, бэкграундов, ширин, высот, паддингов, отступов (причем вида 0.38em), что очень странно для библиотеки, которая абстрагирована от дизайна.

**Comment by lento4ka** [comment]
Да, там нужно просмотреть стили и вынести их.

**Comment by dfilatov** [comment]
we gonna fix it ;-)
