### ISSUE TITLE
button: Cross-browser compatibility

### ISSUE THREAD

**Issue by gela-d** [bem/bem-components#819]
Fx & Chrome
![2014-07-14_1345](https://cloud.githubusercontent.com/assets/1333220/3569219/ae89f1cc-0b3b-11e4-8794-4794ca11e457.png)

**Comment by gela-d** [comment]
Договорились, что до 3 версии, главное, чтобы все контролы в одном браузере соответствовали одной базовой линии.

**Comment by dfilatov** [comment]
Нет, мы не так договорились. Мы договорились что в 2.x мы исправим это.

**Comment by gela-d** [comment]
> Нет, мы не так договорились. Мы договорились что в 2.x мы исправим это.

Так, я запуталась :) Что мы называем 2.x ?
Из разговора с Мишей, я поняла, что мы договорились делать единую базовую линию во всех браузерах в следующей версии, так как там все непросто с ней и придется много переделывать. В ближайшем релизе нужно сделать соответствие базовой линии в каждом браузере и про отличие Fx и Chrome мы знаем.
@mishanga Миш?

**Comment by mishanga** [comment]
Ближайший релиз — 2.0, Дима говорит про 2.1.

**Comment by gela-d** [comment]
Так значит, что в данной задаче мы ничего критичного не исправляем. Потом, по всем блокам, будет масштабная работа по соответствию во всех браузерах.
