### ISSUE TITLE
popup не закрывается

### ISSUE THREAD

**Issue by kompolom** [bem/bem-components#872]
<code>BEMDOM.scope.append(this.domElem);</code> Ошибка возникает на <a href="https://github.com/bem/bem-components/blob/v2/common.blocks/popup/popup.js#L167">этой строке</a>. В <code>BEMDOM</code> не находит св-во <code>scope</code>
Браузер chrome 34 linux
<code>
"bem-core": "git://github.com/bem/bem-core.git#v2.3.0",
    "bem-components": "git://github.com/bem/bem-components.git#4685e5aa5383dc3a5612b648c679cb004ca67df0"
</code>

**Comment by dfilatov** [comment]
А каким образом происходит начальная инициализация? Такое могло произойти, если, каким-то образом, начальная инициализация случилась до DOM-ready.

**Comment by kompolom** [comment]
Я не совсем понял "каким образом"? Блок инициализируется автоматически.

**Comment by kompolom** [comment]
Точнее непонятно, каким образом начальная инициализация может получиться раньше DOM ready...

**Comment by dfilatov** [comment]
Вот поэтому я и спрашиваю. Можно как-то код увидеть?

**Comment by kompolom** [comment]
Да, сейчас выложу

**Comment by kompolom** [comment]
https://github.com/kompolom/popup

**Comment by kompolom** [comment]
https://github.com/kompolom/popup/blob/master/desktop.bundles/index/index.bemjson.js - bemjson просто скопирован из тестов

**Comment by dfilatov** [comment]
А это воспроизводится именно в chrom'е под linux?

**Comment by kompolom** [comment]
TypeError: BEMDOM.scope is null  в firefox и chrome под win

**Comment by kompolom** [comment]
в scope вообще, что должно быть? Dom элемент? или блок?

**Comment by kompolom** [comment]
Возможно, где-то посмотреть блок popup в рабочем состоянии?

**Comment by dfilatov** [comment]
в scope должно быть `body` -- https://github.com/bem/bem-core/blob/v2/common.blocks/i-bem/__dom/i-bem__dom.js#L1480

**Comment by kompolom** [comment]
Похоже блоки действительно инитятся раньше времени... Но почему так получается - непонятно

**Comment by dfilatov** [comment]
Они не то что "инитятся" раньше, каким-то образом метод попапа `redraw` вызывается раньше этого.
Можешь посмотреть в какой момент у тебя происходит https://github.com/bem/bem-core/blob/v2/common.blocks/i-bem/__dom/i-bem__dom.js#L1480, потому что на тестовых примерах я не могу это воспроизвести.

**Comment by kompolom** [comment]
1) <code>var DOM = BEM.decl('i-bem__dom',/*\* @lends BEMDOM.prototype _/{</code>
2)<code> provide(DOM);</code> (из i-bem__dom)
3)<code>provide(BEMDOM.decl(this.name, /_\* @lends popup.prototype */{</code>
4)<code>DOM.scope = $('body'); </code>(из i-bem__dom)

Дальше, по клику вызывается <code> popup.redraw() </code>\- где DOM.scope === NULL

**Comment by deeonis** [comment]
@kompolom попробуй с самой свежей версией, там исправлено проставление `DOM.scope`

**Comment by Guria** [comment]
Обратите внимание на #1377, в частности:

> Also take a note that it is not save to assume that BEMDOM.scope will contain document.body because it could be redefined. See [this forum post](https://github.com/bem/bem-forum-content-ru/issues/237) for reference.

**Comment by qfox** [comment]
По смыслу там вместо `save` должно быть `safe`.

**Comment by tadatuta** [comment]
В обсуждении на форуме https://ru.bem.info/forum/issues/305/ выяснили, что проблема решена
