### ISSUE TITLE
attach.js require BEMHTML (not work with bh)

### ISSUE THREAD

**Issue by pahaz** [bem/bem-components#876]
I use enb+bh. And can not use attach block without bemhtml (client js).
https://github.com/bem/bem-components/blob/v2/common.blocks/attach/attach.js#L7

(Error: Uncaught Error: Module "attach": can't resolve dependence "BEMHTML")

What do you think about this? May be fix it?

**Comment by tadatuta** [comment]
You are right, we already have an issue about it: https://github.com/bem/bem-components/issues/355

**Comment by mishanga** [comment]
As we agreed, BH should provide itself as BEMHTML.
