### ISSUE TITLE
button: difference from guide in button with icon

### ISSUE THREAD

**Issue by DimaChervan** [bem/bem-components#877]
Guide and yandex browser
![button](https://cloud.githubusercontent.com/assets/6004201/3686413/e5a6f9a0-1317-11e4-9733-89f75b08a0f8.png)

**Comment by mishanga** [comment]
@gela-d поправите?

**Comment by gela-d** [comment]
@mishanga Да, конечно

**Comment by deeonis** [comment]
we will wait for new guidelines

**Comment by aristov** [comment]
Close in favour of #1581.
