### ISSUE TITLE
README: описать политику поддержки браузеров

### ISSUE THREAD

**Issue by mishanga** [bem/bem-components#892]

**Comment by innabelaya** [comment]
@aristov @mishanga Привет! Подскажите, пожалуйста, что писать в README? Была идея не писать браузеры с версиями списком, который будет постоянно устаревать, а описать общую идею. Какая у нас политика поддержки браузеров?

**Comment by mishanga** [comment]
Надо написать те версии, которые описаны в конфиге автопрефиксера:
https://github.com/bem/bem-components/blob/v2/.enb/make.js#L357-L374
Список не может быстро устаревать, потому что мы обязаны обеспечивать поддержку заявленных браузеров в рамках мажорной версии. Список (как и конфиг) будет изменяться только с выпуском очередной мажорной версии.

**Comment by innabelaya** [comment]
@mishanga спасибо за ответ!

**Comment by innabelaya** [comment]
https://github.com/bem/bem-components/pull/1178
