### ISSUE TITLE
popup: Add ability to specify z-index

### ISSUE THREAD

**Issue by persidskiy** [bem/bem-components#894]
Привет. Я примерил popup к кейсам, которые мы сейчас используем в продакшене. Он себя показал очень хорошо, но не смог решить одну проблему: 
1. Есть фиксированный блок (шапка)
2. На странице есть различные попапы (например, [календарь на серпе](http://yandex.ru/yandsearch?text=билеты%20москва%20санкт-петербург&lr=2))
3. При скроле, этот попап должен заезжать под шапку. Сейчас там просто понижен z-index, а в новом попапе это сделать нельзя из-за зашитого пула.
4. Тогда мы повышаем на шапке z-index, и все попапы из шапки начинают открываться под нее из-за того же пула. 
5. С этой проблемой сталкивались уже на многих сервисах, кажется, нужно уметь решать ее из коробки.

/cc @dfilatov @veged @narqo

**Comment by dfilatov** [comment]
Ну это похоже все-таки на исключительный случай. Почему мы этой шапке не дать просто гораздо больший `z-index`?

**Comment by persidskiy** [comment]
@dfilatov В том и дело, что если даешь шапке больший z-index, то все попапы из шапки начинают залезать под нее

**Comment by dfilatov** [comment]
@Coltspb да, я понял теперь проблему

**Comment by veged** [comment]
Обсудили вместе с @dfilatov и @narqo. Придумали понятие `z-index-group` — т.е. вместо одной группы "выше всех" (z-index: 10000) будет возможность задать несколько слоёв. По умолчанию всё работает как сейчас, но если к шапке (или любому другому родителю `owner`-а `popup`-а) примешан `{ block : 'z-index-group', mods : { level : 2 } }` то попапы откладываются уже от `2 * 10000` (и т.д. для большего количества групп и левелов). Так же будет возможность явно задать `zIndexGroupLevel` (особенно актуально для `popup`-ов которые открываются по координатам, без `owner`).

**Comment by veged** [comment]
@Coltspb проверь теперь на своих кейсах, всё ли удаётся выразить?

**Comment by persidskiy** [comment]
Вроде ок, но не понятно, чем оно лучше кроме того, что позволяет  отсчитывать индексы от дочерних блоков `z-index-group`. И это сделано ценой `findBlockOutside()`, что не очень хорошая практика, да?

И опять же, появилась неоднозначность способов задания z-index: можно и примешать `z-index-group_level_*`(читай, задать в css), а можно и добавить js-параметр. Похоже на костыль. А еще оно магически суммируется.

Еще остался баг, когда перемещаешь попап из одного родительского попапа в другой, то z-index не обновляется.

**Comment by veged** [comment]
сам по себе `findBlockOutside` не является чем-то запретным — тут он вполне уместен

это не неоднозначность — `z-index-group` и параметр именно что "суммируются", а не заменяют друг друга

**Comment by persidskiy** [comment]
Нашел еще баг:

``` js
{
    block : 'popup', 
    zIndexGroup : 10, 
    content : {
        block : 'popup', // Этот попап отображается под родителем
        content : 'I\'m popup'
    }
}
```

**Comment by narqo** [comment]
> Нашел еще баг: [..]

А что является owner'ом для вложенного popup'а?
