### ISSUE TITLE
разработка и тестирование флоу переводов с xliff

### ISSUE THREAD

**Issue by Murdalay** [bem/bem-components#896]

**Comment by deeonis** [comment]
@Murdalay опиши подробнее — в чем суть этой задачи?

**Comment by aristov** [comment]
@Murdalay ping

**Comment by Murdalay** [comment]
Привет. Задача довольно старая. Сейчас по ней ведутся активные работы в Питере. Суть в том, что у нас есть xliff-ферма, помогающая автоматизировать переводы. Раньше она умела работать только с dita. И было решено научить ее поддержке mdown. Сейчас такая поддержка уже есть и процесс на стадии тестирования. В момент разработки было решено натравить ее на bem-components для пробы. Полагаю, что задачу можно закрывать т.к. в репозиторий прямых изменений вносится не будет.
