### ISSUE TITLE
control-group : Динамическое добавление контролов

### ISSUE THREAD

**Issue by voischev** [bem/bem-components#957]
Реализовал с помощью этого блока такой случай: 
- Изначально в группе один контролл.
- Динамически добавляю в группу новые контроллы. 

Проблема: Заметил одну деталь работы блока `control-group` — когда в группе находится один контрол то левые бордеры у него не закругленные.  

Кажется что нужно это пофиксить :)

**Comment by tadatuta** [comment]
@voischev сможешь предложить пулл-реквест?

**Comment by voischev** [comment]
@tadatuta Да посмотрю.

**Comment by gela-d** [comment]
@voischev @tadatuta По-моему, это чинится простым стилем - https://github.com/bem/bem-components/commit/f6d0d81e82a79fbf8b21c11c7c4288e524f885e3

Пример control-group с несколькими блоками и одним:
![333](https://cloud.githubusercontent.com/assets/1333220/4175079/10ffc320-35be-11e4-8533-875f00bc1ccf.png)

**Comment by mishanga** [comment]
норм

**Comment by voischev** [comment]
@gela-d Спасибо! Уже используем код в проектах )
