### ISSUE TITLE
popup.js: delMod('visible') broken

### ISSUE THREAD

**Issue by aliosv** [bem/bem-components#965]
https://github.com/bem/bem-components/blob/v2/common.blocks/popup/popup.js#L558
**zIndexes** is undefined by default
PR #966
/cc @tadatuta, @veged

**Comment by dfilatov** [comment]
Could you provide sequence of your actions?

**Comment by aliosv** [comment]
https://github.com/aliosv/project-stub/tree/bem-components.965

**Comment by dfilatov** [comment]
?

**Comment by aliosv** [comment]
there is demonstration of bug, build it to see

**Comment by dfilatov** [comment]
I've cloned your repo, pointed browser to `desktop.bundles/index/index.html` and haven't seen anything about this bug.

**Comment by aliosv** [comment]
check browser console.
![image](https://cloud.githubusercontent.com/assets/2275425/4042137/0a921ca2-2d00-11e4-9e27-87c7d74e2aa2.png)

**Comment by dfilatov** [comment]
I see nothing interesting in browser console.

**Comment by dfilatov** [comment]
Could you provide your actions step by step?

**Comment by aliosv** [comment]
git clone git@github.com:aliosv/project-stub.git -b bem-components.965
npm i
bem server
.../index.html

win 7, checked in latest ff, chrome, yabrowser

**Comment by dfilatov** [comment]
I've understood. You are trying to set `visible : true` modifier from bemjson. That case isn't supported right now at all, because only js can properly position popup. We should add notes about that in documentation.

**Comment by aliosv** [comment]
ok, thanks

**Comment by innabelaya** [comment]
добавила информацию в блок `popup`(в рамках #944), спасибо!
