### ISSUE TITLE
Syntax errors of inline examples in docs

### ISSUE THREAD

**Issue by blond** [bem/bem-components#969]
Варнинги можно будет увидеть при сборке примеров `enb make examples` после вливания https://github.com/bem/bem-components/pull/956
- [ ] `examples/common.blocks/button/button.en.md` — ReferenceError: check is not defined
- [ ] `examples/common.blocks/button/button.en.md` — ReferenceError: radio is not defined
- [ ] `examples/common.blocks/button/button.ru.md` — ReferenceError: radio is not defined
- [ ] `examples/common.blocks/checkbox/checkbox.ru.md` — SyntaxError: Unexpected identifier

**Comment by gela-d** [comment]
Андрей, поправила все. @andrewblond

**Comment by gela-d** [comment]
@innabelaya Инна, глянь, на всякий случай, мой комит - https://github.com/bem/bem-components/commit/1719da7f522303bd2cd524440d44943d3ee63918
