### ISSUE TITLE
Merge lint + specs tasks in Travis

### ISSUE THREAD

**Issue by persidskiy** [bem/bem-components#980]
Something tells me that most of the time in `lint` task spending for installing dependencies. Maybe merging this task into specs will speedup the assembling?

@arikon What a reason was to separate this task?

**Comment by tadatuta** [comment]
we also run `csscomb` there which is absolutely useless for `stylus`

**Comment by arikon** [comment]
Merge it

29.08.2014, 23:17, "Ivan Persidsky" notifications@github.com:

> Something tells me that most of the time in lint task spending for installing dependencies. Maybe merging this task into specs will be better approach?
> 
> @arikon What a reason was to separate this task?
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail
