### ISSUE TITLE
(radio|checkbox)-group_theme_simple: Make styles for button_togglable_radio

### ISSUE THREAD

**Issue by gela-d** [bem/bem-components#997]
Дима переделал радио и чекбокс -  https://github.com/bem/bem-components/pull/978, чтобы они заработали в ИЕ9. Для радио, контрол и чекбокс-групп, в которых есть кнопки и другие контролы, пришлось переписать css. 
Стили кнопок, которые в группе, для темы simple поломались. 
Для того, чтобы все стало хорошо, их нужно перенести из кнопки https://github.com/bem/bem-components/blob/v2/design/common.blocks/button/_theme/button_theme_simple.styl#L92-L129
в стили `(radio|checkbox)-group_theme_simple` в виде:

```
.radio-group_theme_simple
{
    .radio_type_button
    {
        &:first-of-type .button_togglable_radio,
        &~ .radio_type_button .button_togglable_radio
        {
            border-right-width: 0;
        }

        &~ .radio_type_button .button_togglable_radio
        {
            border-radius: 0;
        }

        &:first-of-type .button_togglable_radio
        {
            border-top-right-radius: 0;
            border-bottom-right-radius: 0;
        }

        &:last-of-type .button_togglable_radio
        {
            border-right-width: 1px;
            border-top-right-radius: 3px;
            border-bottom-right-radius: 3px;
        }
    }
}
```

Минусы: копипаст в два блока, состояние ховера на кнопке отваливается (но это не страшно, визуально для тестовой темы - все ок)

Как сейчас:
![1](https://cloud.githubusercontent.com/assets/1333220/4165267/767b5e3a-3500-11e4-87ce-a629fc20eca0.png)
После фикса:
![2](https://cloud.githubusercontent.com/assets/1333220/4165273/7b6f2d54-3500-11e4-8985-3cbf371c5055.png)

**Comment by mishanga** [comment]
В simple можно воровать-убивать. А лучше вообще не тратить время.
